readme.md

Updated Readme.md to show contributors as image. Image link was generated on contrib.rocks

Updated Readme with all contributors shown as image

---

packages/bruno-app/src/components/RequestPane/QueryUrl/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/index.js
packages/bruno-app/src/components/Welcome/index.js
tests/home.spec.js
tests/pages/home.page.js

this PR consists of:
- add selector IDs
- include an e2e test for the Create Collection flow 
test result:

feat: Create Collection e2e test

---

package.json
tests/home.spec.js

- use fakerjs as random test data

feat: add fakerjs

---

packages/bruno-app/src/components/Welcome/StyledWrapper.js
packages/bruno-app/src/components/Welcome/index.js

Collection items whole div made as action button and cursor pointer added to the whole div, including icons.

Collections icons partially working #59 - resolved

---

package.json

Script "prettier:web":"npm run prettier --workspace=packages/bruno-app" added in bruno/package.json

chore: prettier script added in root bruno/package.json

---

packages/bruno-app/src/components/RequestTabPanel/index.js

- Introduced `MIN_LEFT_PANE_WIDTH = 300`
- replaced value `5` with `DEFAULT_PADDING` = 5

Issue:62,fix Split line should have max squeeze limit

---

packages/bruno-app/src/components/RequestPane/FormUrlEncodedParams/StyledWrapper.js
packages/bruno-app/src/components/RequestPane/MultipartFormParams/StyledWrapper.js
packages/bruno-app/src/themes/dark.js
packages/bruno-app/src/themes/light.js

In dark mode body form input text color visibility issue fix. Implemented color style of input in both dark and light theme files.

RequestPane body form input text color visibility fix in dark mode

---

docs/development.md

Added snippet to assist in deleting node_modules / package-lock.json in dir structure

Added snippet to development.md

---

packages/bruno-js/src/bru.js

Please also see proposed documentation change in https://github.com/usebruno/bruno-docs/pull/7

RFC: Support process.env in Bru script Re #170

---

.husky/pre-commit
.prettierrc.json
package.json

@helloanoop Please may I ask for a review.

Added prettier precommit hook with husky Re #48

---

packages/bruno-cli/src/commands/run.js
packages/bruno-cli/src/runner/run-single-request.js
packages/bruno-cli/src/utils/bru.js

The _--insecure_ command line option turns off certificate validation on tls connections.

add ability to turn certificate validation off in the cli

---

packages/bruno-cli/src/commands/run.js

#199 bring feature cli overridable env vars to main

#199 bring feature cli overridable env vars to main

---

packages/bruno-cli/src/commands/run.js

#199 improve code to check given env vars correctly

#199 improve code to check given env vars correctly

---

packages/bruno-cli/package.json
packages/bruno-graphql-docs/license.md
packages/bruno-graphql-docs/package.json
packages/bruno-js/license.md
packages/bruno-js/package.json
packages/bruno-lang/license.md
packages/bruno-lang/package.json
packages/bruno-query/license.md
packages/bruno-query/package.json
packages/bruno-schema/license.md
packages/bruno-schema/package.json
packages/bruno-vscode-extension/package.json

All npm published modules should have the license included.

Add license to published npm modules.

---

packages/bruno-app/src/components/RequestPane/GraphQLRequestPane/index.js
packages/bruno-app/src/components/RequestPane/HttpRequestPane/index.js
packages/bruno-app/src/components/ResponsePane/index.js

Allow tabs in tablists to wrap.

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionProperties/index.js

Make sure path string does not overflow the dialog

---

.github/workflows/unit-tests.yml
packages/bruno-electron/src/ipc/collection.js
packages/bruno-electron/src/utils/filesystem.js
packages/bruno-electron/src/utils/filesystem.test.js

Corrects issue when collection names in imports have slashes

---

packages/bruno-app/package.json
packages/bruno-app/src/components/RequestPane/RequestHeaders/index.js
packages/bruno-app/src/components/SingleLineEditor/index.js

For https://github.com/usebruno/bruno/issues/54

Autocomplete

---

packages/bruno-app/src/components/Sidebar/CreateCollection/index.js

Follow up to my last PR:
- Remove Name tooltip
- Update Folder Name tooltip
- Move Folder Name input under location
- Update Folder Name validation
- Now only allow characters for valid system folder names
- Update label htmlFor ids to match the input ids
https://github.com/usebruno/bruno/assets/39559178/334fcf51-6730-43a2-8c06-1e9c95b83c81

feat: Update create collection form

---

packages/bruno-app/src/components/Sidebar/Collections/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/index.js

I have added a feature to sort the collections alphabetically as guided by @helloanoop in #220
@helloanoop , kindly suggest me , should I hide the icon when there is no collections available ?

added feat/-#220

---

packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js

I have added corresponding reducers to be called from actions to manipulate the redux state

fixed issue-#251-&-#265,

---

packages/bruno-app/src/components/Sidebar/Collections/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/index.js

I have implemented all the todos mentioned in #220 by @helloanoop ,Kindly check and do confirm that.

Improved feat-/#220

---

packages/bruno-app/src/components/Modal/StyledWrapper.js

fix: Color in environment delete modal

---

packages/bruno-app/src/utils/importers/insomnia-collection.js

1. fixed importing JSON body with mime-type containing charset i.e. `application/json; charset=utf-8`
2. import `basic` and `bearer` authentication strategies

updated insomnia importer

---

packages/bruno-app/src/components/Environments/EnvironmentSettings/CopyEnvironment/index.js
packages/bruno-app/src/components/Environments/EnvironmentSettings/CreateEnvironment/index.js
packages/bruno-app/src/components/Environments/EnvironmentSettings/RenameEnvironment/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/CloneCollectionItem/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/RenameCollectionItem/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/RenameCollection/index.js
packages/bruno-app/src/components/Sidebar/CreateCollection/index.js
packages/bruno-app/src/components/Sidebar/ImportCollectionLocation/index.js
packages/bruno-app/src/components/Sidebar/NewFolder/index.js
packages/bruno-app/src/components/Sidebar/NewRequest/index.js
packages/bruno-schema/src/collections/index.js
packages/bruno-schema/src/collections/itemSchema.spec.js

typo in the error message

---

packages/bruno-app/src/components/Modal/StyledWrapper.js
packages/bruno-app/src/styles/globals.css

Minor styling fixes
- Increased checkbox and radio sizes, I think they were too small.
- Added background color on the modal.

minor styling fixes

---

package-lock.json
packages/bruno-app/src/components/RequestPane/GraphQLRequestPane/index.js
packages/bruno-app/src/components/RequestPane/GraphQLRequestPane/useGraphqlSchema.js
packages/bruno-app/src/utils/network/index.js
packages/bruno-electron/src/ipc/network/index.js
packages/bruno-electron/src/ipc/network/prepare-gql-introspection-request.js

This fixes the things mentioned here: https://github.com/usebruno/bruno/issues/354#issuecomment-1749094454
> 1. Update to use handlebars
> 2. Interpolate env variables
Additionally, I added one more commit to add the set headers to the introspection request as well as asked here: https://github.com/usebruno/bruno/issues/354#issuecomment-1750191137
One more side note about handlebars: it's only used in two more places now and it should be pretty easy to get rid of this dependency completely.

Improve GQL introspection request

---

package.json
packages/bruno-electron/package.json
scripts/build-electron.js

I created a node js script instead of a bash script.  I'm on Windows and running the script in cygwin or wsl is something painful.  Instead  this node js script will works on any OS.
I also generate the distribution based on the OS.  By default it was MAC.

Building electron script in js to support different OS

---

packages/bruno-app/src/components/ResponsePane/QueryResult/index.js

Add `typeof data === 'string'` check.

fix(#382): TypeError r.replace is not a function

---

packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/index.js

https://github.com/usebruno/bruno/assets/39559178/6f5ca073-d8f4-40d4-aec5-64eefd41b632

fix(#500): Parse query url on request creation

---

packages/bruno-app/src/components/ResponsePane/QueryResult/index.js
packages/bruno-app/src/utils/common/codemirror.js

fixes: #359
Below is a preview after the change:

feat: shows image if url return a image

---

packages/bruno-app/src/utils/network/index.js

fixes https://github.com/usebruno/bruno/issues/497

Show response size even if content-length header isn't present

---

packages/bruno-app/src/components/ResponsePane/Placeholder/index.js

fix(#505): fixed displaying shortcuts based on OS

---

package-lock.json
packages/bruno-electron/package.json
packages/bruno-js/src/runtime/assert-runtime.js

This PR adds and enables "chai-string" plugin, making "startWith"/"endWith" assertions work.

Fix #437 (start/endWith assertions)

---

packages/bruno-js/src/runtime/script-runtime.js

Added support for debug level for console logging in scripts

---

packages/bruno-electron/src/index.js

add minHeight & minWidth to avoid resize window until unseen
https://github.com/usebruno/bruno/assets/26783512/1dc9f78c-f231-43ee-8480-71948cedc980
https://github.com/usebruno/bruno/assets/26783512/a63eb0ab-559f-4084-87f4-bb7334c999e0

fix(ui): add minHeight & minWidth

---

packages/bruno-app/src/components/ResponsePane/Overlay/index.js
packages/bruno-app/src/components/StopWatch/index.js
packages/bruno-electron/src/ipc/network/index.js

fix: switching tabs resets timer

---

packages/bruno-app/src/components/CodeEditor/StyledWrapper.js
packages/bruno-app/src/components/CodeEditor/index.js
packages/bruno-app/src/components/Preferences/Font/StyledWrapper.js
packages/bruno-app/src/components/Preferences/Font/index.js
packages/bruno-app/src/components/Preferences/index.js
packages/bruno-app/src/components/RequestPane/GraphQLVariables/index.js
packages/bruno-app/src/components/RequestPane/RequestBody/index.js
packages/bruno-app/src/components/RequestPane/Script/index.js
packages/bruno-app/src/components/RequestPane/Tests/index.js
packages/bruno-app/src/components/ResponsePane/QueryResult/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/GenerateCodeItem/CodeView/index.js

Added a setting that allows you to change the font of the code

---

packages/bruno-app/src/components/Environments/EnvironmentSettings/EnvironmentList/index.js
packages/bruno-app/src/components/Environments/EnvironmentSettings/ImportEnvironment/index.js
packages/bruno-app/src/components/Environments/EnvironmentSettings/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-app/src/utils/importers/postman-environment.js
packages/bruno-electron/src/ipc/collection.js

-> Fixes https://github.com/usebruno/bruno/issues/193
-> Feature to support Importing Postman environment

Feature: Support Import postman environment - Fixes issue #193

---

packages/bruno-electron/src/ipc/network/index.js

Copy client cert logic from main:run-request-event to main:run-folder-event.
Solves issue #611.
Before:
After:

fix collection client certs

---

scripts/build-electron.js

fixes #629 
Also add output from npm run command, without it only "Building the Electron distribution" is printed and no visible progress.
Before:
After:
After adding command output:

fix electron js build

---

packages/bruno-cli/src/runner/prepare-request.js

This PR fixes an issue when sending requests with SPARQL body via bruno-cli.

Fix: Set body on SPARQL request

---

packages/bruno-electron/src/ipc/network/index.js

Fixes #552: Runs Post response vars and scripts on HTTP error.
This normalises behaviour between:
- Assertions
- Scripts
- Tests
Let me know if you need anything to be changed or if this isn't desired.

Fixes: #552: Runs Post response vars and scripts on HTTP error.

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/index.js

scrolling to the active tab on clicking on the request.  related issue:  #363 
[after.webm](https://github.com/usebruno/bruno/assets/76877078/1a12177c-0a01-466b-a67e-87e55971476f)

feat: scroll to the active tab on click

---

packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js

fixed: #686

---

readme.md
readme_ua.md

This PR adds missing line breaks to the "Stay in touch" section of readme files:

docs(readme): add missing line breaks

---

packages/bruno-app/src/components/ResponsePane/QueryResult/index.js
packages/bruno-app/src/components/ResponsePane/index.js
packages/bruno-app/src/components/RunnerResults/ResponsePane/index.js

Fixes bug #699 introduces in #622 
FYI: @Its-treason 

bug(#699): fixed crashing app on clicking on request result in runner

---

contributing.md
contributing_ru.md
contributing_tr.md
contributing_ua.md
readme.md
readme_ru.md
readme_tr.md
readme_ua.md

Turkish translation for readme.md and contributing.md files.

Turkish translation for readme.md and contributing.md files.

---

contributing.md

There's a small typo in the English contributing.md file. 
Line 36 says "container" should probably be "contain".
https://github.com/usebruno/bruno/blob/f08871d491df711588f2eb79227d12951d20b2f4/contributing.md?plain=1#L36

docs(contributing): Typo Correction

---

packages/bruno-app/src/utils/importers/postman-collection.js

Bug fix to put scripts in comments in postman import

[bugfix] Put scripts in comments in Postman import

---

packages/bruno-app/src/utils/importers/postman-collection.js

Here the fix that each lines should start by //

Postman import : Each line will start by a comment

---

packages/bruno-app/src/utils/importers/insomnia-collection.js

linked to https://github.com/usebruno/bruno/issues/729
Can now import yaml file for insomnia collection

[feature] Can import Insomnia Yaml file

---

contributing.md
contributing_de.md
contributing_ru.md
contributing_tr.md
contributing_ua.md
docs/development.md
docs/development_de.md
docs/development_ru.md
docs/development_ua.md
readme.md
readme_de.md
readme_ru.md
readme_tr.md
readme_ua.md

Add german translation to the project documentation files.
https://github.com/usebruno/bruno/issues/747

Add german translation to documentation files

---

packages/bruno-electron/src/ipc/network/index.js

- add `collectionPath` to `configureRequest` in electron
- use `collectionPath` to resolve relative paths to cert/key if the configured path is not absolute
addresses issue #653

fix cert/key loading in electron for relative path

---

packages/bruno-app/src/components/RequestTabs/index.js

Revert "Make Tabs closable by mouseclick. Closes #778"

---

packages/bruno-app/src/utils/importers/postman-collection.js

Fix the issue when only the first line was imported
see : https://github.com/usebruno/bruno/issues/710

Fix the issue when only the first line was imported

---

readme.md

capitalize git to Git for clarity

---

readme.md

changed Twitter's old name to new 𝕏
old name:
new name:
This fixes https://github.com/usebruno/bruno/issues/830

fix: In README.md in Stay in touch section the Twitter changed to it's new name 𝕏

---

packages/bruno-electron/src/ipc/network/index.js

Related to this comment: https://github.com/usebruno/bruno/pull/705/files#r1370608651

fix graphql schema interpolation

---

readme.md

Many people just want to know how to get it directly from the Github readme
Add simple installation instructions into the README

docs(readme): add simple installation instructions

---

packages/bruno-app/src/components/Sidebar/NewRequest/index.js

This PR adds a fix for https://github.com/usebruno/bruno/issues/855

Address validation issue in Yup schema

---

contributing.md
docs/contributing/contributing_pt_br.md
docs/publishing/publishing_pt_br.md
docs/readme/readme_pt_br.md
publishing.md
readme.md

This PR adds the documentation translation in pt-BR language to the project.
Issue: https://github.com/usebruno/bruno/issues/929

feat: add portuguese brazilian docs translation

---

packages/bruno-app/src/utils/importers/openapi-collection.js

Learned about Bruno today and tried to import PetStore [openapi](https://petstore3.swagger.io/)
Basically, it fails to import because the petstore openapi contains `securitySchemes` at root level but no `security` at root level.
The apis `security` are defined on every path.
From the spec (https://swagger.io/docs/specification/authentication/).
```
Step 2. Applying security
After you have defined the security schemes in the securitySchemes section, you can apply them to the whole API or individual operations by adding the security section on the root level or operation level, respectively. When used on the root level, security applies the specified security schemes globally to all API operations, unless overridden on the operation level. In the following example, the API calls can be …
```

fix(openapi-import): root security should be optional

---

readme.md

Might be a bit brief, but stackoverflow could be a super place for building up a longterm knowledge base about the tweaks and how-tos of Bruno.

Added a hint of the stackoverflow tag to the readme

---

packages/bruno-js/src/bru.js

Fixes #962
Updates one error message

Improve error message when an empty var is set

---

packages/bruno-app/src/components/ResponsePane/index.js

added headers count for response

feat: added response headers count

---

docs/contributing/contributing_fr.md

Improve french translation, correct grammar and syntax errors.

feat(contributing_fr): fix translation errors and syntax within french contributing guidelines

---

readme.md

This PR adds Scoop installation instructions to the README as Bruno was just added to the Scoop package manager. See #310 and https://github.com/ScoopInstaller/Extras/pull/11970 for details. I made a PR for the website too: https://github.com/usebruno/bruno-website/pull/21.

docs: Add Scoop installation info to README

---

contributing.md
docs/contributing/contributing_ro.md
docs/publishing/publishing_ro.md
docs/readme/readme_ro.md
publishing.md
readme.md

Closes #1051 
Added Romanian translation for the readme, contributing & publishing docs.

docs(#1051): Add Romanian translation

---

packages/bruno-electron/src/ipc/network/digestauth-helper.js

This is to fix toUpperCase() error and uri path not being correct.
This is to fix(#1002). It appears that some sites that don't send the algorithm in the `www-authenticate` header so we can just default to MD5 so that it works for more sites. Also Digest Auth requires that the parameter uri needs to be a partial path instead of the full path so that has been fixed. Maybe some sites are more flexible but it's better to follow this process.

Fix(#1002): Digest Error

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-electron/src/ipc/collection.js
packages/bruno-electron/src/utils/filesystem.js

Hello,
This PR introduces a new feature to Bruno - the ability to clone folders directly from the user interface. This functionality aims to enhance user productivity and ease of use, especially for those who work with complex folder structures.
Issue : #1027 
**Clone Button**: Implemented a 'Clone' button in the right-click context menu for folders. This allows users to easily duplicate a folder along with all its contents.
**Error Handling**: Added an error message that is displayed when a user tries to clone a folder into the same location where a folder with the same name already exists. This prevents duplicate naming issues and maintains the integrity of the folder structure.
**Successful Cloning**: Upon successful cloning, the duplicated folder is created with all the original …

feat(#1017) Added ability to clone a folder

---

contributing.md
docs/contributing/contributing_pl.md
docs/publishing/publishing_pl.md
docs/readme/readme_pl.md
publishing.md
readme.md

Closes https://github.com/usebruno/bruno/issues/1113
Polish translation for the readme, contributing & publishing docs.

docs(#1113): add polish translation

---

packages/bruno-cli/src/runner/run-single-request.js
packages/bruno-electron/src/ipc/network/index.js

Since axios is used for requests, it makes sense to match the protocol parsing with their code at
https://github.com/axios/axios/blob/main/lib/helpers/parseProtocol.js
Closes: #1152
* not applicable

refactor: protocol regex matches axios

---

docs/readme/readme_pl.md

Closes https://github.com/usebruno/bruno/issues/1134
Image paths corrected - now should be fine

fix(#1134): images paths in polish readme

---

docs/readme/readme_de.md

Just discovered that you have a German readme, nice!
Some parts read a bit rough, so here are some small improvements.
(I'm a native German speaker).

docs: improve german readme

---

packages/bruno-app/src/providers/ReduxStore/slices/collections/index.js

fix(#1117): Sort env alphabetically

---

docs/contributing/contributing_fr.md
docs/publishing/publishing_bn.md
docs/publishing/publishing_fr.md
docs/publishing/publishing_pl.md
docs/publishing/publishing_ro.md
docs/readme/readme_fr.md
publishing.md

Updated the French doc as per new sections was added in English.

doc: updated French doc

---

packages/bruno-app/src/components/ResponsePane/ResponseClear/StyledWrapper.js
packages/bruno-app/src/components/ResponsePane/ResponseClear/index.js
packages/bruno-app/src/components/ResponsePane/ResponseSave/index.js
packages/bruno-app/src/components/ResponsePane/index.js

This PR resolves usebruno/bruno#1182. You can now click a button (next to the download response button) to clear it.

You can now clear a response.

---

docs/readme/readme_it.md

Fixed a typo into the Italian doc 

doc: fixed typo on italian documentation

---

docs/readme/readme_fr.md

Hi, I've just fix a small typo mistake in fr readme ;)

fix typo in readme fr

---

packages/bruno-app/src/components/SingleLineEditor/index.js

Fix issue crash app when set environment variable
Fixes https://github.com/usebruno/bruno/issues/914
Contribution Checklist:
https://github.com/usebruno/bruno/assets/140475149/501f75dd-6eed-418c-a2be-53e7e64aa9b8
https://github.com/usebruno/bruno/assets/140475149/c9a25a73-4dec-4e78-b1ef-d378ef55be3d

fix(#914): Issue crash app when update environment variable

---

contributing.md
docs/contributing/contributing_cn.md
docs/readme/readme_cn.md
readme.md

This PR adds the documentation translation in Simplified Chinese(cn) language to the project.

docs: add Simplified Chinese language docs translation

---

docs/contributing/contributing_tr.md
docs/publishing/publishing_bn.md
docs/publishing/publishing_fr.md
docs/publishing/publishing_pl.md
docs/publishing/publishing_pt_br.md
docs/publishing/publishing_ro.md
docs/publishing/publishing_tr.md
docs/readme/readme_tr.md

Turkish docs updated.
Added other language links to 'publishing_pt_br.md'

Turkish docs updated.

---

docs/contributing/contributing_tr.md
docs/readme/readme_tr.md

- [Wrong translation fixed.](https://github.com/DogukanUrker/bruno/commit/70328c1dba2914ac5be1ed4e7d79c2f5bd8588dd)
- [Wrong URL syntax fixed.](https://github.com/DogukanUrker/bruno/commit/bcb91bf051b62605e9394998025adfb66c530f53)

Wrong URL syntax and translation fixed for Turkish docs.

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/GenerateCodeItem/CodeView/index.js
packages/bruno-app/src/utils/collections/index.js

Included the collection headers in the code generated. Fix https://github.com/usebruno/bruno/issues/1208

fix #1208: add collection headers to code generated

---

packages/bruno-app/src/components/CollectionSettings/ProxySettings/index.js
packages/bruno-app/src/components/Preferences/ProxySettings/index.js

Closes #1280 
1. Used uppercase HTTP, HTTPS, SOCKS4 & SOCKS5 in the Preferences > Proxy > Protocol
2. Used uppercase HTTP, HTTPS, SOCKS4 & SOCKS5 in the Collection> Settings > Proxy > Protocol

fixed misspelling (global, collection)

---

contributing.md
docs/contributing/contributing_zhtw.md
docs/publishing/publishing_zhtw.md
docs/readme/readme_zhtw.md
publishing.md
readme.md

Add Traditional Chinese language documents

docs: add Traditional Chinese language docs

---

packages/bruno-app/src/components/CollectionSettings/ProxySettings/index.js
packages/bruno-app/src/components/Preferences/ProxySettings/index.js

Fixes #1417 
Before:
https://github.com/usebruno/bruno/assets/1073299/4a39920b-7867-4c36-a11c-b93b91a4072f
After:
https://github.com/usebruno/bruno/assets/1073299/431ec18d-c33a-40a2-b355-1ebf9f7ec083

Fixed selecting SOCKS4 proxy option

---

readme.md

Closes https://github.com/usebruno/bruno/issues/1406 .

feat(#1406): Add flatpak to installation package managers in readme

---

packages/bruno-app/src/components/ResponsePane/QueryResult/QueryResultFilter/index.js

Add placeholer for response filter.
Linked issue: https://github.com/usebruno/bruno/issues/1294

feat: add response filter placeholder

---

packages/bruno-cli/src/runner/run-single-request.js

This MR adds the filename to the request results. This makes it easier to know which tests fail/pass when reading or parsing the report file.

Include the filename of a bruno request in the results.

---

packages/bruno-electron/src/app/menu-template.js
packages/bruno-electron/src/index.js
packages/bruno-electron/src/ipc/collection.js

Recent documents menu

---

packages/bruno-app/src/components/FilePickerEditor/index.js

Resolves #1563. Related to #89.

fix(#1563): Fixed relative paths for file params in Windows

---

readme.md

Hi, this fixes a broken CI badge.
fix #1745 
Before
After 

docs(readme.md): fix broken CI badge

---

docs/readme/readme_es.md

Updated the spanish language readme with new translations from the updated content in the main readme file, as well as some minor fixes on typos.

Update readme_es with new content and typo fixes

---

packages/bruno-app/src/components/RequestPane/QueryEditor/index.js
packages/bruno-app/src/components/ResponsePane/QueryResult/QueryResultFilter/index.js
packages/bruno-app/src/components/ResponsePane/QueryResult/StyledWrapper.js
packages/bruno-app/src/components/ResponsePane/QueryResult/index.js

[JSON_filter_button_with_exapandable_input_bar.webm](https://github.com/usebruno/bruno/assets/25679466/8ec6098d-b100-4df1-ab2e-71069fe9f386)

feat(#BRU-26):  json filter button with expandable input bar

---

readme.md

A simple readme markdown change to inform users that Bruno can be installed with winget

Updates readme with winget install command

---

contributing.md

Make Capitalisation of Bruno consistent with README.md and also make Pull Request plural to fit better gramatically.

contributing.md Capitalisation corrections

---

packages/bruno-cli/readme.md

fix: broken link in readme

---

packages/bruno-app/src/components/Modal/index.js
packages/bruno-app/src/components/Notifications/StyleWrapper.js
packages/bruno-app/src/components/Notifications/index.js
packages/bruno-app/src/components/Sidebar/index.js
packages/bruno-app/src/globalStyles.js
packages/bruno-app/src/providers/ReduxStore/slices/app.js
packages/bruno-app/src/themes/dark.js
packages/bruno-app/src/themes/light.js
packages/bruno-app/src/utils/common/index.js
packages/bruno-app/src/utils/common/notifications.js
packages/bruno-app/src/utils/common/platform.js
packages/bruno-electron/.env.sample
packages/bruno-electron/src/index.js
packages/bruno-electron/src/ipc/notifications.js

[notifications_uii.webm](https://github.com/usebruno/bruno/assets/25679466/de5cabbb-5b60-4536-a9d8-fd2baeb12ac7)

feat(#BRU-31): notifications feature draft

---

packages/bruno-cli/readme.md

Point the bruno-cli readme changelog link to the bruno release page as suggested in the readme file itself
Fixes #1769

Update bruno-cli readme changelog link Fixes #1769

---

docs/readme/readme_pt_br.md

Just updating the pt-br readme.

docs: update pt-br readme

---

docs/readme/readme_de.md

Updated the german readme files with missing things like installation instructions, sponsors, etc.

Update the german readme file

---

packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js

https://github.com/usebruno/bruno/assets/84461672/8a0936dc-cd4f-4f49-a024-ccbcc4f88cc5

feat(#1624): Implement opening cloned request automatically

---

packages/bruno-app/src/components/Sidebar/GoldenEdition/index.js

chore: fix typo

---

docs/contributing/contributing_fr.md
docs/publishing/publishing_fr.md
docs/readme/readme_cn.md
docs/readme/readme_es.md
docs/readme/readme_fr.md
docs/readme/readme_kr.md
docs/readme/readme_pl.md
docs/readme/readme_pt_br.md
docs/readme/readme_tr.md
docs/readme/readme_zhtw.md
packages/bruno-app/src/components/CollectionSettings/Auth/OAuth2/GrantTypeSelector/index.js
packages/bruno-app/src/components/CollectionSettings/ClientCertSettings/index.js
packages/bruno-app/src/components/Environments/EnvironmentSelector/StyledWrapper.js
packages/bruno-app/src/components/Environments/EnvironmentSelector/index.js
packages/bruno-app/src/components/RequestPane/Auth/OAuth2/GrantTypeSelector/index.js
packages/bruno-app/src/components/RunnerResults/index.jsx
packages/bruno-app/src/components/Sidebar/GoldenEdition/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/index.js
packages/bruno-electron/src/ipc/network/index.js
readme.md

- **chore: fix typos in code**
- **chore: GitHub is a trademark**
- **chore: fix documentation in French**
I'm a native French speaker, I noticed some errors in the French documentation.
I started marking changes, then I noticed a few errors in code and in the usage of GitHub trademark.
So I'm opening a PR

fix typos and french documentation

---

.github/ISSUE_TEMPLATE/BugReport.yaml
.github/ISSUE_TEMPLATE/FeatureRequest.yaml
.github/ISSUE_TEMPLATE/config.yaml

fixes #1422 
This is a PR for creating custom `yaml` issue templates. The templates added are - `Bug Report`, `Feature Request` along with the link of the discussions and discord server.

created yaml issue templates

---

packages/bruno-electron/src/ipc/network/index.js

fix(#1145): fix res.responseTime in runner

---

.github/ISSUE_TEMPLATE/BugReport.yaml
.github/ISSUE_TEMPLATE/FeatureRequest.yaml
.github/ISSUE_TEMPLATE/config.yaml

Resolve the typos in the configuration and issue templates.
Fixes #2026 

fix: resolve typos in issue templates and config

---

packages/bruno-electron/src/app/watcher.js

Revert "fix: Folders are not ignored"

---

docs/readme/readme_kr.md

modified CI badge URL and image links
This is the Korean version README modified PR.
readme_kr had two problems.
1. CI Badge Image Broken
2. Broken description image
It was a simple issue that only required editing the link.

Update README KR

---

packages/bruno-app/src/components/Environments/EnvironmentSettings/ManageSecrets/index.js

Just a quick fix to the docs link
resolves #2066 #2055

fix: docs link

---

packages/bruno-app/src/utils/codegenerator/har.js

Addressing #1732, #1750
Error Message: **should match format \"uri\""**
so making sure to convert request url to valid URI format on code generate

fix: converting request url to valid URI on code generate

---

packages/bruno-app/src/components/RequestPane/GraphQLRequestPane/index.js
packages/bruno-app/src/components/RequestPane/GraphQLSchemaActions/index.js
packages/bruno-app/src/components/RequestPane/QueryUrl/index.js

fix: handle null values

---

packages/bruno-app/src/utils/collections/index.js
packages/bruno-electron/src/ipc/collection.js
packages/bruno-schema/src/collections/index.js

Now added the ability to import and export js and json values. changes made in item schema.

---

docs/readme/readme_fr.md

Minor change in the French version of readme, to include the link to Github Sponsor.
Related to issue #2343

fix: minor French translation update

---

package-lock.json
packages/bruno-app/src/components/Sidebar/ImportCollection/index.js
packages/bruno-app/src/components/Sidebar/TitleBar/index.js
packages/bruno-app/src/components/Welcome/index.js
packages/bruno-app/src/utils/importers/bruno-collection.js
packages/bruno-app/src/utils/importers/insomnia-collection.js
packages/bruno-app/src/utils/importers/openapi-collection.js
packages/bruno-electron/src/ipc/collection.js

Fixed object spread operations for collection import

fix: collection import

---

packages/bruno-lang/v2/src/jsonToBru.js

bugfix(#2401)

---

packages/bruno-cli/src/commands/run.js

Revert "fix(#2123): Move output to stderr"

---

packages/bruno-app/src/components/Sidebar/TitleBar/index.js
packages/bruno-app/src/components/Welcome/index.js

refactor: Handle errors when importing collections

---

packages/bruno-app/src/pages/index.js

fix: changed title from 'bruno' to 'Bruno'

---

packages/bruno-app/src/components/RequestPane/Assertions/AssertionOperator/index.js
packages/bruno-app/src/components/RequestPane/Assertions/AssertionRow/index.js
packages/bruno-js/src/runtime/assert-runtime.js

With this PR I've added "IsArray" to the list of selectable Asserts, to give one more option to ease user's testing
Fixes #2414

Added IsArray on Assert

---

packages/bruno-app/src/components/Sidebar/ImportCollectionLocation/index.js
packages/bruno-app/src/utils/importers/postman-collection.js
packages/bruno-app/src/utils/importers/translators/index.spec.js
packages/bruno-app/src/utils/importers/translators/postman_translation.js

Fix postman translation : support postman. ; additional translations

---

packages/bruno-cli/src/runner/prepare-request.js
packages/bruno-electron/src/ipc/network/prepare-request.js

extension of pr #1819 
~ added validation for the decomment step
and fixes failing tests

add decomment step in a try catch block

---

packages/bruno-app/src/components/CollectionSettings/Info/index.js

fix(#1912) Refactor countRequests function to use getTotalRequestCountInCollection in CollectionSettings/Info/index.js

---

contributing.md
docs/contributing/contributing_de.md
docs/readme/readme_pt_br.md
packages/bruno-cli/src/index.js
readme.md

Unlike French, English does not take a non breakable space nor any space before exclamation marks not question marks.
fix #2492

Fixed English grammar/typo

---

packages/bruno-app/src/components/FolderSettings/Vars/StyledWrapper.js
packages/bruno-app/src/components/FolderSettings/Vars/VarsTable/StyledWrapper.js
packages/bruno-app/src/components/FolderSettings/Vars/VarsTable/index.js
packages/bruno-app/src/components/FolderSettings/Vars/index.js
packages/bruno-app/src/components/FolderSettings/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/index.js
packages/bruno-electron/src/bru/index.js
packages/bruno-electron/src/ipc/network/index.js
packages/bruno-electron/src/ipc/network/prepare-request.js
packages/bruno-electron/tests/network/prepare-request.spec.js

extension of #2529 
folder level pre and post variables

feat: folder level variables

---

packages/bruno-app/src/utils/collections/index.js
packages/bruno-cli/src/utils/bru.js
packages/bruno-electron/src/bru/index.js
packages/bruno-electron/src/ipc/collection.js
packages/bruno-schema/src/collections/index.js

include folder.bru and collection.bru data in the exported bruno collection json

add collection and folder data to exported bruno collection json

---

packages/bruno-cli/readme.md

Chore: fixed typos in bruno-cli readme.md

---

packages/bruno-electron/src/ipc/collection.js

@helloanoop @lohit-1 I pushed the change that remove underscores on variables I introduces for PR #2596 as suggested by @Its-treason 
- [X ] **The pull request only addresses one issue or adds one feature.**
- [ X] **The pull request does not introduce any breaking changes**
- [X ] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**

Removed Underscores on variables

---

packages/bruno-app/src/components/FilePickerEditor/index.js
packages/bruno-app/src/components/RequestPane/MultipartFormParams/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/index.js

Fix Multipart request file input init value and clear value

---

docs/readme/readme_pt_br.md

Just noticed one of the sponsors were missing on the portuguese version.

Update missing sponsor in readme_pt_br.md

---

.github/workflows/tests.yml
package-lock.json
packages/bruno-app/src/components/CodeEditor/StyledWrapper.js
packages/bruno-app/src/components/CodeEditor/index.js
packages/bruno-app/src/components/Documentation/StyledWrapper.js
packages/bruno-app/src/components/Documentation/index.js
packages/bruno-app/src/components/MarkDown/StyledWrapper.js
packages/bruno-app/src/components/RequestPane/HttpRequestPane/index.js
packages/bruno-app/src/components/RequestPane/QueryEditor/StyledWrapper.js
packages/bruno-app/src/components/RequestPane/RequestBody/StyledWrapper.js
packages/bruno-app/src/components/RequestPane/Script/index.js
packages/bruno-app/src/components/RequestPane/Vars/index.js
packages/bruno-app/src/components/RequestTabPanel/index.js
packages/bruno-app/src/components/RequestTabs/StyledWrapper.js
packages/bruno-app/src/styles/globals.css

Fixes: #2605
https://github.com/user-attachments/assets/86c93c89-cf94-4854-818c-9407b4c53d44

fix(#2605): fix editor view height

---

docs/contributing/contributing_fr.md

I just add to the contributing_fr.md the step `npm run build:bruno-common`
#2499

Fix: contributing_fr.md

---

packages/bruno-app/src/utils/common/index.js
packages/bruno-electron/package.json
packages/bruno-electron/src/ipc/network/index.js

Revert "Fix/bigint in response"

---

.github/workflows/tests.yml

I missed this job in my previous PR adding cache.

chore: add cache to cli-test job in tests workflow

---

packages/bruno-app/src/utils/curl/curl-to-json.js

bugfix(#2379) - Removed the logic that strips the backslash

---

packages/bruno-js/src/sandbox/quickjs/shims/bru.js
packages/bruno-js/src/sandbox/quickjs/utils/index.js

fix: getRequestVar vm shim, boolean values in vm

---

package-lock.json
package.json
packages/bruno-common/package.json
packages/bruno-graphql-docs/package.json
packages/bruno-query/package.json

Updates to the latest patch on the same version branch to avoid possible breaking changes
fixes #2710

Bugfix/ update rollup to fix build warnings about unrecognized option

---

packages/bruno-tests/collection/echo/echo xml parsed(self closing tags).bru

test: added test for self closing tags in xml-json parser

---

packages/bruno-app/src/utils/exporters/postman-collection.js

This includes GraphQL queries when exporting a collection to Postman. 
Related issue: #2385

Feat: Add GraphQL in export to Postman collection

---

packages/bruno-app/src/components/CodeEditor/StyledWrapper.js
packages/bruno-app/src/components/CodeEditor/index.js

This adds a small box that displays the count of search results 
Closes #1497

feature: add search results count to CodeMirror

---

docs/readme/readme_de.md

I aligned the form of address in the whole document. The according issue is #2175.

Aligned the correct form of address to make it easier to read

---

packages/bruno-app/src/components/CollectionSettings/ProxySettings/index.js
packages/bruno-app/src/components/Preferences/ProxySettings/StyledWrapper.js
packages/bruno-app/src/components/Preferences/ProxySettings/index.js
packages/bruno-app/src/providers/App/useIpcEvents.js
packages/bruno-app/src/providers/ReduxStore/slices/app.js
packages/bruno-cli/src/utils/axios-instance.js
packages/bruno-electron/src/ipc/network/axios-instance.js
packages/bruno-electron/src/ipc/network/index.js
packages/bruno-electron/src/ipc/preferences.js
packages/bruno-electron/src/store/preferences.js

fix: option to toggle on/off system proxy env variables

---

packages/bruno-electron/src/ipc/network/index.js

Supposed to address #2950, however, there still are some folders for which my changes do not store the cookie. Need some more analysis.
fixes #2682 
fixes #2950

feat: Store cookies received in Runner execution

---

package-lock.json
packages/bruno-app/src/components/CollectionSettings/Vars/StyledWrapper.js
packages/bruno-app/src/components/CollectionSettings/Vars/VarsTable/StyledWrapper.js
packages/bruno-app/src/components/CollectionSettings/Vars/VarsTable/index.js
packages/bruno-app/src/components/CollectionSettings/Vars/index.js
packages/bruno-app/src/components/CollectionSettings/index.js
packages/bruno-app/src/components/FolderSettings/Headers/index.js
packages/bruno-app/src/components/FolderSettings/Vars/VarsTable/index.js
packages/bruno-app/src/components/RequestPane/Assertions/AssertionRow/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/index.js
packages/bruno-app/src/utils/collections/index.js
packages/bruno-cli/src/runner/run-single-request.js
packages/bruno-electron/src/ipc/network/index.js
packages/bruno-electron/src/ipc/network/interpolate-vars.js
packages/bruno-electron/src/ipc/network/prepare-request.js
packages/bruno-js/src/bru.js
packages/bruno-js/src/interpolate-string.js
packages/bruno-js/src/runtime/assert-runtime.js
packages/bruno-js/src/runtime/script-runtime.js
packages/bruno-js/src/runtime/test-runtime.js
packages/bruno-js/src/runtime/vars-runtime.js
packages/bruno-js/src/sandbox/quickjs/shims/bru.js
packages/bruno-tests/collection/collection.bru
packages/bruno-tests/collection/scripting/js/data types - request vars.bru
packages/bruno-tests/collection/string interpolation/folder.bru
packages/bruno-tests/collection/string interpolation/pre-vars.bru

Collection Variables Support (#2963)

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CloneCollection/index.js
packages/bruno-app/src/components/Sidebar/CreateCollection/index.js

This PR adds the logging of the exception when a collection fails to be created or cloned so a user is aware why it failed and doesn't just receive a generic error message.
close #3040 

Added a more descriptive error message on create and clone collection.

---

packages/bruno-app/src/components/CodeEditor/index.js

Now the special characters in the search value are escaped before constructing the regexp.

---

packages/bruno-app/src/utils/importers/insomnia-collection.js

**Fixes**: https://github.com/usebruno/bruno/issues/3106

Fix application/xml import issue for insomnia

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/index.js

Conditionally render generate-code button only if the request.type is 'http-request' or 'graphql-request'

---

packages/bruno-app/src/components/Preferences/Keybindings/StyledWrapper.js
packages/bruno-app/src/components/Preferences/Keybindings/index.js
packages/bruno-app/src/components/Preferences/index.js
packages/bruno-app/src/providers/Hotkeys/index.js
packages/bruno-app/src/providers/Hotkeys/keyMappings.js
packages/bruno-app/src/utils/common/platform.js

Added Keybindings tab.

---

packages/bruno-app/src/components/CodeEditor/index.js
packages/bruno-js/src/bru.js
packages/bruno-js/src/sandbox/quickjs/shims/bru.js

#3229 
~ added `bru.deleteAllVars()` fn
~ added missing `bru.hasVar()` and `bru.hasEnvVar` fns to safe-mode

feat: bru fns update

---

packages/bruno-cli/src/runner/prepare-request.js
packages/bruno-electron/src/ipc/network/prepare-request.js

Correcting the WSSE logic from this PR: https://github.com/usebruno/bruno/pull/2136
- [ X] **The pull request only addresses one issue or adds one feature.**
- [ X] **The pull request does not introduce any breaking changes**
- [ X] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**

INTERNAL | correcting WSSE logic

---

packages/bruno-app/src/components/Preferences/Keybindings/StyledWrapper.js

refactor: Update color variable in Keybindings component

---

packages/bruno-app/src/providers/App/useIpcEvents.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-electron/src/ipc/collection.js
packages/bruno-electron/src/store/ui-state-snapshot.js

fix: select no-env issue

---

packages/bruno-js/src/sandbox/quickjs/shims/bruno-response.js

res.setBody shim for safe-mode
fixes: #3287

fix(#3287): res.setBody safe mode

---

packages/bruno-app/src/components/Environments/EnvironmentSettings/EnvironmentList/EnvironmentDetails/EnvironmentVariables/StyledWrapper.js
packages/bruno-app/src/components/Environments/EnvironmentSettings/EnvironmentList/EnvironmentDetails/EnvironmentVariables/index.js

Refactor environment variable styling and error handling

---

package-lock.json
package.json
packages/bruno-app/package.json
packages/bruno-app/src/components/RequestPane/RequestBody/RequestBodyMode/index.js
packages/bruno-app/src/components/Sidebar/index.js
packages/bruno-electron/package.json
packages/bruno-js/package.json

~ removed `@rollup/plugin-json`, `react-github-btn`, `terser`, `uglify-js`, `lossless-json`, `json-bigint`
~ upgraded `posthog-node` lib
todo: remove `json-bigint` from bruno-cli

chore: removed unused libraries

---

packages/bruno-electron/src/ipc/collection.js

fix: can't create collection on empty directory

---

packages/bruno-app/src/components/CodeEditor/StyledWrapper.js
packages/bruno-app/src/components/RequestPane/QueryEditor/StyledWrapper.js
packages/bruno-app/src/globalStyles.js
packages/bruno-app/src/styles/globals.css

fix: codemirror styling fixes, post library upgrade

---

packages/bruno-app/src/providers/ReduxStore/slices/global-environments.js

Fixes #3442
[BRU-441](https://usebruno.atlassian.net/browse/BRU-441)

bugfix / remove error logging for missing global environment

---

packages/bruno-app/src/providers/ReduxStore/slices/notifications.js
packages/bruno-app/src/utils/common/index.js
packages/bruno-app/src/utils/common/index.spec.js

fix: humanize-date fixes: #3556

---

packages/bruno-app/src/utils/curl/curl-to-json.js
packages/bruno-app/src/utils/curl/index.js

Fix/xml body not getting added during curl import. 

---

packages/bruno-app/src/utils/importers/postman-collection.js

Fixes https://github.com/usebruno/bruno/issues/2013
[BRU-464](https://usebruno.atlassian.net/browse/BRU-464)

feat: add support for importing collection-level variables from PM collections

---

packages/bruno-cli/src/utils/common.js

fixes: #3756 
This PR implements a fix to remove error logging during JSON parsing for `bru-cli`.

fix: remove redundant error logging in JSON parsing

---

package-lock.json
packages/bruno-cli/package.json
packages/bruno-cli/src/utils/common.js

fixes: #3762
~ added the missing `iconv-lite` import for cli
~ removed unused library imports

fix: cli - added the missing iconv-lite import and removed other unused imports

---

packages/bruno-app/src/components/MultiLineEditor/StyledWrapper.js

https://github.com/usebruno/bruno/issues/3643

fix: body formurl value disappearing 

---

packages/bruno-app/src/components/Environments/EnvironmentSettings/EnvironmentList/index.js

If there was only one collection environment and we were trying to rename it. It was not working properly
https://github.com/user-attachments/assets/22d5580c-c76d-4fa1-843d-5a47f02c7292

fix: renaming first collection env

---

packages/bruno-app/rsbuild.config.mjs

This is to fix the react player issue when using rsbuild.

feat: add rspack dynamic import configuration to rsbuild

---

packages/bruno-cli/src/runner/run-single-request.js
packages/bruno-electron/src/ipc/network/index.js

Fix to make ntlm auth work, it is a complement of prior PR #3329, 

ntlm auth complement

---

.github/workflows/tests.yml

refactor: update GitHub Actions workflow to add permissions for checks and pull requests for the `cli-tests` job

---

packages/bruno-app/src/components/RequestPane/Auth/OAuth2/AuthorizationCode/index.js
packages/bruno-app/src/components/RequestPane/Auth/OAuth2/ClientCredentials/index.js
packages/bruno-app/src/components/RequestPane/Auth/OAuth2/PasswordCredentials/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-app/src/utils/importers/postman-collection.js
packages/bruno-electron/src/ipc/collection.js
packages/bruno-electron/src/utils/request.js

~ add support for postman oauth2 request imports
~ include collection client certs and proxy config while fetching the `access_token`

oauth2 improvements

---

packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-app/src/utils/importers/postman-collection.js
packages/bruno-electron/src/utils/filesystem.js

refactor: update browseFiles action to remove default properties and improve file dialog handling

---

packages/bruno-app/src/utils/importers/translators/postman_translation.js

Added translation for `skipRequest` and `stopExecution`

add: translation for skipRequest and stopExecution

---

packages/bruno-electron/src/ipc/network/interpolate-vars.js

Fix: Prevent interpolation of buffer values in JSON requests

---

packages/bruno-app/src/providers/ReduxStore/slices/collections/index.js

should be able to save the request after reverting the changes

---

packages/bruno-app/src/components/RequestTabPanel/RequestNotLoaded/index.js

Improved styling of the request page which was failed on load.
https://github.com/user-attachments/assets/8140c0d2-29b6-4d1f-8c7f-0361a6633f5d

Styling improvements in failed-load-request summary

---

package-lock.json
packages/bruno-app/package.json
packages/bruno-app/src/components/Notifications/index.js
packages/bruno-app/src/components/Sidebar/index.js
packages/bruno-app/src/providers/App/index.js
packages/bruno-app/src/providers/App/useTelemetry.js
packages/bruno-app/src/providers/ReduxStore/slices/notifications.js
packages/bruno-app/src/providers/ReduxStore/slices/notifications.spec.js

Support for controlling notification visibility based on semver

feat: notification visibility rules based on semver

---

packages/bruno-app/src/components/CollectionSettings/Overview/Info/index.js
packages/bruno-app/src/components/RequestTabPanel/RequestNotLoaded/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/index.js
packages/bruno-electron/src/bru/workers/scripts/bru-to-json.js
packages/bruno-electron/src/bru/workers/scripts/json-to-bru.js
packages/bruno-electron/src/ipc/collection.js
packages/bruno-electron/src/workers/index.js

~ reuse worker threads to reduce the overhead of creating a new worker for every new request
[1000_files.zip](https://github.com/user-attachments/files/18844487/1000_files.zip)
before:
https://github.com/user-attachments/assets/19c6db1d-b734-4491-978d-a0325b99d82b
after:
https://github.com/user-attachments/assets/a030f1c1-3595-4037-84d0-bb1551334888

reuse worker threads for bru file parsing

---

.github/ISSUE_TEMPLATE/FeatureRequest.yaml

Update Feature Request Form to capture better detail

---

.github/ISSUE_TEMPLATE/BugReport.yaml

[Demo](https://github.com/usebruno/bruno/blob/7517987a24effbb4f4d9be05d3110267ea8d04f2/.github/ISSUE_TEMPLATE/BugReport.yaml)

chore: update BugReport template to include version and OS information

---

scripts/build-electron.js

updates electron builder script to:
- update web files path
- remove "next" folder string replacement
- update replacement form absolute to relative path
fixes #4042

fix windows build (#4042)

---

readme.md

Update link to roadmap in readme.md

---

package-lock.json
packages/bruno-app/package.json
packages/bruno-app/src/components/Accordion/index.js
packages/bruno-app/src/components/Accordion/styledWrapper.js
packages/bruno-app/src/components/Cookies/ModifyCookieModal/StyledWrapper.js
packages/bruno-app/src/components/Cookies/ModifyCookieModal/index.js
packages/bruno-app/src/components/Cookies/StyledWrapper.js
packages/bruno-app/src/components/Cookies/index.js
packages/bruno-app/src/components/ToggleSwitch/StyledWrapper.js
packages/bruno-app/src/components/ToggleSwitch/index.js
packages/bruno-app/src/providers/ReduxStore/slices/app.js
packages/bruno-electron/src/ipc/collection.js
packages/bruno-electron/src/utils/cookies.js

Add feature to create, view, edit, delete cookies
Also, search by domain and clear-all cookies for a domain.
Closes #1094
https://github.com/user-attachments/assets/72c62978-8abf-4bb3-b04e-72a9c5287816

Added UI to manage cookies 

---

packages/bruno-cli/src/commands/run.js

fixes: #4010 
add --delay _delayInMs_ option for bruno cli 
https://github.com/user-attachments/assets/dc9130bb-46f2-41b6-af3c-2433a86351dc

feat: add runner delay for bruno cli

---

packages/bruno-app/src/components/PathDisplay/StyledWrapper.js
packages/bruno-app/src/components/PathDisplay/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CloneCollection/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/CloneCollectionItem/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/RenameCollectionItem/index.js
packages/bruno-app/src/components/Sidebar/CreateCollection/index.js
packages/bruno-app/src/components/Sidebar/NewFolder/index.js
packages/bruno-app/src/components/Sidebar/NewRequest/index.js

Added help tips for file and folder custom name feature.

feat: added helptips for file and folder custom names

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/CloneCollectionItem/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/CollectionItemInfo/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/RenameCollectionItem/index.js
packages/bruno-app/src/components/Sidebar/NewFolder/index.js
packages/bruno-app/src/components/Sidebar/NewRequest/index.js

Improved Collection Item Info UX

feat: improved item info ux

---

packages/bruno-app/src/styles/globals.css

Updated font-family for improved typography consistency

style: update font-family for improved typography consistency

---

packages/bruno-app/src/components/Preferences/index.js
packages/bruno-electron/src/app/about-bruno.js
packages/bruno-electron/src/app/menu-template.js
packages/bruno-electron/src/index.js
scripts/build-electron.js
scripts/build-electron.sh

* Resolved an issue preventing the About menu from loading.
* Corrected padding inconsistencies in Preferences.
* Fixed an issue that prevented the Inter font from loading properly.

fix: font not loading issue, about menu item not loading issue and preferences modal styling issue

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/index.js

fix: request run crash

---

packages/bruno-app/src/utils/codemirror/javascript-lint.js

Fixed lint error in pre and post editor. Addressing issure https://github.com/usebruno/bruno/issues/4284

fix: codemirror lint errors

---

packages/bruno-app/src/components/ResponsePane/Timeline/TimelineItem/Common/Time/index.js
packages/bruno-electron/src/ipc/collection.js
packages/bruno-electron/src/ipc/network/index.js
packages/bruno-electron/src/utils/oauth2.js

fix: proxy and certs config not being used for oauth2 calls

---

packages/bruno-app/src/components/CodeEditor/index.js
packages/bruno-js/src/bruno-response.js

fixes #3889 
https://github.com/user-attachments/assets/f795d43f-b0f5-4678-9940-1d85ce5b013f
https://github.com/user-attachments/assets/a38a9cf7-2553-43ee-9201-a3cfa48db8ba

Fix: `res.setBody` fails for Object in Developer-mode

---

contributing.md

Added new changes to `contribute.md` file with latest setup instructions.

Update contributing.md with contribution guidelines and setup instructions

---

packages/bruno-app/src/components/Icons/Dot/index.js

Invalid DOM property `stroke-width`. Did you mean `strokeWidth`? Error Component Stack
Removes console error message  fixes #4371

fix console error Invalid DOM property stroke-width (fixes #4371)

---

packages/bruno-cli/readme.md

- Capitalize title
- Added bru-cli docs
- Added command line options

updated bruno cli readme file

---

packages/bruno-app/src/components/Preferences/General/index.js

This PR implements the case-sensitive renaming of the terms "custom" and "default" to "Custom" and "Default" throughout the product to ensure consistency and alignment with the naming conventions.

Rename "custom" and "default" to "Custom" and "Default" (Case Sensitive) for Consistency

---

.github/ISSUE_TEMPLATE/BugReport.yaml

Added a checkbox for reporting regression bugs in issue template

Updating issue template for github to track regression bugs

---

packages/bruno-app/src/components/CodeEditor/StyledWrapper.js

**Preview of the fix**
*Dark mode*
*Light mode*
This fixes #4354

Fix: Highlight matching brackets pair

---

packages/bruno-app/src/components/RequestPane/Auth/OAuth2/Oauth2ActionButtons/index.js

fix: Oauth2 toast typo

---

packages/bruno-electron/src/ipc/network/axios-instance.js

fix: user agent header

---

.github/workflows/tests.yml
packages/bruno-app/src/utils/importers/postman-collection.js
packages/bruno-converters/src/postman/postman-to-bruno.js
packages/bruno-converters/tests/postman/postman-to-bruno.spec.js

~ validation fixes for `postmanToBruno` function
~ refactored the `postmanToBruno` function to return the collection object directly instead of wrapping it within an object

fixes for postman-to-bruno converter package

---

.github/workflows/tests.yml

add: bruno converters package in workfow file

---

packages/bruno-converters/readme.md

Added an example to the Bruno converter package readme file.

added example to readme file

---

docs/contributing/contributing_de.md

In the text above you said you need at least Node v20

chore: updated required node version in german contributing file

---

packages/bruno-common/src/interpolate/index.spec.ts

- Added test for mock variables interpolation.

feat: add tests for mock variable interpolation in interpolate function

---

packages/bruno-converters/src/insomnia/insomnia-to-bruno.js
packages/bruno-converters/tests/insomnia/insomnia-collection-v5.spec.js

This PR adds Insomnia v5 support for the import functionality. The changes include detecting the new export format and processing it appropriately, while still maintaining backward compatibility exports.
Addressing issue: https://github.com/usebruno/bruno/issues/4410

feat: add insomnia v5 import

---

packages/bruno-app/src/components/Environments/EnvironmentSettings/ImportEnvironment/index.js
packages/bruno-app/src/components/GlobalEnvironments/EnvironmentSettings/ImportEnvironment/index.js
packages/bruno-app/src/utils/importers/postman-environment.js

Fixed Issue where postman import postman environment was failing

fix: add json parsing and error handling for postman environment imports

---

packages/bruno-common/src/runner/reports/html/generate-report.ts
packages/bruno-common/src/runner/types/index.ts

[JIRA Ref](https://usebruno.atlassian.net/browse/BRU-1095)

update T_RunnerResults type to include summary prop

---

contributing.md
docs/contributing/contributing_hi.md
docs/contributing/contributing_ja.md
docs/contributing/contributing_kr.md
docs/contributing/contributing_nl.md
docs/contributing/contributing_sk.md

Added build commands for `converters` and `requests` package

Adding build instructions for new packages

---

contributing.md

Added a specific Node.js version requirement to the `CONTRIBUTING.md` file.

Fix: Specify Node.js version in Contributing Guide

---

package.json

[jira](https://usebruno.atlassian.net/browse/BRU-1097)
~ eslint run gives a javascript out of memory issue
https://stackoverflow.com/a/54456814

fix: eslint - javascript heap out of memory

---

playwright.config.ts

Customize Playwright reporter and retries for dev and CI env

---

e2e-tests/preferences/verify-support-links-in-preferences.spec.js
e2e-tests/test-app-support_element.spec.js

This test verifies that the URLs for the Support elements (e.g., Git, Discord) match the expected URLs for each respective support resource.
Jira Link: https://usebruno.atlassian.net/browse/BRU-1027

Playwright: Support Element Verification

---

packages/bruno-app/src/components/CollectionSettings/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/GenerateCodeItem/index.js
packages/bruno-lang/v2/src/collectionBruToJson.js

[jira](https://usebruno.atlassian.net/browse/BRU-1183)

fix: collection auth default value access fix and validations

---

package-lock.json
packages/bruno-app/babel.config.js
packages/bruno-app/jest.config.js
packages/bruno-app/package.json
packages/bruno-app/src/components/ResponsePane/ResponseSize/ResponseSize.spec.js

Jira: [BRU-1159](https://usebruno.atlassian.net/browse/BRU-1123)
- Changes made
- Invalid inputs (undefined, null, NaN, Infinity, strings, objects)
- Valid size values (0B, <1024B, exactly 1024B, >1024B)
- Decimal number handling
- Tooltip content verification

Tests for responseSize component

---

packages/bruno-converters/src/utils/send-request-transformer.js
packages/bruno-converters/tests/postman/postman-translations/transpiler-tests/transformers/send-request.test.js
packages/bruno-requests/src/network/axios-instance.ts

[jira](https://usebruno.atlassian.net/browse/BRU-699)

add await keyword to the translated bru.sendRequest function calls

---

docs/contributing/contributing_es.md

Improve the Spanish section of  **contributing_es.md** fixing typos, standardizing code blocks, correcting tool names, more info, and updating the Node.js version.

Update Spanish contribution guide for clarity and accuracy

---

packages/bruno-requests/src/network/axios-instance.ts

fix: set default proxy value as `false` for `bru.sendRequest`' axios request config

---

packages/bruno-app/src/components/Environments/EnvironmentSettings/ManageSecrets/index.js

Closes #5033 
This is a content only change.

Manage secrets modal content updated

---

packages/bruno-app/src/components/ResponsePane/QueryResult/index.js

issue: #5206 
[JIRA](https://usebruno.atlassian.net/browse/BRU-1402)

fix: Large response crash bruno

---

packages/bruno-converters/readme.md

1. Changed examples to `Common JS` format.

changed example to cjs syntax

---

packages/bruno-app/src/styles/globals.css

Add z-index with value 20 to CodeMirror hint box
Fixes #5367 

Add z-index to CodeMirror hint box

---

packages/bruno-common/src/interpolate/index.spec.ts
packages/bruno-common/src/interpolate/index.ts
packages/bruno-tests/collection/string interpolation/runtime vars.bru

Update Bruno's Age 🎉

---

package-lock.json
packages/bruno-app/package.json
packages/bruno-app/src/components/RequestPane/QueryUrl/HttpMethodSelector/index.spec.js

Added some jest dom tests to test the HttpMethodSelector component 🧪

Add HttpMethodSelector component tests

---

docs/playwright-testing-guide.md

Added a `playright-testing-guide.md` file describing how to write playright test cases

Add Playwright testing guide for Bruno application

---

package-lock.json
packages/bruno-js/package.json
packages/bruno-js/src/runtime/test-runtime.js
packages/bruno-js/src/sandbox/bundle-libraries.js
packages/bruno-js/src/sandbox/quickjs/index.js
packages/bruno-js/src/sandbox/quickjs/shims/lib/crypto-utils.js
packages/bruno-js/src/sandbox/quickjs/shims/lib/crypto-utils.spec.js
packages/bruno-js/src/sandbox/quickjs/shims/lib/utils.js
packages/bruno-tests/collection/scripting/inbuilt modules/crypto-js/crypto-js-pre-request-script.bru
packages/bruno-tests/collection/scripting/inbuilt modules/crypto-utils/getRandomValues.bru
packages/bruno-tests/collection/scripting/inbuilt modules/crypto-utils/randomBytes.bru
packages/bruno-tests/collection/scripting/inbuilt modules/utils.js

[jira](https://usebruno.atlassian.net/browse/BRU-1409)

fix crypto-js in safe mode

---

packages/bruno-app/src/components/Environments/EnvironmentSelector/index.js

fix: env name overflow

---

eslint.config.js
packages/bruno-app/src/utils/url/index.js
packages/bruno-app/src/utils/url/index.spec.js
packages/bruno-cli/src/runner/interpolate-vars.js
packages/bruno-electron/src/ipc/network/interpolate-vars.js
packages/bruno-electron/tests/network/interpolate-vars.spec.js
packages/bruno-tests/src/echo/index.js
tests/interpolation/collection/bruno.json
tests/interpolation/collection/echo-request-odata.bru
tests/interpolation/collection/echo-request-url.bru
tests/interpolation/init-user-data/collection-security.json
tests/interpolation/init-user-data/preferences.json
tests/interpolation/interpolate-request-url.spec.ts

Fine tuning the PR https://github.com/usebruno/bruno/pull/5048 and added test cases

Support for Odata style path params

---

packages/bruno-electron/src/app/onboarding.js
packages/bruno-electron/src/store/preferences.js

[Jira 1](https://usebruno.atlassian.net/browse/BRU-1886)
[Jira 2](https://usebruno.atlassian.net/browse/BRU-1885)
should use existing savePreferences function with schema validation

fix: update preferences saving method in preferences utility

---

packages/bruno-cli/src/runner/prepare-request.js
packages/bruno-cli/src/runner/run-single-request.js
packages/bruno-cli/tests/runner/prepare-request.spec.js

feat: add support for file body mode in bruno-cli

---

package-lock.json
packages/bruno-app/src/components/Devtools/Console/index.js
packages/bruno-app/src/components/Devtools/Performance/StyledWrapper.js
packages/bruno-app/src/components/Devtools/Performance/index.js
packages/bruno-app/src/providers/App/useIpcEvents.js
packages/bruno-app/src/providers/ReduxStore/index.js
packages/bruno-app/src/providers/ReduxStore/slices/performance.js
packages/bruno-electron/package.json
packages/bruno-electron/src/app/collection-watcher.js
packages/bruno-electron/src/app/system-monitor.js
packages/bruno-electron/src/index.js

This PR add's a new tab in dev tools to show:
cpu usage,
memory usage,
uptime,
pid

add: system monitor

---

tests/interpolation/interpolate-request-url.spec.ts

fix: update interpolate-request-url.spec.ts test flow

---

packages/bruno-app/src/components/RequestPane/WsQueryUrl/StyledWrapper.js
packages/bruno-lang/v2/src/bruToJson.js
packages/bruno-lang/v2/tests/bruToJson.spec.js
tests/request/save/save.spec.ts
tests/utils/page/locators.ts

Adds a conditional check to get value from the file only if they exist, if they don't exist, the default defined in other places will take over as necessary.

fix: keepAlive's fallback adds problem while saving normal requests
