usebruno/bruno

.github/workflows/playwright.yml
.gitignore
package.json
playwright.config.js
tests/home.spec.js
tests/pages/home.page.js

hi @helloanoop 
since this awesome project doesn't have any e2e tests integrated. I propose to add one, using Playwright. 🙇🏻

feat: add e2e test

---

packages/bruno-app/src/providers/Theme/index.js

Set the default theme to the user's preferred browser theme.
[Browser support](https://caniuse.com/prefers-color-scheme) for `prefers-color-scheme`.
**Note**: There is a [known issue](https://bugs.chromium.org/p/chromium/issues/detail?id=998903) with Chrome in Linux which causes the `prefers-color-scheme` to always detect light mode.

Set default theme to the user's browser theme

---

packages/bruno-js/package.json
packages/bruno-js/src/utils.js
packages/bruno-js/tests/utils.spec.js

Enabled compiling and caching of expressions.
Currently expression evaluation is dynamic and a new function need to be created every time an expression is evaluated.
By identifying the variables used in an expression, we are able to create a function and cache it.
```js
res.data.pets.map(pet => pet.name.toUpperCase())
```
In the above expression there are two variables that are identified (`res` and `pet`). These are picked up from the context when the function is called.
```js
function(context) {
const { res, pet } = context;
return res.data.pets.map(pet => pet.name.toUpperCase())
}
```
Though pet is not really in context, it is harmless and does not affect evaluation in any way...

Compiled and cached expressions

---

contributing.md
docs/development.md

1. Replaced section in `contributing.md` with link to `development.md` 
2. Updated `development.md` to use npm scripts; fixed reference to `bruno-lang` tests

Removed redundant instructions in docs

---

packages/bruno-app/src/components/Sidebar/CreateCollection/index.js

collectionFolderName `inputRef` was overriding the `inputRef` on collectionName

Correct the tab order on the CreateCollection modal

---

packages/bruno-query/readme.md
packages/bruno-query/src/index.ts
packages/bruno-query/tests/index.spec.ts

Filter shortcut for scalar properties
```js
get(data, '..items[?]', { id: 2, amount: 20 })
```
instead of
```js
get(data, '..items[?]', i => i.id === 2 && i.amount === 20)
```

filter shortcut for scalar properties

---

packages/bruno-app/src/components/RequestPane/GraphQLRequestPane/useGraphqlSchema.js
packages/bruno-app/src/components/RequestPane/RequestBody/RequestBodyMode/index.js
packages/bruno-app/src/components/Sidebar/NewRequest/index.js
packages/bruno-app/src/utils/collections/index.js

I propose the following UI terminology changes relating to the new request dialog:
1. `Http` --> `REST`
2. `Graphql` --> `GraphQL`
3. `Form Url Encoded` --> `Form URL Encoded`

Proposed adjustment to terminology on requests

---

packages/bruno-app/src/providers/Hotkeys/index.js

This commit adds a CMD+W hotkey (see #128 for details).
Please point me in the right direction if more error handling is required.
Caveat:  closing a tab with unsaved changes is consistent with the app behaviour when clicking the `x` to close the tab.

Proposed addition of CMD+W hotkey Re #128

---

packages/bruno-electron/src/ipc/network/index.js
packages/bruno-js/src/runtime/script-runtime.js

Solves #138 
Hey @helloanoop as you had the other PR where you have injected more packages into the sandbox. I took a branch out of that and added my changes on top of that.
I used axios and this modified pre-request script to resolve my issue

Adding support for using async pre-request scripts

---

packages/bruno-cli/readme.md

As part of a poc for testing on our CI, I'm exploring Bruno's cli.
Based on this excerpt from the documentation:
```
Or run all requests in a folder:
`bru run folder`
```
I tried to run the following command:
`bru run apps/backend/requests`
where `apps/backend/requests` is the collection root folder. I got the following error:
`You can run only at the root of a collection`
Thinking I typed the command wrong, I tried several commands before realizing that the command is only valid for the sub-folders of a collection.
I therefore propose a change in the document in order to clarify this point for newcomers

chore: improve the cli doc to avoid misunderstandings 

---

packages/bruno-app/src/components/Sidebar/Collections/index.js
packages/bruno-app/src/components/Sidebar/index.js
packages/bruno-app/src/pageComponents/Index/StyledWrapper.js

Loving bruno so far! I just converted our postman files containing 50+ collections and ran into #118 so I thought I'd try my hand at fixing it.
- Make sidebar height 100vh
- absolute position for collections scrolling container
- absolute position for sidebar footer
Thanks for the awesome work! Very much looking forward to diving deeper with bruno! So much nicer than the alternatives.
---
I also figured out how to get around the rollup error, here's the diff of my changes to `packages/bruno-graphql-docs/rollup.config.js`
```diff
module.exports = [
{
input: "src/index.ts",
output: [
...
],
plugins: [
postcss({
minimize: true,
+       extract: 'dist/esm/index.css',
extensions: ['.css']
}),
peerDepsExternal(),
nodeResolve({
extensions: ['.css']
}),
commonjs(),
typescript({ tsconfig: …
```

Enable scrolling in collections sidebar #118

---

packages/bruno-cli/src/commands/run.js
packages/bruno-cli/src/runner/run-single-request.js

Add ability in the cli to specify a file from which to read cacerts to be used to validate TLS connections.

support alternative cacert file in cli

---

packages/bruno-cli/src/runner/run-single-request.js
packages/bruno-electron/src/ipc/network/index.js

Add custom cacert file support in electron app. Process environment variables SSL_CERT_FILE or NODE_EXTRA_CA_CERTS can be used. The 'cacert' preference can also be used, but I have not added a way to set it. I was thinking maybe a file dialog in the preferences.
Added ability to use SSL_CERT_FILE or NODE_EXTRA_CA_CERTS process environment variables in the cli in addition to the 'cacert' command line option.
This should address the problem in issue #117.

support custom cacert file

---

packages/bruno-app/src/components/Environments/EnvironmentSelector/index.js
packages/bruno-app/src/components/ResponsePane/QueryResult/index.js
packages/bruno-app/src/components/ResponsePane/index.js
packages/bruno-cli/src/runner/prepare-request.js
packages/bruno-electron/src/ipc/network/prepare-request.js

Hi,
currently XML was presented in the response Pane surrounded by quotation marks and so the CodeEditor could not highlight the XML.
I added a check for the response type to check if the result is a JSON. Only then Stringify the JSON.
Before the `JSON.stringify` ran on XML too and added the quotations marks.
second change:
set the request header `content-type` only if it is not set by the user in the header variables.
BR
Mirko

check response type for ResponsePane CodeEditor

---

packages/bruno-app/src/utils/importers/postman-collection.js

Hallo @helloanoop,
While importing postman collections it can happen, that the language of a raw body is missing (problem of postman export)
I have implemented a fallback to search body language by header 'content-type'.
Can you please merge the fix?
It is possible to get a new release 0.14.1 with my fixes of the last days?
Postman is not usable anymore in my company, because we are not allowed to use postman accounts, because of data privacy. (All data is stored anywhere in the world.)
And we are working strong with XML.
Thanks
Mirko

#192 implement fallback to search body language by header 'content-type'

---

package.json
packages/bruno-electron/src/app/menu-template.js

Add `about-window` module to add a basic about window to bruno so that the user knows what version is currently installed.

Issue #203 Add about-window to help menu

---

packages/bruno-cli/examples/report.json
packages/bruno-cli/readme.md
packages/bruno-cli/src/commands/run.js
packages/bruno-cli/src/runner/run-single-request.js

This adds a `--output` or a `-o` option to dump the results of the CLI runs into a file.
This also modifies the way requests are run to reduce duplication of logic.

Adds an option to collect output from cli runs

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionProperties/index.js

This adds a fallback for when a user has no environment defined. Otherwise, there's a bug where the `environments.length` can't be computed and causes the screen to blank.

Adds fallback when no environments are defined

---

.gitignore
packages/bruno-cli/src/runner/run-single-request.js
packages/bruno-electron/src/ipc/network/index.js
packages/bruno-js/src/runtime/test-runtime.js
packages/bruno-js/src/test.js
packages/bruno-js/tests/runtime.spec.js

allow use async in tests
I'm using bruno/cli for integration testing and want to put some asynchronous stuff in the tests to allow queries to be run after getting the results to check data consistency.
I added a new test file for test-rutime in bruno-js

feat: allow test to be asynchrone

---

packages/bruno-app/src/components/Sidebar/CreateCollection/index.js

Currently:
https://github.com/usebruno/bruno/assets/39559178/9e9338f9-95b6-462c-bbee-fd705b29d739
With my fix:
https://github.com/usebruno/bruno/assets/39559178/49f87574-7d89-442b-8744-c5a14ffe34cc
---
Also, as an Idea: I think the name tooltip could be removed as it doesn't add any information and the Folder Name tooltip could be expanded to clarify that the folder will be created inside the selected location. To avoid mistakes like: `~/projects/my-api/docs/docs`.

Bugfix: Create collection modal validation

---

packages/bruno-app/src/components/VariablesEditor/index.js
packages/bruno-app/src/components/Welcome/index.js
packages/bruno-cli/src/index.js
readme.md

Signed-off-by: Andy Piper <andypiper@users.noreply.github.com>

Remove rogue apostrophes and capitalise API in text.

---

docs/development.md
packages/bruno-graphql-docs/rollup.config.js
packages/bruno-graphql-docs/src/index.ts

- during the dts transformation, the css import was not recognized, hence marking it as external in the dts transform didn't throw the error
- "extract: true" in postcss plugin makes sure the CSS file gets extracted to the final bundle as well
---
I think the pre-commit caused stylistic changes 🤔 lmk if anything needs to be changed or added

fix(graphql-docs/build): rollup error thrown during build

---

packages/bruno-app/src/utils/codemirror/brunoVarInfo.js
packages/bruno-app/src/utils/common/codemirror.js

Currently adjacent variables like `{{var1}}{{var2}}` are rendered by CM in one `<span>` because they had the same classname; and likewise considered as one token in apis like `getTokenAt`
Fixes: https://github.com/usebruno/bruno/issues/113

Ensure that adjacent variables are rendered in separate spans.

---

packages/bruno-app/src/utils/importers/insomnia-collection.js

To avoid name collisions, my fix adds number suffixes to duplicate names.

fix(#257): Name collision during Insomnia collection import

---

packages/bruno-app/src/utils/collections/index.js

When dragging and dropping items, to delay changing sequence numbers until after all the resource-dependent logic has completed, we were relying on the order of children in redux store (which we then converted into new seq numbers).
This order of children was however **not updated** when sequence numbers changed (for example due to file watch changes). This resulted in a seemingly random drag-and-drop ordering, which in fact was linked to the initial order when the collection was  loaded.
This change sorts all the items by sequence number prior to reordering, so that those random jumps no longer happen. As this happens on a deep clone of the collection, no data gets hurt in the process.
disclaimer: As I have close to no idea about how any of the technologies involved work, please feel …

fix(#154): correct ordering during drag-and-drop

---

packages/bruno-app/src/utils/common/index.js

SafeParseXML - Option for collapseContent: true in QueryResult/index is not being passed to XML-Formatter.

Fix for XML Formatting Options

---

packages/bruno-app/src/components/RequestPane/Assertions/AssertionRow/index.js
packages/bruno-app/src/components/RequestPane/FormUrlEncodedParams/index.js
packages/bruno-app/src/components/RequestPane/MultipartFormParams/index.js
packages/bruno-app/src/components/RequestPane/QueryParams/index.js
packages/bruno-app/src/components/RequestPane/RequestHeaders/index.js
packages/bruno-app/src/components/RequestPane/Vars/VarsTable/index.js
packages/bruno-app/src/components/SingleLineEditor/index.js

Two changes:
- the inline editor was made tab-friendly (it ignored tabs anyway, now it just treats them correctly)
- tabbing omits selection/deletion widgets as they seem much less likely to be used in practice
Now it's still not perfect for a few reasons:
- I'm not even sure what the user experience **should** be when taking into account sidebar
- if you add empty rows in headers and tab out to URL, the empty rows stay in place; if you start typing - they disappear
But a tiny bit less annoying nevertheless.
There is also an awful lot of copy-pastyism with those tables, might be work time consolidating at some point.

fix(#314): tabbing order through tables (variables etc) was inconsistent or impossible

---

packages/bruno-cli/src/runner/run-single-request.js
packages/bruno-electron/src/ipc/network/index.js

After all tests or assertions were deleted, the store was not updated because of the length checks. Now the assertions/tests will always try to run, to ensure the data is always updated.
Before my fix:
https://github.com/usebruno/bruno/assets/39559178/0ad3e466-f7e3-4f3d-ae02-27ecd22c616e
With my fix:
https://github.com/usebruno/bruno/assets/39559178/90edded8-a23e-4d1b-a4fb-9b5611a2a00d

fix(#270): Fix deleted assertions & tests shown in test tab

---

contributing.md
packages/bruno-app/src/components/ResponsePane/ResponseSize/index.js

I noticed that sometimes the response size is weirdly displayed.
- size `112932` is displayed as `110.28.999999999999996KB`
- size `112990` is displayed as `110.34KB`
The problem is in the decimal calculation. Rounding the value ensure we don't have two `.` in the displayed size.
Size with a bug:
```js
const size = 112932
if (size > 1024) {
// size is greater than 1kb
let kb = Math.floor(size / 1024);
let decimal = (((size % 1024) / 1024).toFixed(2) * 100);
sizeToDisplay = kb + '.' + decimal + 'KB';
} else {
sizeToDisplay = size + 'B';
}
console.log(sizeToDisplay)
```
`110.28.999999999999996KB` is displayed.
And with the current fix, `110.29KB` is displayed.
Also, update the `contributing` to increase the minimum Node version required.

Fix rounding response size

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/index.js

As discussed in #291 
- Add double click handler on `CollectionItem`
- On double click render rename modal

feat(291): add double click request to open rename modal

---

package.json
packages/bruno-cli/src/runner/run-single-request.js
packages/bruno-electron/package.json
packages/bruno-electron/src/ipc/network/index.js

HTTP proxies typically make use of TCP tunnels to send proxied HTTPS requests. However, Axios makes use of https.Agent by default which does not support TCP tunneling.
This PR makes use of the https-proxy-agent package which replaces https.Agent for proxied requests. Non-proxied requests still make use of https.Agent.
Note that this can be tested on any machine by spinning up a simple HTTP proxy with the following docker-compose:
```
services:
proxy:
image: ubuntu/squid
ports:
- "3128:3128"
```
Then, direct Bruno to use an http proxy with the hostname localhost and port 3128.
Before my changes, directing Bruno to use the proxy at localhost:3128 will result in a TLS error from Squid. After my changes, a TCP tunnel is established and HTTPS requests are able to be made.

Changed Proxied Requests to Use https-proxy-agent.

---

packages/bruno-app/src/components/Environments/EnvironmentSettings/CopyEnvironment/index.js
packages/bruno-app/src/components/Environments/EnvironmentSettings/EnvironmentList/EnvironmentDetails/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-electron/src/ipc/collection.js

As requested in https://github.com/usebruno/bruno/issues/336
This commit adds the "copy" button on the environments modal
It's the first time I mess around with Electron, ipc and redux so don't hesitate to correct me if something can be done in a better way
Screenshots:

Feature: Add new button to copy existing environments

---

package.json
packages/bruno-app/src/components/Sidebar/CreateCollection/index.js
packages/bruno-app/src/utils/importers/insomnia-collection.js
packages/bruno-app/src/utils/network/index.js
packages/bruno-electron/src/ipc/network/axios-instance.js
packages/bruno-electron/src/ipc/network/index.js

Hello there 👋🏽 
- Create an `axios` instance that uses `interceptors.response` and `interceptors.request` to have a better/accurate request duration number
- Add missing dependencies. For example `typescript` and `prettier` were missing and they are needed by `npm run build:bruno-query` and `npm run build:graphql-docs` and `husky` respectively.
- `pretty-quick` is an old package and depends on an older prettier version
In regards to the missing deps, let me know if you would rather have this discarded from the PR.
I recently started using Bruno after the Insomnia fiasco, and noticed that my API request durations weren't necessarily correct.
The issue being that using `Date.now()` before and after the request happens wouldn't yield correct duration results since axios has other timings …

fix(network): use axios interceptors to better reflect durations

---

packages/bruno-app/src/components/Sidebar/index.js

I don't know, if it was for me only but,
while on dark mode github star button was still looking white, so I made some changes to fix that.
checked on my device, works on both dark and light mode
before  changes ::
after changes ::

github star button color fix

---

packages/bruno-electron/src/index.js

- Only setting `icon` property would set the icon of the window in Linux.
- Set `title` to `Bruno`.
- Enable `autoHideMenuBar` to prevent ugly menu bars in dark mode.
I was not able to test these changes due to `phantomjs` errors but I'm sure that these changes are correct.

Better BrowserWindow

---

packages/bruno-cli/src/runner/run-single-request.js

This PR fixes an issue with `start` constant not being in scope
There is still an issue with a failed request not being shown as failed (the yellow marked):
This should probably fixed in a separate PR?

Put constant in outer scope

---

packages/bruno-electron/src/app/watcher.js

Prevents this from happening when secret value is empty:
```
Error: Decrypt failed: unrecognized string format
at decryptString (/home/me/bruno/packages/bruno-electron/src/utils/encryption.js:70:11)
at /home/me/bruno/packages/bruno-electron/src/app/watcher.js:142:28
at arrayEach (/home/me/bruno/node_modules/lodash/lodash.js:530:11)
at Function.forEach (/home/me/bruno/node_modules/lodash/lodash.js:9410:14)
at changeEnvironmentFile (/home/me/bruno/packages/bruno-electron/src/app/watcher.js:138:9)
at change (/home/lared/projects/me/bruno/packages/bruno-electron/src/app/watcher.js:341:12)
at FSWatcher.<anonymous> (/home/me/bruno/bruno/packages/bruno-electron/src/app/watcher.js:431:37)
at FSWatcher.emit (node:events:527:28)
at FSWatcher.emitWithAll …
```

fix(#399): loading environment with empty secret variable fails

---

packages/bruno-cli/src/runner/run-single-request.js
packages/bruno-cli/src/utils/axios-instance.js

Measure response time with axios interceptor, similar to https://github.com/usebruno/bruno/pull/368
There is now some code duplication with `axios-instance.js` being twice in the project. Should we address this in this PR?
Note that I also modified `axios-instance.js` slightly, since `error.response` might be undefined:
```javascript
(error) => {
if (error.response) {
const end = Date.now();
const start = error.config.headers['request-start-time'];
error.response.headers['request-duration'] = end - start;
}
return Promise.reject(error);
}
```

Use axios interceptor to measure response time

---

packages/bruno-app/src/pages/_app.js

The GraphQL docs explorer doesn't have any CSS styling which makes very difficult to use, see image:
I'm new to Bruno so not sure if this has worked before.
This PR simply imports the necessary CSS file in the `_app.js` file. Not very familiar with the code base so let me know if there's a better way to do this.
After image:

fix: add missing CSS for GraphQL docs explorer

---

packages/bruno-app/src/utils/collections/index.js

Previously I touched some code for moving requests between folders in #154, those two additional fixes should (hopefully) fully address the situation.

fix(#428): moving requests into directories or into root of collection broke ordering

---

packages/bruno-app/src/components/RequestTabs/RequestTab/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/RequestMethod/StyledWrapper.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/RequestMethod/index.js
packages/bruno-app/src/themes/dark.js
packages/bruno-app/src/themes/light.js

The colors of the request on the tab and the sidebar item were different, so I made some changes to fix that.
before::
after ::

request colors made consistent on the sidebar and tabs

---

packages/bruno-app/src/components/Sidebar/TitleBar/index.js
packages/bruno-electron/src/ipc/collection.js

Addresses issue in #440 where a common operation, opening dev tools (ex. to debug scripts) was only available from menu, which by default is hidden, which generated some friction in user experience.

fix(#440) open dev tools from menu

---

packages/bruno-js/src/runtime/assert-runtime.js

This is a small fix for the 'between' runtime assert.
Without this fix, the assertion fails with the message "value is not defined"

Fix 'between' assertion

---

packages/bruno-electron/src/index.js
packages/bruno-electron/src/store/window-state.js
packages/bruno-electron/src/utils/window.js

This PR implements issue #451 and adds code to persist the window state of the Electron application, including its size and position so it's starting at the same position and size when opening the application as it was closed. I also added some checks to reset both position or size to default if it's not inside the screen border's (e.g. when switching to a smaller screen).

Persist window state (size, position)

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/index.js

Currently, to open dropdown action on collection/folder/request must be click on icon at the right side item. This PR contains change to give access to right click mouse to show dropdown action.
https://github.com/usebruno/bruno/assets/37659721/1e522012-0282-4476-b31f-d5fa3551439f

Better experience for open request or folder dropdown action

---

packages/bruno-app/src/components/RequestPane/Assertions/AssertionRow/index.js

This PR fixes the following bug in GUI:
> Assertion operator falls back to "eq" when user starts changing assertion value.
> 
> Steps to reproduce:
> 1. Create any assertion that requires value, except "eq" (for example "neq")
> 2. Start changing the value
>
> Expected: Operator doesn't change
> Actual: Operator falls back to "eq"

Fix assertion value modification

---

packages/bruno-js/src/runtime/script-runtime.js

Simply wasn't added to the runtime.

fix(#473) add Ajv to the runtime

---

packages/bruno-js/src/runtime/test-runtime.js

In previous PR I added ajv to runtime in scripts. I discovered that node-fetch is missing in tests, so I added this and ajv there too.

fix(#473) add Ajv and node-fetch to the test runtime

---

package-lock.json
packages/bruno-app/src/pageComponents/Index/index.js
packages/bruno-electron/src/index.js

Hey,
there have been two issues with GraphQL validation (issue https://github.com/usebruno/bruno/issues/474):
* the `codemirror/addon/lint/lint` module was not imported, consequently the GraphQL linting/validation was not enabled
* the content security policy did not allow to load base64 inline images, required for the red squiggly underlines and the little icon in the popover
I have also allowed myself to make the CSP stricter and successfully tested it in the development and production builds. Now the `unsafe-*` policies will only be used during development where they are needed.

Fix GraphQL validation

---

packages/bruno-app/src/components/Sidebar/NewFolder/index.js
packages/bruno-app/src/components/Sidebar/NewRequest/index.js

- Fixed Name Validation in Add Request and Add Folder Modals, previously it wasn't trimming the string
- Fix validation message on Add folder modal

fix: add request and folder modal validation fixes

---

packages/bruno-app/src/components/RequestPane/RequestBody/RequestBodyMode/index.js
packages/bruno-app/src/components/RequestPane/RequestBody/index.js
packages/bruno-app/src/pageComponents/Index/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/index.js
packages/bruno-app/src/utils/collections/index.js
packages/bruno-electron/src/ipc/network/prepare-request.js
packages/bruno-lang/v2/src/bruToJson.js
packages/bruno-lang/v2/src/jsonToBru.js
packages/bruno-lang/v2/tests/fixtures/request.bru
packages/bruno-lang/v2/tests/fixtures/request.json
packages/bruno-schema/src/collections/index.js

This PR adds support for [SPARQL](https://en.wikipedia.org/wiki/SPARQL) bodies:
SPARQL bodies are integrated into bruno-lang v2, but not in v1, is this ok or should v1 also be supported?
Example query:
```sparql
SELECT ?predicate (COUNT(DISTINCT ?subject) AS ?count) WHERE {
?subject ?predicate ?object .
}
GROUP BY ?predicate
ORDER BY DESC(?count)
LIMIT 10
```

Add support for SPARQL bodies

---

packages/bruno-electron/src/ipc/network/axios-instance.js

When you try to do a request to an invalid URL, e.g. `https://`, then the following error was shown:
With this fix the actual error is shown:

Fixed error handling

---

packages/bruno-electron/src/ipc/network/index.js
packages/bruno-electron/src/ipc/network/prepare-gql-introspection-request.js
packages/bruno-electron/src/ipc/network/prepare-request.js

With https://github.com/usebruno/bruno/commit/1ce8d707f1b4cc461235333174b3bdcb290c9c40 merged I think it makes sense to reuse the same logic for the introspection request. Use the collection level authentication if possible, else use request level authentication.

feat(#354): Use collection level auth if available for introspection request

---

packages/bruno-electron/.gitignore
packages/bruno-electron/electron-builder-config.js

Adds RPM as a Linux target to the electron-builder config.
The output is a `bruno_%version%_x86_64_linux.rpm` file in the `packages/bruno-electron/out` directory.
Resolves #230.

Add RPM linux build target

---

packages/bruno-cli/src/runner/run-single-request.js

Due to missing variable while calling `prepareRequest()` auth from `collection.bru` was not added to the request during `bru run`. 
Is a reproduction of the bug needed?

fix(bruno-cli): add missing variable to `prepareRequest`

---

packages/bruno-app/src/components/Sidebar/Collections/index.js

This PR will add a small clear button in the collection search field to quickly delete the input. Previously it was required that the input field was either cleared character for character or by selecting the input and hit backspace. This is a small QoL feature.

feat: add button to clear collection search

---

packages/bruno-app/src/components/RequestPane/Assertions/AssertionOperator/index.js

In dark mode assert operator dropdown background color was not changing to dark
before:
after:

assert operator dropdown bgcolor fix

---

packages/bruno-app/src/components/CollectionSettings/ClientCertSettings/StyledWrapper.js
packages/bruno-app/src/components/CollectionSettings/ClientCertSettings/index.js
packages/bruno-app/src/components/CollectionSettings/index.js
packages/bruno-electron/src/ipc/network/index.js

Add initial mutual TLS support with client certificate in global preferences

feat: client certificate support

---

packages/bruno-app/src/components/Environments/EnvironmentSettings/EnvironmentList/index.js
packages/bruno-app/src/components/Welcome/index.js

The Import icon is slightly misleading as the current one represents upload rather than download/import. Solves issue #601

[User Experience] Change import icon

---

packages/bruno-app/src/components/RequestPane/RequestBody/RequestBodyMode/index.js

This PR implements the prettify feature on the request body mode JSON
https://github.com/usebruno/bruno/assets/9076885/3a4812a4-07a7-4951-b564-a84c0d0663c7
the bru file save as
```
body:json {
{
"foo": 1,
"bar": "test",
"bad": 1
}
}
```
solved #550
[![]()](https://github.com/usebruno/bruno/assets/9076885/3a4812a4-07a7-4951-b564-a84c0d0663c7
)

Feature (#550): JSON body request prettify

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/RemoveCollection/index.js

Simply adds the name of the collection to the confirmation dialog.

feat: add collection name to remove dialog

---

packages/bruno-app/src/components/ResponsePane/ResponseSize/index.js

This PR just adds a title to the ResponseSize component, showing the size in bytes, in addition to human-readable KB and MB.

Fix #646: show exact response size in bytes on mouse hover

---

packages/bruno-js/src/interpolate-string.js
packages/bruno-js/src/runtime/assert-runtime.js

Adds interpolation to variable runtime as it was missing from there. Fixes #624
> NOTE! i copied interpolate-string.js from bruno-cli. I would've required interpolateString function from bruno-cli but that would've caused depenceny cycle. My suggestion is to move all interpolate files to bruno-js and then require those to bruno-cli and other packages from there.

Adds variable interpolate to assert runtime

---

packages/bruno-app/src/components/Sidebar/CreateCollection/index.js

- Autofill folder name to be the same as collection name as and when the user types in the collection name.
- In order to improve user experience further, once the user consciously updates the folder name, and then comes back to update the collection name, this time around, folder name is not updated automatically.
- Fixes issue https://github.com/usebruno/bruno/issues/637

Fixes #637: autofill folder name as collection name

---

.github/workflows/unit-tests.yml
package.json
packages/bruno-app/package.json

- jump to `actions/checkout` v4 (latest version)
- retrieve node version from NVM instead of hard-coded
- add a new job to run prettier (in case people skip pre-commit hook)

Update GitHub workflows

---

package-lock.json
packages/bruno-app/src/components/RequestPane/GraphQLRequestPane/index.js
packages/bruno-app/src/components/RequestPane/GraphQLRequestPane/useGraphqlSchema.js
packages/bruno-electron/src/ipc/network/index.js

Currently the requests to fetch GraphQL schemas does not use the recently introduced client certificates or any configured proxy. This change enables that :)
In addition I added any occured error to the toast, I am not 100% certain about that as it could result in a quite long toast. On the other hand it left me wondering when the request failed without any notice what went wrong... 

feat: use client certificates and proxy for fetching graphql schema

---

packages/bruno-electron/src/app/menu-template.js

The default shortcut to close in the menu is Ctrl+W, I changed it to Ctrl+Shift+Q because Firefox uses this shortcut for closing

fix(#529): Fix Ctrl+W closes Bruno

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/index.js

Fix for issue #509 also reworking for PR #537. This PR separate function left click and right click functionality to prevent event mouse up fired up when user hold mouse click and release the hold at sidebar component.

fix: event mouse up triggered when hold mouse click at anywhere and release at sidebar

---

packages/bruno-electron/src/index.js
packages/bruno-electron/src/store/window-state.js
packages/bruno-electron/src/utils/window.js

Fix for https://github.com/usebruno/bruno/pull/452#issuecomment-1755101199: save if the window is maximized in the window state and maximize on start if it was before.

Fix: save window maximized state

---

packages/bruno-app/src/utils/importers/postman-collection.js

In Postman you can define Pre-request scripts and tests to do when you do a request.  Those information are stored in the collection but were not imported by **bruno**
linked to this feature :  [[FEATURE] Support Postman pre-request script and tests when Importing collection #710 ](https://github.com/usebruno/bruno/issues/710)
- [X ] **I have added screenshots or gifs to help explain the change if applicable.**
#hacktoberfest

Added pre-request and tests scripts support from Postman Collection

---

packages/bruno-cli/src/runner/run-single-request.js
packages/bruno-cli/src/utils/proxy-util.js
packages/bruno-electron/src/ipc/network/index.js
packages/bruno-electron/src/utils/proxy-util.js

This PR fixes https://github.com/usebruno/bruno/issues/362
When Bruno would make SSL/TLS connections through a proxy, it would not respect connection options like `rejectUnauthorized` or `ca`. This was making it difficult to use when going through a self-signing MiTM proxy, or using a custom certificate authority.
The issue was caused by an upstream bug in [https-proxy-agent](https://github.com/TooTallNate/proxy-agents/tree/main/packages/https-proxy-agent), where it doesn't permit options  to be passed down when upgrading sockets to TLS:
* https://github.com/TooTallNate/proxy-agents/issues/194
The same underlying issue has been reported against multiple versions of that library over the years. As you can see in the comments, people have either switched to other libraries, or patched it to …

fix: respect rejectUnauthorized and ca opts when proxying https

---

packages/bruno-app/src/components/CodeEditor/StyledWrapper.js

(fixes: https://github.com/usebruno/bruno/issues/693)
This PR fixes the overflow issue by forcing line breaks through CSS:
| Before | After |
|---|---|
| <img width="1392" alt="overflowing-code-editor" src="https://github.com/usebruno/bruno/assets/68591/04a4627a-bf78-433a-a28b-69d60e0a9633"> | <img width="1392" alt="fixed-code-editor" src="https://github.com/usebruno/bruno/assets/68591/bb69472b-542e-48eb-9f50-efb2ea6e7038"> |

fix: overflowing code editor

---

packages/bruno-app/src/components/RequestPane/FormUrlEncodedParams/index.js
packages/bruno-app/src/components/SingleLineEditor/index.js
packages/bruno-lang/v2/src/bruToJson.js
packages/bruno-lang/v2/src/jsonToBru.js

Fix #571 
- Allow newlines in form URL encoded bodies using `ALT + ENTER`
- Allow any character in the parameter values by:
- encoding parameter values of the body before saving
- decoding parameter values of the body after loading
- Use `ALT + ENTER` to create a newline
- Use any character in the request
```
meta {
name: Test
type: http
seq: 1
}
post {
url: https://bruno-tester.requestcatcher.com/
body: formUrlEncoded
auth: none
}
body:form-urlencoded {
test: 123:456
789
}
```
```
meta {
name: Test
type: http
seq: 1
}
post {
url: https://bruno-tester.requestcatcher.com/
body: formUrlEncoded
auth: none
}
body:form-urlencoded {
test: 123%3A456%0A789
}
```
**Response Body:**
```
test=123%3A456%0A789
```
Note: Keeping the PR small and focused helps make it easier to review and merge. If you …

fix #571 - allow newlines and encode uri form data

---

packages/bruno-electron/src/ipc/network/index.js
packages/bruno-electron/src/ipc/network/prepare-request.js

This PR addresses the following feature request:
* https://github.com/usebruno/bruno/issues/704
It automatically runs the usual pre-request and post-response code (vars and scripts) when fetching the GQL schema. It also tries to consolidate some of the relevant code to make re-use more manageable.

feat: run prerequest/postresponse actions when fetching gql schema

---

packages/bruno-app/src/components/Dropdown/StyledWrapper.js
packages/bruno-app/src/components/Environments/EnvironmentSettings/EnvironmentList/StyledWrapper.js

Adds an overflow for the environment dropdown and modal so they don't expand beyond the bottom of the app window
Before:
After:

adjust styles on environment dropdown and modal

---

packages/bruno-app/src/components/Sidebar/ImportCollection/index.js
packages/bruno-app/src/utils/importers/openapi-collection.js

First pass at adding import for OpenAPI collections. Currently this only supports v3. Likely still missing some things.
Some assumptions worth considering from product standpoint and deserve discussion:
- It uses the operationId as the "name" of the request
- It groups the requests by tags (the first tag)
- it uses the first security scheme configured globally (if an operation overrides the security config, it uses the first one defined under the operation)
- For basic auth, it adds `{{username}}` and `{{password}}` for the values so that one wouldn't have to run through each request to add it. It similarly uses `{{apiKey}}` if API Key (in a header) security scheme is used
- For request bodies, it uses the first content type defined in the spec
- it uses the first "server" in the servers …

feat: openapi v3 import

---

packages/bruno-app/src/utils/importers/openapi-collection.js

- Handles no security block defined now (bugfix)
- handles no operationId defined for an operation. Now it will use some other defaults (summary, description or fall back on using Method + path)
These were mentioned in this PR: https://github.com/usebruno/bruno/pull/578

OpenApi v3 case fixes

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/RemoveCollection/index.js

Fixes #741 misleading message on remove collection. Replace "delete" with "remove" since collection is not deleted from disk, only remove from Bruno.
Before
After

fix misleading message

---

package-lock.json
packages/bruno-electron/package.json

- update bruno-electron to use v0.9.1 of @usebruno/js closes #751 and closes #749

fix: update @usebruno/js to a working version in bruno-electron

---

packages/bruno-app/src/utils/importers/openapi-collection.js

Fixes #744 . I included all possible methods per OpenAPI spec.

OpenAPI import - filter out non-methods on path item objects parsing

---

packages/bruno-app/src/utils/importers/openapi-collection.js

Now, this is embarrassing. I was testing code for #744 on different env from where it was committed, and I somehow lost `return`.

[bugfix] fix OpenAPI method filtering predicate

---

packages/bruno-app/src/components/RequestTabs/index.js

Make Tabs closable by mouseclick.
If a user clicks on a tab with a mouse button other then the primary one -> Close the corresponding tab.
- [/] **The pull request only addresses one issue or adds one feature.**
- [/] **The pull request does not introduce any breaking changes**
- [/] **I have added screenshots or gifs to help explain the change if applicable.**
- [/] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [/] **Create an issue and link to the pull request.**

Make Tabs closable by mouseclick. Closes #778

---

packages/bruno-app/src/components/CodeEditor/index.js
packages/bruno-app/src/pages/Bruno/index.js

Add XML fold to Response and Body. Add count of object directly inside of fold.  Include hotkeys Ctrl-Y to fold and Ctrl-I to unfold all XML/JSON data.
Fix #315 by adding these hotkeys:
Ctrl-Y: fold all
Ctrl-I: unfold all
This is to create a tree-view like functionality that can completely fold XML/JSON data in Response and Body. The ability to fold XML data is helpful and only requires 1 line of code. There is no UI button to fold/unfold all but that can be added if users are looking for it.
https://github.com/usebruno/bruno/assets/115114979/5e04fbad-c6d0-46ba-bec9-f7d48c3e72be
Please see …

Add better CodeMirror folding options

---

packages/bruno-app/package.json
packages/bruno-app/src/pages/_app.js
packages/bruno-electron/src/index.js

Fixes: #740
- Custom error when opening bruno in the browser
- Custom error when starting electron without the web server running
- Force Next dev server to use port 3000
- Added `-p 3000` to next dev command

feat(#740): Add hints for local bruno setup

---

packages/bruno-app/src/components/Sidebar/index.js
packages/bruno-app/src/providers/App/useIpcEvents.js
packages/bruno-app/src/providers/ReduxStore/slices/app.js
packages/bruno-electron/src/app/menu-template.js
packages/bruno-electron/src/ipc/preferences.js

Fixes #762.
Currently there is no menu entry to open the preferences. Additionally, most apps allow to quickly enter preferences with `cmd+,`. I think both things should be added to Bruno so it behaves like most apps.

Add menu entry for preferences and add shortcut for it

---

packages/bruno-js/src/runtime/script-runtime.js
packages/bruno-js/src/runtime/test-runtime.js

Solves #438 (contains additional context).
This feature allows the user to add addtional script context roots to be able to share code/scripts between collections.
Example collection config:
```
{
"version": "1",
"name": "cloud",
"type": "collection",
"scripts": {
"additionalContextRoots": [
"../scripts"
]
}
}
```
It supports absolute and relative paths.

[feature] allow multiple script context roots

---

packages/bruno-app/src/utils/importers/postman-collection.js

Fixes: #790
This PR adds functionality to import a GraphQL collection exported from Postman client into Bruno.
**Changes:**
1. Add function `parseGraphQLQuery()` to parse and clean incoming GraphQL queries from postman collection
2. Add function `parseGraphQLVariables()` to parse and clean incoming GraphQL variables
3. Add function `parseGraphQLRequest()` to handle validating incoming data and keys
This PR check the `mode` of the request item in the collection to then trigger a GraphQL sanitisation and build a valid request to be input into Bru format.
```JSON
{
"info": {
"_postman_id": "c33bffc4-0e32-498b-a12d-2b5d54eebf14",
"name": "Test Stub Graphql",
"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
},
"item": [
{
"name": "Get Countries",
"id": …
```

feat: Adding ability to import postman graphql collections

---

packages/bruno-electron/src/ipc/network/prepare-request.js

Fix #843 
Missing imports
before:
after:

fix: Multipart Form

---

packages/bruno-app/src/components/CodeEditor/index.js

Now response/body will be refresh each time it gets resized so the cursor always stays in the right place.
This will fix #402 and make it easier to adjust the response/body window size to see them better while not losing the cursor. It might not be very efficient if the response/body is very large (haven't noticed any issues yet).
https://github.com/usebruno/bruno/assets/115114979/49d53071-7a27-45d2-ad39-52754efb2508
https://github.com/usebruno/bruno/assets/115114979/7c07201e-5f8a-4c8a-b0ad-f8f45d7daac3

fix (#402): response/body cursor offset on resize

---

packages/bruno-app/src/utils/common/codemirror.js

Fixes #680.
Non-string collection variables are displayed in code editor as red without tooltip with variable value. So this PR fixes this bug and they are now correctly displayed as green also in cases value is null. They are red only in case they are undefined.

fix (#680): fixed non-string variables to be displayed correctly in code editor

---

package-lock.json
packages/bruno-app/package.json
packages/bruno-app/src/components/Sidebar/NewRequest/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-app/src/utils/curl/index.js

This PR add the capability to create an HTTP request from a valid cURL command (fixes https://github.com/usebruno/bruno/issues/338)
- Added **From Curl** option in the New Request modal.
- Added `parse-curl` as a dependency and new utility method `getRequestFromCurlCommand` to parse cURL commands

Add new request from cURL command

---

packages/bruno-app/src/components/Environments/EnvironmentSettings/EnvironmentList/EnvironmentDetails/EnvironmentVariables/index.js
packages/bruno-app/src/components/RequestPane/Vars/VarsTable/index.js
packages/bruno-app/src/utils/common/regex.js
packages/bruno-js/src/bru.js

Closes: #853 & #682
Allow `-` in variable names, update error messages & refactor the regex into a constant.

fix(#853): Allow - in variable names & small refactor

---

packages/bruno-app/src/components/CollectionSettings/Auth/AuthMode/index.js
packages/bruno-app/src/components/CollectionSettings/Auth/DigestAuth/StyledWrapper.js
packages/bruno-app/src/components/CollectionSettings/Auth/DigestAuth/index.js
packages/bruno-app/src/components/CollectionSettings/Auth/index.js
packages/bruno-app/src/components/RequestPane/Auth/AuthMode/index.js
packages/bruno-app/src/components/RequestPane/Auth/DigestAuth/StyledWrapper.js
packages/bruno-app/src/components/RequestPane/Auth/DigestAuth/index.js
packages/bruno-app/src/components/RequestPane/Auth/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/index.js
packages/bruno-app/src/utils/collections/index.js
packages/bruno-app/src/utils/importers/insomnia-collection.js
packages/bruno-app/src/utils/importers/openapi-collection.js
packages/bruno-electron/src/ipc/network/digestauth-helper.js
packages/bruno-electron/src/ipc/network/index.js
packages/bruno-electron/src/ipc/network/interpolate-vars.js
packages/bruno-electron/src/ipc/network/prepare-request.js
packages/bruno-lang/v2/src/bruToJson.js
packages/bruno-lang/v2/src/collectionBruToJson.js
packages/bruno-lang/v2/src/jsonToBru.js
packages/bruno-lang/v2/src/jsonToCollectionBru.js
packages/bruno-lang/v2/tests/fixtures/collection.bru
packages/bruno-lang/v2/tests/fixtures/collection.json
packages/bruno-lang/v2/tests/fixtures/request.bru
packages/bruno-lang/v2/tests/fixtures/request.json
packages/bruno-schema/src/collections/index.js

Enables the use of Digest as an additional authentication option.
Limitations:
- Supports the MD5 algorithm only.
- Supports username and password input only. No advanced parameterization.
Guidance required:
1. What is the best place to add automated tests for Digest?
2. How can I verify this PR doesn't introduce breaking changes?
3. I'm only familiar with the UI usage and need some help verifying Bru Lang / Collection Runner / CLI
Screenshots:
Get request - Auth and Vars defined in the request.
Post request - Auth defined in the collection, Vars defined in the environment.

Add Digest Auth Support #119

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/StyledWrapper.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/index.js

Resolves #849
During drag and drop, the target collection has a `isOver` property provided by the `collect` function 
https://github.com/usebruno/bruno/blob/c46fbfbde39b025c5e1692477508c2162b65f4aa/packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/index.js#L60-L62
We use that to add a new class to the collection item and that class has the same property as the existing `:hover` 
https://github.com/usebruno/bruno/assets/674667/4ff5bd47-fdcb-4ebd-abf7-bef91477b653

feat: add class when collection name is hovered during drag and drop

---

packages/bruno-electron/src/index.js

Fixes this electron startup error:
```
(node:9856) UnhandledPromiseRejectionWarning: Error: Each line must end in a semicolon
at exports.setContentSecurityPolicy (C:\Users\Timon\projects\bruno\node_modules\electron-util\index.js:150:9)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:9856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```
This happened because the last line was missing a …

fix: Fix Content-Security-Policy config

---

packages/bruno-app/src/components/RequestPane/QueryUrl/index.js

I fixed #961 by applying .trim() on the incoming url.
Unsure if tests are used to safeguard the functionality of components, I didn't see any tests for QueryUrl, but maybe I overlooked them.

fix #961 by using trim

---

packages/bruno-app/src/utils/importers/openapi-collection.js

Problem: Issue relates to OpenAPI specs which have self referencing components, resulting in infinite loops being made within resolveRefs.
Solution: Added basic use of Set to store already-traversed items within the OpenAPI spec.
Tested against the API Spec mentioned in issue [939](https://github.com/usebruno/bruno/issues/939#issue-1986513743) - both as JSON and YAML.

Fix inifinite loop in openapi-spec import with self-references

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/GenerateCodeItem/CodeView/index.js
packages/bruno-app/src/utils/codegenerator/har.js

Closes - #901 
While debugging the issue stated in #901, I found another issue(custom headers not being shown in code-generator at all, possibly missed in #280)
This PR addresses both of these:
* unwanted header - `content-type` added in code generator by default
* custom header not added in code generator at all
Snapshot: - pst

fix(#901): fix headers in code generator

---

packages/bruno-app/src/components/CollectionSettings/ProxySettings/index.js
packages/bruno-app/src/components/Preferences/ProxySettings/index.js
packages/bruno-cli/src/runner/run-single-request.js
packages/bruno-electron/src/ipc/network/index.js

If no proxy configuration is given on collection level, check for the global proxy configuration.
Allow empty port for proxy configuration

#937, #921 improve evaluation of proxy configuration, allow empty port

---

packages/bruno-app/src/components/Environments/EnvironmentSettings/EnvironmentList/EnvironmentDetails/EnvironmentVariables/index.js

Closes #904 
Allows empty value for an environment variable(useful as user might want to create variables and assign values later)

fix(#904): fix environment save when empty secret exists

---

packages/bruno-electron/src/utils/cookies.js

Closes #1012
After some digging, it looks like this is fixed by using the options `ignoreError`: `true` on [tough-cookie cookieJar.setCookieSync](https://www.npmjs.com/package/tough-cookie#setcookiecookieorstring-currenturl-options-callbackerr-cookie).
This will silently ignore many invalid cooke:
To validate the fix, I've added an endpoint in `bruno-testbench`:
```javascript
app.get('/cookies', function (req, res) {
res.cookie('test-valid', 'something');
res.cookie('test-invalid', 'something-invalid', { domain: 'invalid.com' });
return res.send();
});
```
To keep the PR focused on the fix I have not included this but I'm happy to commit it if you prefer.
I've also tested the request in #1102 and the errors is indeed fixed.
Note: Keeping the PR small and focused helps make it easier to …

fix(#1012): silently ignore invalid cookie

---

packages/bruno-app/src/utils/importers/postman-collection.js

Refers to https://github.com/usebruno/bruno/issues/955 
If you have multiple folders with the same names when you import your Postman Collection, only the first one will be imported and all of the others will be ignored. I think there are 3 solutions 
1. Merge all the requests into one folder
2. Keep the folders and add a number to the end
3. Simply notify the user that all the folders could not be imported
For now I chose the 2nd solution, see capture : 
https://github.com/usebruno/bruno/assets/46541094/91792067-9669-410f-a12f-94d9ca8585ea
Let me know if it's the desired behaviour.
Please see …

feat: handle postman import with same folder names (#955)

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/index.js

Hello,
I've added a feature that allows users to run an item directly from the sidebar menu. 
With this update, when you right-click on an item in the sidebar, you now have the option to run it. This action opens the tab with the selected item (if it's not already open) and executes it. This enhancement eliminates the need to click on each item and then go to the top-right corner to find and click the IconArrowRight in the queryUrl to run it.
It’s an alternative to the run collection if you want to do it step by step.
Issue : #1017

feat(#1017) Added ability to run a single request from sidebar

---

package-lock.json
packages/bruno-app/package.json
packages/bruno-app/src/components/CodeEditor/index.js

Fix false linting errors for comments inside of JSON body. This is needed since Bruno already removes comments from the body of the body of JSON requests.
This is to fix #1008 by replacing all comments with spaces for the JSON linter. Had to override the normal JSON linter with one that can replace comments and keep placement of linting errors. There are other JSON linting things that could be done but I will leave them to other commits after this gets merged.
https://github.com/usebruno/bruno/assets/115114979/0c6b3c55-3dd9-461e-9129-96fdfc4a1f37
* strip-json-comments (pretty compact and few dependencies) …

Fix (#1008) by removing comments from JSON linter.

---

packages/bruno-app/src/components/ResponsePane/QueryResult/index.js
packages/bruno-app/src/utils/common/index.js

Closes: #1035 
while rendering a API response, all falsy values were ignored
this is fixed with this PR

fix(#1035): fix falsy check of response

---

packages/bruno-app/src/components/CodeEditor/index.js

Convert unquoted variables in JSON body to 1 in JSON linter. This allows for putting multiple environment/collection variables next to each other and still be unquoted.
This is to fix (#1038) by making the JSON linter replace unquoted variables with 1 so that it passes it's tests and matches what is allowed in the JSON body. It should also fix the prettify check that I failed last commit.

Fix (#1038): Handle unquoted variables in JSON Lint

---

packages/bruno-app/src/utils/codegenerator/har.js

Fixes #1089 to filter out disabled query params when generating code

fix(GenerateCode): filter out disabled query params

---

packages/bruno-app/src/utils/importers/insomnia-collection.js

Closes #1024 
Changed `variables` to be an empty string just like `query` when there's an exception while parsing a GraphQL request.
|Before|After|
|-------|------|
|<video src="https://github.com/usebruno/bruno/assets/30027205/99c71328-9928-4656-92a5-69bbb9dd162f"></video>|<video src="https://github.com/usebruno/bruno/assets/30027205/b8dfbb1b-3406-4a04-9566-f80aeafe2f4b"></video>|

fix(#1024): Fix validation error on GraphQL request when importing Insomnia collection

---

packages/bruno-electron/src/ipc/network/prepare-request.js
packages/bruno-electron/tests/network/prepare-request.spec.js

Closes #946 
This is something which I also missed from Postman, now users can send a request without specifying the protocol.
We now prepend `http://` to the URL when preparing the request if there's no protocol.
|Before|After|
|-------|------|
|<video src="https://github.com/usebruno/bruno/assets/30027205/6bfe4d66-68bc-4c6c-92e6-70bac0efadc1"></video>|<video src="https://github.com/usebruno/bruno/assets/30027205/c8e09786-c908-4191-b9e9-e3449d5062a2"></video>|

feat(#946): Send request even when protocol isn't specified in URL

---

packages/bruno-app/src/utils/importers/openapi-collection.js

Swap order for the source of the operationName when importing from openApi with a summary
This just to assure that in case a summary is provided, the openApi collection prefers it instead of the operantionId, which is too less explanatory 
Linked issue resolve: https://github.com/usebruno/bruno/issues/994

Update openapi-collection.js to change the order of the source for the operationName

---

packages/bruno-electron/src/index.js

Updated Electron's Content-Security-Policy to include `app.posthog.com`. This fixes telemetry data not being sent.

Fix: Update CSP to allow posthog

---

packages/bruno-app/src/components/Environments/EnvironmentSettings/EnvironmentList/EnvironmentDetails/EnvironmentVariables/index.js
packages/bruno-app/src/components/RequestPane/Vars/VarsTable/index.js
packages/bruno-app/src/utils/common/regex.js
packages/bruno-electron/src/ipc/network/interpolate-vars.js
packages/bruno-js/src/bru.js

Closes #964 
Thanks for creating this project btw! I was getting really disappointed with the alternatives (Insomnia, Postman, etc.) before stumbling upon Bruno on HN, and it's exactly what I was looking for.
|Before|After|
|-------|------|
|![image](https://github.com/usebruno/bruno/assets/30027205/8dc495e4-2164-4298-84a9-be0dae9a72e5)|![image](https://github.com/usebruno/bruno/assets/30027205/b7bf5480-04b4-498c-9fa7-27471d2f0ced)|
|![image](https://github.com/usebruno/bruno/assets/30027205/97412176-b0e3-4d8f-8a18-fc7060d43b6e)|![image](https://github.com/usebruno/bruno/assets/30027205/359caad1-98b8-41db-bc8e-f17511b39d7c)|
||![image](https://github.com/usebruno/bruno/assets/30027205/d5c291f6-f357-4d7b-b251-84f006ee12df)|
Added `.` to the Regex, removed the now unnecessary check with the …

fix(#964): Allow "." in variable names + make error message more consistent

---

packages/bruno-app/src/components/Documentation/index.js

This PR sets the `font` property (previously missing) on the Docs editor to follow the value set in the preferences window.
**Associated Issue:** #1131

fix(web): documentation editor font not following preferences value

---

packages/bruno-electron/src/ipc/network/axios-instance.js
packages/bruno-electron/src/ipc/network/index.js

This PR fix #124, by correctly handling : 
- localhost subdomains (*.localhost) even if they are not inside a hosts file
- trying ipv6 localhost first, like in google chrome.
(see RFC: 6761 section 6.3 https://tools.ietf.org/html/rfc6761#section-6.3).
This fix is heavily inspired by how PostmanRuntime is handling it (https://github.com/postmanlabs/postman-runtime/blob/develop/lib/requester/core.js#L433),  their handling is even more complex by overriding DNS lookup of node (https://github.com/postmanlabs/postman-runtime/blob/develop/lib/requester/core.js#L285).
I did some tests on windows & linux, and this PR correctly fix subdomains, or ipv6 issues.
If you have any comments on this PR let me know !

fix(#124): resolve all *.localhost to localhost, and fix ipv6 issue

---

package-lock.json
packages/bruno-app/package.json
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/GenerateCodeItem/CodeView/StyledWrapper.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/GenerateCodeItem/CodeView/index.js

I added the copy to clipboard feature

Add copy to clipboard icon

---

package-lock.json
packages/bruno-app/src/components/Sidebar/Collections/Collection/CloneCollection/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-electron/src/ipc/collection.js

Issue: [Feature]-collection clone or duplicate feature/option is not available #156
I have created clone collection functionality. I just created new folder at user location and copied previous collection files.
Here is demo video of that.
[Screencast from 11-12-23 02:11:38 AM IST.webm](https://github.com/usebruno/bruno/assets/76739180/f8105f8e-b067-4aa2-856c-b9ec6b3e6e7a)

clone functionality in collection

---

packages/bruno-electron/src/app/watcher.js

This PR resolves #159.
In watcher.js:415, changed the code like following to save and open collection on wsl2 fs.
```
usePolling: watchPath.startsWith("\\\\") ? true : false,
```
after changing the code above, the bruno works fine. (see the following picture)

set the polling mode based on path type to resolve wsl2 file system issue.

---

packages/bruno-app/src/components/Preferences/Theme/index.js
packages/bruno-app/src/providers/Theme/index.js

Added a "System" theme options, which means "Sync with system". Does not break explicitly specified Light and Dark options.
Resolves #731 
| Sync with system dark | Sync with system light |
|--|--|
|![image](https://github.com/usebruno/bruno/assets/9428948/cf1b358b-f3dd-4b4b-ae62-1429257af8fc)|![image](https://github.com/usebruno/bruno/assets/9428948/adeebb44-7a1e-4093-83c8-9f2208244405)|

feat(#731): support theme sync with system

---

packages/bruno-app/src/components/RunnerResults/index.jsx

Fixing issue #1210 
Improve mapping function : 
- `return null` when item no longer exists
- add `.filter(Boolean)` to remove previous null values
https://github.com/usebruno/bruno/assets/64689165/13dc8e57-80f5-4478-83fc-32f4e69a0d80

bugfix(#1210): prevent collection run mapping on deleted items

---

packages/bruno-app/src/components/RequestTabs/RequestTab/ConfirmRequestClose/index.js

Just fixed a typo in the close confirmation modal
Closes: https://github.com/usebruno/bruno/issues/1265

Fixed typo in modal

---

packages/bruno-app/src/components/Preferences/General/index.js
packages/bruno-app/src/providers/ReduxStore/slices/app.js
packages/bruno-electron/src/ipc/network/index.js
packages/bruno-electron/src/store/preferences.js

- Allow to add custom CA Certificate and allow to have a verified SSL/TLS connection without disabling SSL/TLS Verification. (#1080, #211 ).
- Set KeepAlive to true in the httpsAgent that should fix `Error: socket hang up` seen in #211, this value was changed to true by default on Node v19+ (https://github.com/nodejs/node/pull/43522)
UI changes :

feat: add custom CA Certificate preference

---

packages/bruno-app/src/components/Sidebar/GoldenEdition/index.js

changed colors of golden edition modal in dark mode
previous:
dark mode:
light mode:
now:
dark mode:
light mode:

fix dark mode colors of golden edition modal

---

package-lock.json
packages/bruno-electron/package.json
packages/bruno-js/package.json
packages/bruno-js/src/runtime/script-runtime.js
packages/bruno-js/src/runtime/test-runtime.js

Replaced `vm2` with `@n8n/vm2` a fork of vm2 that fixes 2 security vulnerabilities.
Closes #263 #922
---
PSA: While this closes sandbox escape vulnerabilities, you should always make sure not to run random/untrusted scripts. Bruno allows script's to access `node:fs` and other modules (If enabled in bruno.json) so be careful with what you run.

fix(#263): Replace vm2 with fork of vm2 to fix security issues

---

packages/bruno-js/src/utils.js

Closes #1000
Convert too long numbers into a string for collection vars so they don't get changed.
Before:
After:

fix(#1000): Convert too long numbers into String for collection vars

---

packages/bruno-cli/src/runner/interpolate-vars.js
packages/bruno-electron/src/ipc/network/interpolate-vars.js
packages/bruno-electron/tests/network/interpolate-vars.spec.js

Closes #1143, Closes #1148, Closes #1150, Closes #1367 & Closes #1321
Fixes changes introduced by PR #971
Now we add `[]` only to variables within a string & only to variables which are not process environment variables (those that don't start with `process.env.`).
I also added this feature to the CLI.
|Before|After|
|------|------|
|<video src="https://github.com/usebruno/bruno/assets/30027205/1d439bac-0611-4b03-b7ca-38b3cd453c54"></video>|<video src="https://github.com/usebruno/bruno/assets/30027205/948852fc-e9eb-4eb7-9056-ce5137817d87"></video>|
|<video src="https://github.com/usebruno/bruno/assets/30027205/8f566262-4bdc-4595-9714-0d94a04a47ea"></video>|<video src="https://github.com/usebruno/bruno/assets/30027205/9167747d-7dc0-4c95-bdca-8bb6ac0f4c04"></video>|
|<video …

fix(#1143): Fix PR #971 - Use literal segments only for env/collection variables + Add to CLI

---

packages/bruno-app/src/components/CodeEditor/index.js

Added `bru.setNextRequest(nextRequest)` into the hint words list. After #534 was closed, the new method of the Bru object wasn't added to the hint words list inside the desktop application. In this PR I'm adding it and probably will update the documentation on the website. If it wasn't for me exploring the discussion I wouldn't discover this very useful functionality.
Closes #1442 
Usage:

[Feature] Added bru.setNextRequest into the hint words list

---

packages/bruno-app/src/components/Environments/EnvironmentSelector/index.js
packages/bruno-app/src/components/Environments/EnvironmentSettings/EnvironmentList/EnvironmentDetails/index.js
packages/bruno-app/src/components/Environments/EnvironmentSettings/EnvironmentList/index.js

Fix overflow of environment name on environment dropdown and environment selector modal
Related Issue: #1459 #1458 
before:
after:

style: overflow of environment name fix

---

packages/bruno-cli/src/runner/run-single-request.js
packages/bruno-electron/src/ipc/network/index.js

Fixed ignored SSL verification and client certificates configuration when using SOCKS proxy

---

docs/readme/readme_de.md
docs/readme/readme_es.md

I was reading the docs in german and in english and then noticed that in the german version there are less language links than in the english version. As such I fixed it for both german and spanish, as I speak these languages.
closes #1251 

docs: Make german and spanish readme link to the same set of languages as the english readme

---

packages/bruno-app/src/utils/url/index.js

fixes: #1363 
Current behaviour: 
Currently, bruno incorrectly strips off a query param if the `value` or `name` for the same is empty/missing
this has been fixed with this PR
New behaviour:
if query param `Name` field is not empty, append the same in the URL (remove check for value to be present)
if query param `Name` is missing, do not append it to the URL
https://github.com/usebruno/bruno/assets/13575704/4405f2d1-6c66-4ffe-a124-25cd9e5d6d40

fix(#1363): add query param even when value is missing

---

packages/bruno-app/src/components/FilePickerEditor/index.js
packages/bruno-app/src/components/RequestPane/MultipartFormParams/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/index.js
packages/bruno-cli/src/runner/prepare-request.js
packages/bruno-cli/src/runner/run-single-request.js
packages/bruno-electron/src/ipc/collection.js
packages/bruno-electron/src/ipc/network/index.js
packages/bruno-electron/src/ipc/network/prepare-request.js
packages/bruno-electron/src/utils/filesystem.js
packages/bruno-lang/v2/src/bruToJson.js
packages/bruno-lang/v2/src/jsonToBru.js
packages/bruno-schema/src/collections/index.js

This PR attempts to implement Multipart Form Data file uploads, as discussed in https://github.com/usebruno/bruno/issues/195.
I am new to this framework and have referred to the work done in https://github.com/usebruno/bruno/pull/258 and https://github.com/usebruno/bruno/pull/558 for guidance.
In the .bru file, I used a `|` to separate different files, considering that it is a forbidden character on both Windows and Linux.

feat: Multipart Form Data file uploads

---

packages/bruno-app/src/components/CollectionSettings/Info/index.js
packages/bruno-electron/src/app/collections.js
packages/bruno-electron/src/app/watcher.js
packages/bruno-electron/src/ipc/collection.js

This PR resolves #1496 by enhancing the `bruno.json` collection configuration file with a new property named `ignore` allowing to specify a list of path fragments which should be excluded when loading a collection.
For instance :
```json
{
"version": "1",
"name": "Sample Collection",
"type": "collection",
"ignore": [
".idea",
".vscode",
"Test/Test2"
]
}
```
Collection creation behavior has also been updated so that default exclusions initially handled in the code (_node_modules, .git_ folders) are now written by default in the collection configuration file.
Opening legacy collections will work as expected as default exclusions will be applied if no exclusion configuration can be found.
The collection info tab has been updated in order to display the list of excluded path items
- [ X] …

feat(#1496) Allow ignoring path fragments from the collection configuration file

---

packages/bruno-app/src/utils/curl/curl-to-json.spec.js
packages/bruno-app/src/utils/curl/parse-curl.js

fix(1548): correct import of escaped curl string

---

packages/bruno-electron/src/ipc/network/prepare-request.js

Resolves #1552
Before:
Window becomes unresponsive and js heap runs out of memory.
https://github.com/usebruno/bruno/assets/23408784/5405f796-2c61-44c3-b412-e69c3561414d
After:
https://github.com/usebruno/bruno/assets/23408784/ec4d03e7-4bc1-4ed5-8631-22ddfae7bde1

fix(#1552): Fixed file uploads performance issues

---

contributing.md
packages/bruno-app/src/components/RequestTabs/RequestTab/ConfirmRequestClose/index.js

The problem was that the ConfirmRequestClose wasn't passing the `handleCancel` prop to Modal.
Closes: #1573

[Fix] Crash when closing confirmation modal

---

packages/bruno-cli/src/runner/prepare-request.js
packages/bruno-cli/src/runner/run-single-request.js

We can upload files using the Bruno GUI as Multipart Form data, but we can't do it using the CLI. This means you can't use it in CI pipelines because it doesn't have a GUI. This pull request incorporates this feature into the Bruno Command Line Interface.

feat(#1579): Add file uploading support for CLI

---

packages/bruno-app/src/globalStyles.js
packages/bruno-app/src/themes/dark.js
packages/bruno-app/src/themes/light.js

Improved scrollbar styling for linux and windows
[scrollbar_styling.webm](https://github.com/usebruno/bruno/assets/159901171/22356698-84a0-45c4-9842-50fdfb1539d9)

feat(#BRU-7) - scrollbar styling for linux and windows

---

packages/bruno-app/src/components/RunnerResults/index.jsx

Adds runner output 'block level' scrolling
[Screencast from 14-02-24 09:32:53 PM IST.webm](https://github.com/usebruno/bruno/assets/159901171/de344f4d-c575-4ceb-941c-1d9fdb505f2c)

feat(#1575) - auto scroll runner output body during collection run

---

packages/bruno-app/src/components/CollectionSettings/Docs/index.js
packages/bruno-app/src/components/CollectionSettings/Script/index.js
packages/bruno-app/src/components/CollectionSettings/Tests/index.js
packages/bruno-app/src/components/Documentation/index.js
packages/bruno-app/src/components/RequestPane/GraphQLVariables/index.js
packages/bruno-app/src/components/RequestPane/RequestBody/index.js
packages/bruno-app/src/components/RequestPane/Script/index.js
packages/bruno-app/src/components/RequestPane/Tests/index.js
packages/bruno-app/src/components/ResponsePane/QueryResult/QueryResultPreview/index.js
packages/bruno-app/src/components/ResponsePane/QueryResult/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/GenerateCodeItem/CodeView/index.js

Fixes inconsistent code editor syntax colors for system theme
Before:
[system_theme_before.webm](https://github.com/usebruno/bruno/assets/159901171/666e4083-584a-4071-a21c-c53cc1060503)
After:
[system_theme_after.webm](https://github.com/usebruno/bruno/assets/159901171/9805c42e-dfae-4c44-a5ab-6e2c0a9350a3)

feat(#BRU-10) - codeeditor syntax colors for system theme

---

package-lock.json
packages/bruno-js/package.json
packages/bruno-js/src/runtime/script-runtime.js
packages/bruno-js/src/runtime/test-runtime.js
packages/bruno-js/tests/runtime.spec.js

Add the ajv-formats dependency in test and script runtimes to perform additional json validations with ajv such as date-time or uuid. See the complete list here : https://ajv.js.org/packages/ajv-formats.html#formats.
This solves #947.

feat(#947): set up ajv-formats in script and test runtimes

---

packages/bruno-electron/src/store/env-secrets.js
packages/bruno-electron/src/utils/encryption.js

This enables empty strings to be encrypted (fixes #1545).
As reported in #1545, it's not possible to use an empty value as a secret.
Current:
- when saving an empty string as secret this is in the end populated with `null` which then gets into the auth header
After:
- empty string can be saved as a secret and the value is as expected in the resulting auth header

fix(#1545): empty strings encryption

---

packages/bruno-app/src/components/RunnerResults/index.jsx

After styling changes:
[response_pane_scroll_behavior.webm](https://github.com/usebruno/bruno/assets/25679466/0bfcc5fa-bf1f-475c-ad81-63884dd1533e)

feat(#1575): make response pane in collection runner screen unaffected by scroll

---

packages/bruno-app/src/components/RequestTabs/RequestTab/index.js

This feature was shared first by [Sahilm416](https://github.com/Sahilm416) - [PR](https://github.com/usebruno/bruno/pull/586). But the code is like deprecated. This is a amazing feature that will improve UX of all of bruno's users!
Closes [485](https://github.com/usebruno/bruno/issues/485)

feat: add middle mouse button click to close tab

---

packages/bruno-electron/src/ipc/network/oauth2-helper.js

In some cases the authroization url may already contain some query parameters expected by the specific applicaiton, in which case oauth2 authorization request specific parameters should be appended to the list. Previous implementation assumed no query component in the authrization URI.
Fixes #1683

Fix #1683 allow OAuth2 authorizationUrl with user provided query parameters

---

packages/bruno-app/src/components/Welcome/index.js

Hey! Stumbled upon the project, love the idea.
This is a _very_ minor contribution, but my OCD kicked in when I saw those uneven margins 😅 
Current:
Fix:

Fix margin between items in Welcome > Links

---

packages/bruno-cli/examples/report.html
packages/bruno-cli/src/commands/run.js
packages/bruno-cli/src/reporters/html-template.html
packages/bruno-cli/src/reporters/html.js
packages/bruno-cli/tests/reporters/html.spec.js

Add a HTML reporter : 
```
bruno run request.bru --output results.html --format html
```
The report describes each request and response, with full details of assertions and tests.
See example : https://github.com/trusta/bruno/blob/feat/html-report/packages/bruno-cli/examples/report.html
There are screenshots one the associated issue : https://github.com/usebruno/bruno/issues/1659

feat(#1659): add html reporter for cli

---

packages/bruno-cli/src/commands/run.js
packages/bruno-cli/src/runner/interpolate-vars.js
packages/bruno-cli/src/runner/run-single-request.js

The two github issues that are being closed with this PR did not contain descriptions of the underlying (small) issues in the CLI code. Here's more context:
1. The CLI code was not interpolating the AWS-centric values. Now it is.
1. When running a folder via command line, the post-request script of request 1 wants to edit the runtime environment of the Bru object that the CLI instantiated. The environment object that was passed into the post-request script function was correctly being modified, but was not affecting the runtime environment for the folder.
This PR address both of those issues.
Please see …

CLI fixes for aws and environment modifications

---

packages/bruno-app/src/components/RequestPane/GraphQLRequestPane/index.js

Related to #1822
I fixed the issue making the text scheme theme incorrect on dark mode in Windows.
Here is the before :
Here is the after : 

fix: system theme in dark mode

---

packages/bruno-app/src/components/SingleLineEditor/StyledWrapper.js

When I working on dark-mode, text selection at SingleLineEditor it's not eye friendly. This is class component and cannot use `useTheme`, so I made small change to provide better text selection on dark or light mode.
| Before      | After |
| ----------- | ----------- |
| <img width="1381" alt="image" src="https://github.com/usebruno/bruno/assets/13098072/d8cddd26-8160-4e97-8ecc-d562a632e647"> <img width="1381" alt="image" src="https://github.com/usebruno/bruno/assets/13098072/27afe5be-b9e6-4d72-845d-eb85db383043">    | <img width="1381" alt="image" src="https://github.com/usebruno/bruno/assets/13098072/c4f14be9-65c3-4ef8-8305-2aaaf5d49a8e">  <img width="1381" alt="image" src="https://github.com/usebruno/bruno/assets/13098072/32e7bfca-a5b6-4542-af7f-9086ed04a752">    |
Note: Keeping the …

fix(ux): better text selection implementation on dark-mode

---

packages/bruno-app/src/components/ResponsePane/QueryResult/QueryResultPreview/index.js
packages/bruno-app/src/components/ResponsePane/QueryResult/index.js
packages/bruno-electron/src/index.js

Any audio and video response can be now be previewed.
Here is screenshot for video preview.

feat(#1839): Add Audio and Video Preview

---

packages/bruno-app/src/components/Notifications/index.js
packages/bruno-app/src/components/Sidebar/index.js

Add native tooltips to the items at the bottom of the sidebar.
See #1832

feat: Add tooltips to sidebar footer

---

packages/bruno-app/src/components/Preferences/General/index.js
packages/bruno-app/src/providers/ReduxStore/slices/app.js
packages/bruno-electron/src/ipc/network/index.js
packages/bruno-electron/src/store/preferences.js

In Bruno when specifying a custom certificate authority certificate, so connections to servers using privately signed certificates can be established securely, the Node.js default truststore is discarded. Therefore, connections to systems using officially signed certificates cannot be established any more as their root CAs are no longer part of the configuration.
While you could add the official root CA certificates to the file that contains your custom CA certificate, this is a tedious job and it is more convenient to tell Bruno directly to either augment or replace the default truststore with the custom CA certificates.
Therefore, default truststore is in place. No need to allow for a choice. Checkbox "Keep default CA Certificates" is disabled.
Checkbox "Keep default CA Certificates" is …

Allow to keep the default truststore, when using a custom CA (#1080)

---

packages/bruno-electron/src/ipc/network/oauth2-helper.js

As per [RFC 7636: Proof Key for Code Exchange](https://www.rfc-editor.org/rfc/rfc7636#page-8) we should expect code verifier to be at least 43 characters after URL encode. Current implementation gives only 32.
Fixes #1793

Fix OAuth2 code verifier too short (#1793)

---

packages/bruno-electron/src/ipc/network/authorize-user-in-window.js

Redirects during OAuth2 authorization code flow are only identified through a rather broad regex match for `code` in the redirect uri. The authorization process will fail for authorization servers offering a "multi-step" authorization that include intemediate redirects casually containing the keyword `code` in their uri.
This change checks the redirect for the distinct `code` query paramter [as defined in the RFC](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2)
Fixes https://github.com/usebruno/bruno/issues/1778

Check oauth2 authorization code redirect for exact 'code' query parameter

---

packages/bruno-electron/src/ipc/network/oauth2-helper.js

OAuth2 configuration should allow empty `scope` or `Callback URL` fields, as these are optional.
Fixes #1797

Fix: OAuth2 Authorization Request OPTIONAL parameters are required by bruno

---

packages/bruno-app/src/components/CollectionSettings/Auth/index.js
packages/bruno-app/src/components/CollectionSettings/ClientCertSettings/index.js
packages/bruno-app/src/components/CollectionSettings/Headers/index.js
packages/bruno-app/src/components/CollectionSettings/Info/index.js
packages/bruno-app/src/components/CollectionSettings/Presets/index.js
packages/bruno-app/src/components/CollectionSettings/ProxySettings/index.js
packages/bruno-app/src/components/CollectionSettings/Script/index.js
packages/bruno-app/src/components/CollectionSettings/Tests/index.js
packages/bruno-app/src/components/CollectionSettings/index.js

I've added descriptions to each of the panels in CollectionSettings for better user education.  Furthermore, I've also made the UI more consistent across the panels. You'll notice in the provided video that the location of the description for each tab are now all on the same line, giving a smoother feeling to transitions.
Resolves #2030 
https://github.com/usebruno/bruno/assets/18120837/7ec1286e-6d0b-4010-98d1-4c73dc70e54f

feat: Add descriptions for each panel in CollectionSettings

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/RenameCollectionItem/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js

Small enhancement, to make sure user doesn't lose their unsaved changes while renaming the request.
Saving unsaved request changes before renaming the request
Issue: #1462

feat: save unsaved request changes before renaming

---

packages/bruno-app/src/utils/exporters/postman-collection.js

When exporting a postman collection, the app bombs with this error:
Fixes https://github.com/usebruno/bruno/issues/1943
This PR accesses the properties safely, so that the app doesn't crash

Fix Postman Export

---

.github/workflows/tests.yml
packages/bruno-app/src/components/Sidebar/ImportCollection/index.js
packages/bruno-app/src/components/Sidebar/ImportCollectionLocation/index.js
packages/bruno-app/src/providers/Theme/index.js
packages/bruno-app/src/utils/importers/postman-collection.js

- fixes for the `prettier` issues
- replaces the `dorny/test-reporter@v1` with a slightly better `EnricoMi/publish-unit-test-result-action@v2`
- results are always visible in actions run summary
- does not publish results on PRs from forks
- does not require a bunch of elevated privileges
Fixes #2042.

fix: resolve build issues

---

package-lock.json
package.json
packages/bruno-app/src/components/RequestPane/RequestBody/RequestBodyMode/index.js

#1933  Description
Changes to address issue #1996 
Replace usage of jsonBigint with lossless-json for the Prettify json functionality.
Behaviour after Prettify is as expected, with all data preserved:

Fix: Replace jsonBigint with lossless-json

---

.github/workflows/release-snap.yml

Publish to SnapCraft use checkout v3 to download git repository but this version use node JS 16 and this version is [deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).
I have bump checkout actions to [v4](https://github.com/actions/checkout/releases/tag/v4.0.0) and not setup node actions because I have see you use node JS 18.

Fix error in actions about older node JS version

---

packages/bruno-electron/src/ipc/network/authorize-user-in-window.js

This changes fix an issue which happens during authorization process of OAuth2.0 with authorization code when loading the authorize user window of IdP which contain redirects. This redirects cause the `window.loadUrl(url)` function to throw an error due that the original requested page was not completely loaded. 
https://github.com/usebruno/bruno/blob/1349a7975082e2afa64f4cc3b1c2d0d884991b4b/packages/bruno-electron/src/ipc/network/authorize-user-in-window.js#L75-L80
Such behaviour is explained on https://github.com/electron/electron/issues/17526 and https://github.com/electron/electron/issues/27574. Insomnia also faced this as they reported on this issue https://github.com/Kong/insomnia/issues/5926
Current error:
Fixes: #1920

fix(#1920): Ignore redirect abortion emmited by loadUrl

---

packages/bruno-app/src/components/VariablesEditor/index.js

Due to changes in https://github.com/usebruno/bruno/pull/650 collection variables would be passed as an object but were expected to be an array. Collection variables are now converted to an array.
Fixes: #1940
---
Also, we should later remove the `Show secret variable values` button for Collection.

fix: Collection variable viewer

---

packages/bruno-electron/src/app/watcher.js

fixes #1928 
I have changed the order of relative and normalize operations.
Screen before:
Screen after:
**Someone please test it on different environment like Linux or Mac, please.**
- [ x] **The pull request only addresses one issue or adds one feature.**
- [ x] **The pull request does not introduce any breaking changes**
- [ x] **I have added screenshots or gifs to help explain the change if applicable.**
- [ x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [ x] **Create an issue and link to the pull request.**

fix: Folders are not ignored

---

packages/bruno-app/src/components/Modal/StyledWrapper.js

Fixes https://github.com/usebruno/bruno/issues/1935
I've adjusted the modal z-index to ensure that underlying components do not overlap the modal. This change ensures that the prettier button in a POST body no longer overlaps modal windows.

Fixes #1935 - Underlying components no longer overlap modals

---

readme.md

[Issue](https://github.com/usebruno/bruno/issues/1924)
Since all Bruno releases are 64bit, there is no reason to skip this argument. Without it, apt gives a warning on every run: `N: Skipping acquire of configured file 'stable/binary-i386/Packages' as repository 'http://debian.usebruno.com bruno InRelease' doesn't support architecture 'i386'`
before:
after:

Fix sources.list.d deb: make 64bit explicit to avoid warning

---

packages/bruno-electron/src/ipc/network/prepare-request.js

Empty headers (in request or in collections) are ignored to prevent sending request error. (https://github.com/usebruno/bruno/issues/1898)

fix(#1898): Ignore empty headers to prevent sending request error

---

packages/bruno-app/src/providers/App/useIpcEvents.js

In the second if statement, an attempt is made to use the variable message, but this variable is not defined. Instead, the error variable should be used.

Fix variable name error

---

packages/bruno-schema/src/collections/index.js

pkce is now `false` by default to prevent save errors
Closes: #2070

fix: pkce validation error

---

packages/bruno-electron/src/ipc/network/authorize-user-in-window.js

The browser used for user authentication in OAuth2 Access Token flow is not following user preferences to disable SSL/TLS Certificate verification or to trust custom CA Certificate. As a result completing OAuth2 flow that requires login with web browsers is impossible with local environments using self-signed certificates.
With this change, the certificate errors may be optionally ignored based on said user preference.
Fixes #1684 in most part. What this PR does not fix is making it possible for browser session to trust user specified custom CA - or more generally using the same request configuration (Proxy, mTLS, etc) - but in my eyes ignoring certificate-erros entirely will fix 99% of problems of users having to work in unsecure test environments.

fix: Oauth2: Apply TLS Certifcate valiadation preference to accessing Auth and Token URLs

---

packages/bruno-app/src/components/CollectionSettings/ClientCertSettings/index.js
packages/bruno-app/src/components/CollectionSettings/ProxySettings/index.js
packages/bruno-app/src/components/Preferences/ProxySettings/index.js

Password inputs should be hidden with the HTML password type. Added them for the proxy and the client cert settings.
Fixes issue: https://github.com/usebruno/bruno/issues/1886
Before
After

fix: use html password type for password and credential inputs

---

packages/bruno-app/src/components/CollectionSettings/ClientCertSettings/StyledWrapper.js
packages/bruno-app/src/components/CollectionSettings/ClientCertSettings/index.js
packages/bruno-app/src/components/CollectionSettings/ProxySettings/index.js
packages/bruno-app/src/components/Preferences/ProxySettings/index.js

Input 'password' in ProxySettings (Preferences) can be toggled to be visible or not. The button can be clicked to show or hide input values, providing convenience and simplicity to the design:
The feature is present in 'Preferences' and 'Settings' (Collection Settings).
Thanks!

feat: toggle password visibility

---

packages/bruno-app/src/components/Sidebar/ImportCollection/index.js

This PR uses the `key` of the `options` object in import collection to suppress the unique key prop warning.
Fixes issue #2078
Screenshot of the console after the changes (note the lack of a warning):

flx: add unique key prop to ImportCollection options

---

packages/bruno-app/.prettierrc.json
packages/bruno-app/src/pages/ErrorBoundary/index.js
packages/bruno-electron/src/ipc/collection.js

This PR fixes the annoying blank screen in the event of an uncaught error which left the user with no option other than force quit. With this fix, options to return to the App and Force Quit is added.

fix: error boundary adding return-to-app and force-quit options

---

packages/bruno-app/src/components/CodeEditor/index.js

Fixes #2087 
This change hides the autocomplete popup (and keeps it hidden)  when `Escape` is pressed. Cursor can freely navigate  afterwards.
**Before**
[Screencast from 2024-04-15 22-08-56.webm](https://github.com/usebruno/bruno/assets/1665841/af147180-4880-4ab0-acce-8b423831de85)
**After**
[Screencast from 2024-04-15 21-58-09.webm](https://github.com/usebruno/bruno/assets/1665841/d31a4736-6837-4c7f-bb89-fb61fd1ef974)

bugfix: hide autocomplete on escape keyup

---

packages/bruno-app/src/utils/collections/index.js

Save and Save all not working while there is unsaved json body fixed
resolves: #2130 
before:
https://github.com/usebruno/bruno/assets/76877078/1e273d6b-da3e-4af1-ae56-41ed7a65f7ea
after:
https://github.com/usebruno/bruno/assets/76877078/d2c05aab-d0c9-454a-914a-902bd29d3881

fix: save button on confirm close popup not working

---

packages/bruno-cli/src/runner/prepare-request.js

Fixes issue introduced in #1667 - None means None 
Now also inherit means inherit
fixes #2206 and unit tests

Fix: CLI Test Runner ignores auth:"inherit" in requests (#2206)

---

packages/bruno-app/src/utils/importers/translators/index.spec.js
packages/bruno-app/src/utils/importers/translators/postman_translation.js

1. This PR allows translation of additional Postman specific scripts.
- `pm.response.json()` &rarr; `res.getBody()`
- `pm.environment.has("xyz")` &rarr; `bru.getEnvVar("xyz") !== undefined && bru.getEnvVar("xyz") !== null`
- `pm.expect( ... )` &rarr; `expect( ... )`
2. Tests to cover the above scenarios
3. Fix an incorrect regex in the translation script
- `'pm.response.to.have\\.status\\('` &rarr; `'pm\\.response\\.to\\.have\\.status\\('`
Fixes #1973

feat: allow translation of more postman scripts

---

packages/bruno-app/src/components/Sidebar/ImportCollectionLocation/index.js
packages/bruno-app/src/components/Sidebar/TitleBar/index.js
packages/bruno-app/src/components/Welcome/index.js
packages/bruno-app/src/utils/importers/postman-collection.js
packages/bruno-app/src/utils/importers/translators/index.spec.js
packages/bruno-app/src/utils/importers/translators/postman_translation.js

Following changes from #2031 : improved ui feedbacks to display failed translations while importing a postman collection into bruno

Feat/UI feedback : Visual + console feedback for failed postman translated imports

---

packages/bruno-electron/src/index.js

resolves: #2152
The error message was:
_Refused to load the image 'http://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png' because it violates the following Content Security Policy directive: "img-src 'self' blob: data: https:"._
Electron was not allowing to load images over "http", only "https" was allowed.
I think it's reasonable to allow it (for images only).
https://github.com/usebruno/bruno/assets/139650490/ecaa04cd-ba32-4c75-8ae5-4ee961b3bb9f

bugfix(#2152): Docs not support "http" markdown image

---

docs/readme/readme_ar.md
docs/readme/readme_bn.md
docs/readme/readme_cn.md
docs/readme/readme_de.md
docs/readme/readme_es.md
docs/readme/readme_fr.md
docs/readme/readme_it.md
docs/readme/readme_ja.md
docs/readme/readme_kr.md
docs/readme/readme_pl.md
docs/readme/readme_pt_br.md
docs/readme/readme_ro.md
docs/readme/readme_ru.md
docs/readme/readme_tr.md
docs/readme/readme_ua.md
docs/readme/readme_zhtw.md
readme.md

Fixes the link under the CI badge so it points to the builds history instead of 404. Also fixed badge rendering in many langages

Fix: Update README links to CI tests and status badge

---

packages/bruno-electron/package.json
packages/bruno-electron/src/ipc/network/index.js
packages/bruno-tests/src/echo/index.js

Description: decoding response body based on the content-type charset value

fix(#2367): handle response body decode

---

packages/bruno-electron/src/ipc/network/authorize-user-in-window.js
packages/bruno-electron/tests/network/authorize-user.spec.js

Fixes #2147
In an Authorization code flow, there may be multiple intermediate redirects before reaching the final one which matches the callback URL and has a code in the query params.
We should wait until we see a redirect URI that matches both the conditions. This fixes the issue where, when a redirect contains `code` as a query param but is not the final one (i.e., is not to the callback URL) an error is thrown saying the callback URL is invalid.

fix: Check OAuth2 redirect URL for matching callback URL and authorization code in query parameters

---

packages/bruno-electron/src/ipc/network/index.js
packages/bruno-js/src/runtime/vars-runtime.js

fix #2005
- display post request variable evaluation errors in a toast, each individual variable error on a new line
- display the response body (was previously replaced by the an error "Error invoking remote method 'send-http-request': ..."

Feat: Catch post request variable evaluation errors

---

packages/bruno-app/src/components/Preferences/General/index.js
packages/bruno-app/src/providers/ReduxStore/slices/app.js
packages/bruno-cli/readme.md
packages/bruno-cli/src/commands/run.js
packages/bruno-cli/src/runner/run-single-request.js
packages/bruno-electron/src/store/preferences.js

Continuation of PR #1937, considering the changes proposed in that PR.
The change in feature #1863 did not cover the CLI feature of Bruno, `bru`. This feature adds that part and introduces a new command line option to `bru` CLI to control the way custom CA certificates are handled: replace _or_ extend the default truststore.
The new CLI option is called `--ignore-truststore` and documented in both synopsis and readme.
This new option only is in effect, if a custom CA certificate is specified via option `--cacert`.
At the same time, this change inverts the default handling of specifying custom CA certificates in the GUI. Previously, the default truststore was replaced completely, if custom CA certificates had been specified. Now specifying custom CA certificates results in augmenting the …

feature: Augment default truststore by default, optionally limit to custom CA certs

---

packages/bruno-app/src/utils/codemirror/brunoVarInfo.js
packages/bruno-common/package.json
packages/bruno-common/src/interpolate/index.spec.ts
packages/bruno-common/src/interpolate/index.ts

fixes #2227
Add option to compose env variables with recursion

feat: add recursive interpolate

---

packages/bruno-electron/src/ipc/network/index.js
packages/bruno-electron/src/ipc/network/interpolate-vars.js
packages/bruno-electron/src/ipc/network/prepare-request.js

bugfix(#2439)

---

packages/bruno-electron/src/ipc/network/oauth2-helper.js

The scope param is always passed (when according to the spec, it is optional).
The server responds with
{
"error": "invalid_scope",
"error_description": "Invalid scopes: "
}
Fixes: https://github.com/usebruno/bruno/issues/2446.

fix: Pass the scope conditionally for OAuth2 Password Credentials

---

packages/bruno-electron/src/ipc/network/index.js

It looks like there was regression with the graphql introspection query code that was preventing pre-request scripts from settings header values in the prepared request.
https://github.com/usebruno/bruno/issues/704
Using an example here, a pre-script that sets some authentication headers
This data now actually gets sent through to the backend
```
X-Mul-Nonce: xxxx
X-Mul-Timestamp: xxxx
X-Mul-Signature: xxxxx
```
So my (previously broken) introspection request now succeeds.

interpolate vars correctly in graphql introspection request

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/GenerateCodeItem/CodeView/index.js
packages/bruno-app/src/utils/codegenerator/auth.js

Fixes #1791
This PR add to Bruno the ability of generate code with Authorization headers of basic and bearer mode

fix: add authorization token to generate code

---

packages/bruno-cli/src/runner/prepare-request.js
packages/bruno-cli/tests/runner/prepare-request.spec.js
packages/bruno-electron/src/ipc/network/prepare-request.js
packages/bruno-electron/tests/network/prepare-request.spec.js

Request body json was not decommented if json parsing fails, which would happen if variables are not quoted.
Fixes usebruno#888

fix: decomment not working in json body

---

packages/bruno-cli/src/runner/run-single-request.js
packages/bruno-electron/src/ipc/network/index.js
packages/bruno-js/package.json
packages/bruno-js/src/bru.js
packages/bruno-js/src/interpolate-string.js
packages/bruno-js/src/runtime/assert-runtime.js

this is an extension of the pr #2234
~ updated the current interpolateString function in bruno-js to use the recursive interpolation function
~ added the processEnvVars to the assert runtime context

update interpolate function in bruno js

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/GenerateCodeItem/CodeView/index.js

Closes #2444 
When generating code for a request, `getEnvironmentVariables()` of CodeEditor was called with an undefined value, because props of CodeEditor did not contain "collection" in the specific case of being instantiated from CodeView.
I've added this collection var when creating the CodeEditor in CodeView.

Fix error when attempting to "generate code" of a request

---

packages/bruno-app/src/components/Environments/EnvironmentSettings/CreateEnvironment/index.js
packages/bruno-app/src/components/Environments/EnvironmentSettings/ImportEnvironment/index.js
packages/bruno-app/src/components/Environments/EnvironmentSettings/index.js
packages/bruno-app/src/components/Sidebar/ImportCollection/index.js
packages/bruno-app/src/utils/importers/postman-environment.js

Linked issue #2473 
**Rendering a modal on top of a modal is not a good practice**
This PR introduces : 
- Multiple files selection when importing environments
- Env modal, create env modal and import env modal **grouped** together
- "Go back" button to return to the env modal
- **Styling** in previously mentioned components
- Errors while importing corrupted or wrong postman envs
_New "no env" modal :_ 
_Create env in the same modal level :_
_Same for import env + styling :_

[Feature] : Bulk env import and UX/UI improvements

---

packages/bruno-electron/src/bru/index.js

Fixes broken resequenzing of Requests. The `seq` property is in the Top-Level of the JSON instead of inside `meta`.

fix(#2573): Fix broken resequenzing of requests

---

packages/bruno-electron/src/ipc/collection.js

When cloning a folder, requests and subfolders are cloned too, but not folder.bru files.
- [X ] **The pull request only addresses one issue or adds one feature.**
- [ X] **The pull request does not introduce any breaking changes**
- [ X] **I have added screenshots or gifs to help explain the change if applicable.**
- [ X] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [ X] **Create an issue and link to the pull request.**
#2593 
Suppose to have this structure. : 
```
.
├── MultiLevelDir
│   ├── FirstLevel
│   │   ├── SecondLevel
│   │   │   ├── Artist Finder 2.bru
│   │   │   └── folder.bru
│   │   └── folder.bru
│   └── folder.bru
├── bruno.json
└── collection.bru
```
Now, cloning the MultiLevelDir we get also folder.bru …

Cloning a dir now clone also folder.bru files recursively#2593

---

packages/bruno-cli/src/commands/run.js

We need to exclude folder.bru files when executing all requests in a directory (NOT recursively)
- [ X] **The pull request only addresses one issue or adds one feature.**
- [ X] **The pull request does not introduce any breaking changes**
- [X ] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [ X] **Create an issue and link to the pull request.**
#2584

Bruno CLI tries to execute folder.bru #2584

---

packages/bruno-app/src/components/Environments/EnvironmentSettings/EnvironmentList/index.js

minor fix for when there is single environment and user renames it, active environment is not updated to the renamed environment which causes error when user tries to update or delete the active environment.
before:
https://github.com/user-attachments/assets/3da6d45b-88fa-436d-9b3e-817ee38ff58e
after:
https://github.com/user-attachments/assets/b8d4d9cd-fe4b-48f4-b0b7-7884cee9b79c

fix: active enviroment not updated after rename when there is single enviroment

---

packages/bruno-app/src/components/Environments/EnvironmentSettings/EnvironmentList/index.js

Reverts usebruno/bruno#2640
Cause it's causing this bug!
https://github.com/user-attachments/assets/e76db461-1fa5-46e1-8c08-597744016ae2

Revert "fix: active enviroment not updated after rename when there is single enviroment"

---

packages/bruno-app/src/globalStyles.js

removed scrollbar style -- electron bump issue

scrollbar fix

---

packages/bruno-cli/src/runner/run-single-request.js
packages/bruno-electron/src/ipc/network/index.js
packages/bruno-js/src/runtime/test-runtime.js

Allow the use of bru.setNextRequest() at the test script level
#2155 

Allow bru.setNextRequest() on Test Scripts (#2155)

---

packages/bruno-app/src/providers/ReduxStore/slices/collections/index.js

This change resolves an issue when the runner execute the same request more than once. For example this happens when the request script sets the next request to itself. Before the changes the runner test results would look like this:
After this fix the result will show like this:

Fix test results when the same request is executed more than 1 time (#2522)

---

packages/bruno-app/src/components/SingleLineEditor/index.js

A refactor to improve readability.  Code readability is subjective so I'm raising this to see whether it's perceived as an improvement or not.
I'm working on a PR in this area of the codebase and the `codemirror` config takes up quite a lot of lines with repeated identical event handlers.  From my perspective naming the event handler functions and reusing them makes the code more readable as it draws the attention to the connection between the key combination and the action that's performed and takes the attention off the mechanism behind the action being performed.
Note: I haven't created an issue as it's just a refactor, if an issue is needed I'm happy to create one.
- [] **Create an issue and link to the pull request.**
Note: Keeping the PR small and focused helps make it easier to …

Refactored handlers into reusable functions for readability.

---

packages/bruno-app/src/utils/curl/parse-curl.js

Don't exclude the cookies from the request headers if they are in the headers of the curl command. 
resolves #1747 

don't exclude cookies from request headers when importing from curl

---

packages/bruno-app/src/components/Sidebar/NewRequest/index.js

For some reason, clicking enter on New Request modal doesn't submit the form, I noticed that it happens even on other modals if there are more than 1 input fields. so just added a keydown event to submit the form whenever user clicks "enter"

fix: enter key not submitting new request form

---

packages/bruno-app/src/utils/codegenerator/har.js

sets the content-type header during code generation also handles missing request body modes
This kind of logic of turning body mode into content-type is duplicated in at least more than 2 places. Seems like it would be a good candidate for a shared util.
Closes #2488

set content-type header during code generation

---

.github/workflows/tests.yml

Enable npm package caching on the tests workflow

chore: add cache to tests workflow

---

packages/bruno-lang/v2/src/jsonToBru.js

- fixed #2699
- If there is undefined value in imported json item, type error occurs.
```
Error occurred in handler for 'renderer:import-collection': TypeError: Cannot read properties of undefined (reading 'includes')
```
- I fixed it by adding optinal chaing in `getValueString()` 

fix: type error in jsonToBru during import collection

---

packages/bruno-electron/src/ipc/network/prepare-request.js

This PR make sure that request headers and vars get picked up correctly when the request to be sent is in a draft state.
Closes #2627

fix: draft variables and headers

---

packages/bruno-app/src/components/CodeEditor/index.js

feat: https://github.com/usebruno/bruno/issues/1451
This PR enable users to exclude specific parts of the request through comments in a JSON payload interface.
https://github.com/user-attachments/assets/928b9aa2-759f-4645-bd3c-19c5f1979af9

feat: comment with keybinding (cmd + /) in JSON payload interface

---

packages/bruno-schema/src/collections/index.js
packages/bruno-schema/src/collections/requestSchema.spec.js

In #2117 it was discovered by @nicolasne that the `TRACE` method caused an issue on import, this is an attempt at adding it to the list of allowed methods.
`TRACE` is already supported in other OpenAPI Collection locations such as 
https://github.com/usebruno/bruno/blob/1e0c88a2916236b73017c2df01a6a85c414d7edf/packages/bruno-app/src/utils/importers/openapi-collection.js#L342-L347

Add TRACE to OpenAPI allowed methods during import

---

packages/bruno-app/src/themes/dark.js

Current `modal` component's `title` and `body` share the same background color. 
For better UX, it would be worth adding a slight shade to the `title` to differentiate between the `title` and `body` section. I have used the shade generator utility from https://mdigi.tools/color-shades/#303031
> Note that the `light` mode already has this subtle difference, so this PR is only applicable to `dark` mode.
The change is subtle but impact on user experience is substantial. 
Take a look at the screenshots before and after
**Before**
**After**

(feat) Add shade to modal header in dark mode

---

packages/bruno-app/src/components/RequestPane/QueryUrl/index.js
packages/bruno-app/src/components/SingleLineEditor/index.js

fixes #2802 
query url overflowing
before:
after:

fix: query url overflowing

---

packages/bruno-app/src/components/FolderSettings/Script/index.js
packages/bruno-app/src/components/FolderSettings/index.js

* Fixes the sizes of the `Pre-request` + `Post-request` inputs on the Folder Settings Panel
* Fixes the size of the `Test` tab input in the Folder Settings Panel
* I've aligned the styling of the container and the children with the equivalent components in `RequestPane`
Fixes #2796
Folder Settings Scripts Tab
(Before)
(After)
Folder Settings Test Tab
(Before)
(After)

fix: align folder settings pane + scripts with request pane

---

packages/bruno-app/src/components/Sidebar/NewRequest/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-app/src/utils/curl/curl-to-json.js
packages/bruno-app/src/utils/curl/index.js
packages/bruno-app/src/utils/curl/parse-curl.js

Seems like there was some ground work for this ability. This also opens the door for other auth types to be imported from cURL.
closes #2774

feat: add ability for cURL to import basic auth

---

packages/bruno-app/src/providers/Hotkeys/index.js

Shortcut that closes all tabs in the collection.

feat: add hotkey to close all tabs

---

packages/bruno-app/src/components/Welcome/index.js
packages/bruno-app/src/dictionaries/en.js
packages/bruno-app/src/dictionaries/index.js
packages/bruno-app/src/pages/_app.js
packages/bruno-app/src/providers/Dictionary/index.js

Currently constants are spread all over the codebase. 
However, going forward it would be a challenge to maintain these values.
Having dictionary would yield following benefits:
- All constants used in UI layer are housed together.
- These values can be reused at multiple places in the application thereby reducing duplication and enhancing consistency.
- Ability to add languages other than English `en` when needed.
- Ability to switch languages can be controlled via `Preferences`.
- Refactoring is easy as you need to make change only at one place.
I have used `Welcome` page to demonstrate its usage. …

feat: Add support for dictionary and use in Welcome page

---

packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js

- fix #2786
- Fixed an issue where query params and path params were not being added correctly in the `newHttpRequest()` called from the new request modal.
https://github.com/user-attachments/assets/5b09c4bf-5b3c-4208-8204-049bc258f6af
https://github.com/user-attachments/assets/bf17131d-f31a-42ac-aec0-45213af4ebe6
https://github.com/user-attachments/assets/01e700fa-66fd-48e6-97c7-00954138d410

fix: add path params on newHttpRequest

---

packages/bruno-app/src/components/Preferences/Support/index.js
packages/bruno-app/src/dictionaries/en.js

We recently merged [this PR](https://github.com/usebruno/bruno/pull/2819) to source the commonly used text from the Dictionary. This PR is about re-using the dictionary in the `Preferences->Support` component.
Refer the screenshots before and after the change:
---
---

feat: Reuse dictionary in preferences support page

---

packages/bruno-app/src/components/Sidebar/ImportCollectionLocation/index.js

fixes: #966 
**Issue:** There is an exception in the Import Collection feature with the following error message:
```
Error: Error invoking remote method 'renderer:import-collection': TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean (false)
```
**Changes Introduced:**
In this Pull Request, I have implemented a type check for the `location` variable in the Import Collection process. Specifically, the code now verifies if the `dirPath` is of type `string`. If `dirPath` is a string, it proceeds with the operation; otherwise, the Import Collection modal remains open for the user to select a valid path.
Here is the added code snippet for the type check:
```javascript
if (typeof dirPath === 'string') {
formik.setFieldValue('collectionLocation', …
```

Bugfix- Import blank directory Exception

---

packages/bruno-electron/src/ipc/network/oauth2-helper.js

Removes the "scope" parameter from token endpoint requests when using authorization_code grant.
With authorization_code grant the "scope" parameter isn't supported:
https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.3
fixes https://github.com/usebruno/bruno/issues/2814

fix: remove scope with auth code grant

---

packages/bruno-app/src/components/RequestTabPanel/RequestNotFound/index.js

I'm just removing classes that are duplicated in the RequestNotFound component.

fix: remove duplicate tailwind classes in RequestNotFound component

---

packages/bruno-app/src/utils/codegenerator/har.js

- fix #2849
- Fixed an issue, invalid file path was created when creating shell-curl code.
- In a function within the [httpsnippet](https://github.com/Kong/httpsnippet/blob/master/src/targets/shell/curl/client.ts#L133) library, append @ to the file path based on fileName.
- current
- after

fix: invalid file path in shell-curl

---

packages/bruno-app/src/components/RequestPane/HttpRequestPane/index.js

Closes https://github.com/usebruno/bruno/issues/2757
This PR adds an indicator (●) that the body, script or tests property of a request is configured (just like the number indicators on other properties) to quickly see what configuration has been made for a given request.

Feature: Visualize if request body, script or tests have content (#2757)

---

packages/bruno-app/src/components/ResponsePane/QueryResult/QueryResultFilter/index.js

Fixes #2534 
Using [Tailwind's pointer-events](https://tailwindcss.com/docs/pointer-events), fixes mouse events being ignored at the bottom of the response pane, caused by the response query filter.
Now is possible to scroll and click in this area.
[vokoscreenNG-2024-06-30_02-07-17.webm](https://github.com/usebruno/bruno/assets/15898277/d7312473-54a1-4198-9685-257a342b818f)

bugfix(#2534) Fix QueryResultFilter mouse events

---

packages/bruno-app/src/utils/importers/openapi-collection.js

Fixes [#2513](https://github.com/usebruno/bruno/issues/2513) to support path parameters when OpenAPI specification is imported.
It replaces all path placeholders enclosed in curly braces with colons when the OpenAPI spec is parsed.
**Before**
```
meta {
name: get -users--id-
type: http
seq: 1
}
get {
url: http://api.example.com/v1/users/{id}
body: none
auth: none
}
params:query {
~metadata: 
}
params:path {
id: 
}
```
**After**
```
meta {
name: get -users--id
type: http
seq: 2
}
get {
url: http://api.example.com/v1/users/:id
body: none
auth: none
}
params:query {
~metadata: 
}
params:path {
id: 
}
``` …

Fix path parameters when OpenAPI specification is imported (#2513)

---

packages/bruno-app/src/components/ResponsePane/index.js

Due to this changes https://github.com/usebruno/bruno/commit/4917f24b7cb02bbfae175fdc5079ed77a44fae2c
related to issue #1436 
response headers count logic was broken for showing headers count in the response pane, so I have updated it.
before:
after:

Response headers count logic update

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/RequestMethod/index.js

fixes #584 
The fix shorten the method name to only starting 3 characters which have length greater than 5
Below is the screenshot for how it looks

Shorten method name for OPTIONS and DELETE

---

packages/bruno-app/src/components/FolderSettings/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/index.js
packages/bruno-app/src/providers/ReduxStore/slices/tabs.js
packages/bruno-app/src/utils/tabs/index.js

Fixes: #2903 
The bug (issue #2903) is fixed by checking ```isFolderSettingsOpenedInTabs``` before opening a new tab
Before:
https://github.com/user-attachments/assets/d8204bdb-0289-4b15-87a8-14fd39d860c2
After:
https://github.com/user-attachments/assets/59c32eb6-dd5a-4448-a1bc-be9d9e59f17d

fix: multiple tab collection level settings

---

packages/bruno-app/src/utils/url/index.js

A non-parsable URL should be an acceptable state while the text is being typed. The parsing is  now aborted, without raising an error.
fixes #2652

fix: Failed to construct 'URL': Invalid URL everytime the URL is modified

---

packages/bruno-app/src/components/CollectionSettings/ClientCertSettings/index.js
packages/bruno-app/src/components/CollectionSettings/index.js

The UI for collection level certificates does not reveal which file is used for which domains, so the only way to make sure you are using correct keys is to remove and re-add them. Also, the paths to key and cert files are kept in bruno.json file as absolute paths, making it unsuitable for version control and sharing between users with various setups.
With this change, the paths picked with file picker are relative to current collection and displayed in the Client Certificates view of collection settings.
Note, the absolute paths are still supported, so collections using old format are not affected. 
fixes #2420
Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull …

feat: Store client certificate paths in collection settings as relative to collection and display them the UI.

---

packages/bruno-app/src/utils/common/index.js
packages/bruno-app/src/utils/common/index.spec.js

-----
While writing tests for the utility functions `relativeDate` and `humanizeDate`, I identified that humanizeDate will not always return the date it is given based on the user's timezone. This stackoverflow post explains this well: https://stackoverflow.com/questions/7556591/is-the-javascript-date-object-always-one-day-off/31732581#31732581
- This pull request adds tests for `humanizeDate` and `relativeDate` which are found here: `packages/bruno-app/src/utils/common/index.js`.
- It also adds a fix to `humanizeDate` to ensure it always returns …

Fix/2377  Fix humanizeDate so that it always returns the date it is passed

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/StyledWrapper.js

The PR addresses a minor style issue in the Collection Item component, specifically for the "Delete Request" button. This issue was introduced by the following [lines](https://github.com/usebruno/bruno/pull/2183/files#diff-14d7c357f3f7423edb8a6276671636a63bacf208c1e29c389e76678e569cf9efR43) in the [PR #2183](https://github.com/usebruno/bruno/pull/2183).
Before:
After:

Style: Delete button hidden in Light theme

---

packages/bruno-app/src/utils/url/index.js
packages/bruno-app/src/utils/url/index.spec.js

This PR fixes query parameter parsing from URL field. The '=' should be allowed within query parameter value. While first equals sign separates parameter name from its value, any subsequent occurrences are valid and should not be discarded.
Additionally in curent implementation the last query parameter value incorrectly contains what should be URI fragment (anything that follows #), which this PR also addresses.
fixes: #2124 
fixes: #2731
Before:
After:

fix: Issue with Parameters Passed in the URL(#2124)

---

packages/bruno-app/src/components/CodeEditor/index.js
packages/bruno-app/src/components/RequestPane/GraphQLVariables/index.js

Inspired by #526 and its follow-ups, this PR adds support for formatting code on the **GraphQL Variables tab**.
It equips the `CodeEditor` component with formatting capabilities (using `prettier`) and a button that's only rendered if consumers provide the `formattingOptions` prop, where an appropriate parser and potential prettier plugins can be specified.
This way the formatter can be re-used in other places down the line as described in #2265.

feat(#2265): Support GraphQL variables formatting

---

packages/bruno-app/src/utils/importers/openapi-collection.js

This PR updates the resolveRefs function to handle cases where spec or spec.components is undefined. The function now includes checks to avoid errors when spec is null or components is missing.
Issue link: https://github.com/usebruno/bruno/issues/2083
Sample openapispec to generate this in current implementation
```
openapi: 3.0.0
info:
title: API
version: 0.0.0
description: xxx
servers:
- url: http://localhost
description: Main production API server
paths:
'/v1':
get:
summary: xxx
description: dddddd
responses:
'200':
description: OK
content:
application/json:
schema:
type: object
properties:
key:
type: integer
nullable: true
example:
key: null
```

added validations for spec and ref

---

packages/bruno-electron/src/ipc/network/oauth2-helper.js

Some APIs don't like extraneous properties such as state. Avoiding passing that in unless it's set to a non-empty value.
Fixes https://github.com/usebruno/bruno/issues/3033.

Don't include state in OAuth 2 exchange flow

---

packages/bruno-app/src/components/RequestTabs/RequestTab/index.js

fixes: #3038 
In this PR, I implemented middle-click functionality for the `RequestNotFoundTab` and `SpecialTab`. 
Previously, PR #1649  introduced middle-click functionality for request tabs. Now, with this update, middle-click can be used to close any type of tab.
Before:
https://github.com/user-attachments/assets/55ea3405-4cd2-475e-a8e2-384621321e28
After:
https://github.com/user-attachments/assets/7cb026f7-6007-4aec-af5f-b369e8fbeffc

fix: middle button click to close - SpecialTab and RequestTabNotFound

---

packages/bruno-app/src/components/CodeEditor/index.js

As mentioned in https://github.com/usebruno/bruno/issues/3043 there are no word hints for the new methods _getFolderVar_ and _getCollectionVar_  which were introduced with #2963

fix: add hints of 'bru' object for 'getFolderVar' and 'getCollectionVar' methods

---

packages/bruno-app/src/components/Table/StyledWrapper.js

In the `Table` component created in PR #2641 for the `ReorderTable` component, the bottom border for the header inside the table was not properly handled. As a result, the bottom border was not visible when there were no values in the `Table`. In this PR, I have addressed the issue by adding the missing border.
Before:
After:

style: added bottom border for `Table` component

---

packages/bruno-js/src/bruno-response.js

Allows setting the response body from a script. Useful for when you e.g. want to base64 decode the response before displaying it.
Fixes usebruno#2441.

feat: Set response body function

---

packages/bruno-app/src/components/RequestPane/QueryUrl/index.js

Fixes: #2978
This PR fixes the cursor jumping to the start of the request URL bar when one deletes a whitespace character in the request URL bar. This was happening because the value was being trimmed every time the value was changed in the URL bar, which triggered the cursor to go to the starting. Now the request URL will only be trimmed when the request URL is being saved.
https://github.com/user-attachments/assets/e20e6fee-4862-4b80-8150-7bc21d6b5c79

fix: cursor jump to start

---

packages/bruno-app/src/components/RequestPane/QueryUrl/index.js

fixes: #2978 
- This implements a feature to restore the cursor position after the `URL` has been trimmed (When actively editing on the Query URL. 
- I have used `useRef` to access the cursor position and set it only after the `URL` has been trimmed.
Currently, this issue has been fixed by PR #3082  , but the required behavior is to trim the `URL` when it is actively changed. The previous PR did not add the capability to trim the `URL` on unsaved request runs. I believe both of these scenarios can be addressed with the merging of this PR.
Before:
https://github.com/user-attachments/assets/cb73c991-736c-4bb0-a033-6821499cfeb9
After:
https://github.com/user-attachments/assets/23ccd8b8-5eb7-4745-bd73-ad476d8af292

fix cursor position restoration after `URL` trimming

---

packages/bruno-app/src/utils/importers/postman-collection.js

Fix for #1300
In Postman, multiple requests in same folder can have same name. Current importer code is creating bruneRequestItems with same name and bruno doesn't allow multiple requests with same name in a given folder. **Which is causing only one of the original requests to be actually created and other requests with the same name are missing in imported collection in bruno.**
Appending "_<duplicate_count>" to conflicting request names within same folder.

Fix #1300 : Handling request name conflicts while importing postman V2 collections

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/RunCollectionItem/index.js

1. Updated the request count logic to only include http-request and graphql-request types using a new getRequestsCount function. Currently it is calculating the folders too.
2. Added conditional rendering to display a message when no requests are found and disabled the Run and Recursive Run buttons accordingly.
current implementation:
Updated design:

Improved Request Count Calculation and UI Handling in RunCollectionItem

---

packages/bruno-app/src/utils/url/index.js

This PR address #3067. The problem was when we create a new URL() with more than one env variable, it throws an error. But since bruno supports multiple environment variable, instead of throwing error, we try to split it directly and create path params.
- [ x] **The pull request only addresses one issue or adds one feature.**
- [x ] **The pull request does not introduce any breaking changes**
- [ x] **I have added screenshots or gifs to help explain the change if applicable.**
- [ x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [ x] **Create an issue and link to the pull request.**

#3067: handle multiple env vars

---

packages/bruno-cli/src/commands/run.js

Adding the ability to pass multiple reporters using `--format`. You can specify the output files using `--output.reporter`
Sample I ran on my machine:
`node ..\..\bruno-cli\bin\bru.js run --env Prod --output junit.xml --format junit --format html --format json --output.html html.html --output.json results.json`
Console output:
All 3 files were written:
Related to #2045

feat: Feature/cli support multiple reporters

---

packages/bruno-cli/src/utils/axios-instance.js
packages/bruno-electron/src/ipc/network/axios-instance.js

Fixes #3126 .
In previous release there was PR that forcibly sets user-agent header. It was done in request interceptors, so it cannot be changed when user wants different. 
So I changed code to set user-agent header when creating axios, and after it if user specifies this header, users header will be used, if not, Bruno default header will be used.
without user-set header:
with user-set header:

Fix: Allow to set custom user agent

---

packages/bruno-app/src/providers/Hotkeys/index.js

fixes: #2219 
This PR implements the logic for saving `collection-settings` using the `Ctrl+S` or `Cmd+S` shortcut. It allows users to save the `Docs` tab even in preview mode, thereby resolving the issue.

feat: add logic to handle saving collection settings on shortcut (preview mode)

---

packages/bruno-app/src/hooks/useFocusTrap/index.js

fixes: #2076 
This PR updates #3075 to improve focus management within the modal. It ensures that focus is restricted to elements within the modal when it contains at least one focusable element. The approach follows guidance from Stack Overflow to confine focus to internal elements only.
_This is the Reference to this specific implementation_: [Keep tabbing within modal pane only](https://stackoverflow.com/questions/14572084/keep-tabbing-within-modal-pane-only)
**Key Changes:**
- Added focus trapping within the modal to restrict focus to internal elements.
- Adjusted `tabindex` to hide non-focusable elements outside the modal.
- Set initial focus to the first focusable element within the modal.
- Implemented focus looping between the first and last focusable elements.
- Restored original …

feature/useFocusTrap: Support focusable tab cycles in `Modal` (Update of PR #3075)

---

packages/bruno-app/src/components/RequestPane/QueryUrl/index.js

A new button has been added to the query URL bar, positioned alongside the existing “Save” button. This button provides quick access to the code generation feature, allowing users to easily generate code snippets for their requests without navigating through additional menus.
Solves #3083 
https://github.com/user-attachments/assets/b718837a-9e61-4555-8d5c-12ee88de49ce

added generate code button in query url bar to increase its visibility

---

packages/bruno-app/src/components/RunnerResults/ResponsePane/index.js

~ in the runner results, the error message doesn't show in the response

fix: runner results response preview

---

packages/bruno-app/src/components/RequestTabs/RequestTab/index.js

~ the previous implementation only closed the tabs of requests at the root of the collection

fix: close saved tabs button issue

---

packages/bruno-cli/src/runner/interpolate-vars.js
packages/bruno-electron/src/ipc/network/interpolate-vars.js

As reported in #2760, if a URL has a trailing slash and also contains
path parameters then the original logic had a bug that would drop the
trailing slash.
This implements the fix proposed by @ThenTech.

Fix #2760: Path params trailing slash

---

packages/bruno-app/src/components/CodeEditor/index.js
packages/bruno-cli/src/runner/run-single-request.js
packages/bruno-electron/src/ipc/network/index.js
packages/bruno-js/src/bruno-request.js
packages/bruno-js/src/sandbox/quickjs/shims/bruno-request.js

extension of pr #3105
moving the getExecutionMode fn to `req` object instead of `bru` object
`req.getExecutionMode()`
values: standalone | runner | cli

feat: request execution mode

---

packages/bruno-app/src/components/Environments/EnvironmentSettings/RenameEnvironment/index.js
packages/bruno-electron/src/ipc/collection.js

fixes: #3198 
This PR fixes the issue where environments with only a case difference cannot be renamed (e.g., renaming `ProD` to `Prod`), which primarily affects macOS and Windows.
- The fix involves using the `safeToRename` utility function to check if the files are identical based on their existence, rather than just comparing their names.
- This approach is particularly useful for Unix/Linux systems, which support case-sensitive filesystems.
- For more detailed context, see: [Link](https://github.com/usebruno/bruno/pull/3171#issue-2541807340)
Before:
https://github.com/user-attachments/assets/c6225df7-7669-4d7e-b099-10b307aca4b6
After:
https://github.com/user-attachments/assets/65c47354-f460-487f-b1fe-80acbd77ae37

Bugfix/rename with same name for `Environments`

---

packages/bruno-app/src/components/CodeEditor/StyledWrapper.js

Refactor CodeMirror styling to remove glow outline around folded JSON

---

packages/bruno-app/src/providers/App/useIpcEvents.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-app/src/utils/collections/index.js
packages/bruno-electron/src/app/watcher.js
packages/bruno-electron/src/ipc/collection.js
packages/bruno-electron/src/store/ui-snapshot.js
packages/bruno-electron/src/store/ui-state-snapshot.js

~ ui-state-snapshot store for persisting selective ui states between app launches
~ currently only saves last selected env per collection
based off of the below discussion
https://github.com/usebruno/bruno/pull/1971#issuecomment-2326812887

feat: ui-state-snapshot

---

packages/bruno-electron/src/ipc/network/interpolate-vars.js

fix: interpolate json body for type object -- graphql variables

---

packages/bruno-app/src/components/ReorderTable/index.js

fixes: #3191 
This PR implements a refactoring of the `ReorderTable` component used in the `QueryParams`. The refactor focuses on enhancing performance by reducing unnecessary re-renders and recalculations.
- Used `useMemo` to memoize the `rowsOrder`, ensuring it only recalculates when `children` change. 
- Minimizing re-renders during the editing of query parameters, this will fix the cursor jump issue. 
Before:
https://github.com/user-attachments/assets/115d33e9-5165-4cdd-a19f-3da8fb56985e
After:
https://github.com/user-attachments/assets/8f8f3310-03ed-411f-a92f-4f22b3cf08ae

bugfix: Cursor jump on Query Params

---

packages/bruno-js/src/runtime/vars-runtime.js

fixes: #3248 
This PR implements a conditional check for the existence of the key in `v.name` to confirm that the key exists. It then calls `bru.setVar(v.name, value);` to ensure that the value is set only if the key is present.
Before:
https://github.com/user-attachments/assets/d1a74419-b3b7-44ec-b3ba-125bfc33a61b
After:
https://github.com/user-attachments/assets/6d8a5541-4e7c-463d-aed6-5a8cbb029ac6

Handle blank post request variables in request run

---

packages/bruno-app/src/utils/importers/insomnia-collection.js

Solves #3294 
When a user creates a request in insomnia, and sets the auth to "Basic", Insomnia will set the value of username and password to empty string.
BUT if the request has been imported from an older insomnia export, these values may be null instead of an empty string. Insomnia will not change the null value and persist it for future exports, unless the field is modified. This results in the collection failing to import as it hits a .match condition which is expecting a string value.
Steps to reproduce:
1) [Clone, setup and start Bruno](https://github.com/jake-owen-p/bruno/blob/main/contributing.md)
2) Checkout main
3) Create a file named "example.json" and copy/paste the below json into it
4) In Bruno, Click "Import Collection", add "example.json" created on (3)
5) See error …

fix: failing to import insomnia collection when username/password in auth is null

---

packages/bruno-app/src/components/RequestTabs/CollectionToolBar/index.js
packages/bruno-app/src/components/ToolHint/index.js

fixes: #3278 
This PR implements a style fix for the Toolhint component. I have added the z-index for the Toolhint (Tooltip's) UI, allowing it to rise above the tab scroll and the 'Add Request' button when multiple tabs are open.
Additionally, I've added the Tooltip for the `GlobalEnvironmentSelector` component.
Before:
After:

Style: Update `Toolhint` Z-Index and Add Toolhint for `GlobalEnvironmentSelector`

---

packages/bruno-app/src/utils/importers/openapi-collection.js

Fixes: #1239 
Closes PRs: #1240, #2261
1. Instead of separate variables protocol and host, this change creates a single environment variable basePath
2. Loops through all server urls and create environments for each of them separately
3. Creates environments using the server description if that doesnot exists creates environment as Environment 1(2, 3, ...)
https://github.com/user-attachments/assets/b45b1cb8-99bd-4576-984f-d5603159c051

Create default environments on openapi import using server url

---

packages/bruno-app/src/utils/importers/insomnia-collection.js

Importng insomnia files(yaml exports) fails when it contains date values
```
url: https://testbench-sanity.usebruno.com/api/echo/json
name: New Request
description: ""
method: GET
body: {}
parameters:
- id: pair_87d0dc461d5a408a93ebfe0fe500fdce
name: date
value: 2022-22-02
description: ""
disabled: false
- id: pair_8a903b8bf636404288bba577485d6816
name: ""
value: ""
description: ""
disabled: false
```
The YAML parser(js-yaml) automatically converts date values into Date objects, which causes issues while validating collection schema.
I have updated the YAML parsing logic to use the CORE_SCHEMA from js-yaml. This way, we avoid automatic conversion of date.
Issue ref to js-yaml repo: https://github.com/nodeca/js-yaml/issues/161
Note: Keeping the PR small and focused helps make it easier to …

Fix Date Handling in Insomnia Collection Import

---

packages/bruno-app/src/components/RequestTabPanel/index.js
packages/bruno-app/src/providers/ReduxStore/slices/global-environments.js

~ merge `globalEnvironmentVariables` into the active collection and rebuild the `collections` immer proxy object, instead of adding it to the cloned `collection` object.

fix: add global env vars to the active collection

---

packages/bruno-app/src/utils/importers/translators/postman_translation.js

Fixes:  #3061
Addition of two new postman collectionVariable functions mapping to equivalent bruno functions. 
Postman: 
Bruno:

fix: Add missing postman translation functions

---

packages/bruno-electron/src/ipc/network/index.js

Fixes Issue #3233
Previously, `httpsAgentRequestFields` were not applied to `request.httpsAgent` when `shouldProxy` or `shouldUseSystemProxy` was false, resulting in an improper agent configuration.

Fixes Issue #3233: set httpsAgentRequestFields on request.httpsAgent when shouldProxy or shouldUseSystemProxy was false

---

packages/bruno-cli/src/runner/run-single-request.js

fixes the below scenario:
~ if the request fails with an `ECONNREFUSED` error, the cli run summary indicated that the request passed.

fix: cli run-summary count fix for requests with ECONNREFUSED error

---

packages/bruno-app/src/providers/ReduxStore/slices/global-environments.js

~ fixes the promise.then's callback fn

fix: incorrect dispatch fn calls  -- global env slice

---

packages/bruno-app/src/components/CodeEditor/index.js

fix: exclude Meta, Alt, Home and End key press for autocomplete trigger

---

packages/bruno-app/src/components/Sidebar/NewRequest/StyledWrapper.js
packages/bruno-app/src/components/Sidebar/NewRequest/index.js
packages/bruno-app/src/utils/codegenerator/har.js
packages/bruno-app/src/utils/curl/curl-to-json.js
packages/bruno-app/src/utils/curl/index.js

Fixes #3333
https://github.com/user-attachments/assets/3a11093b-38e8-4c33-8e37-e20192b7a08a

Now based on the request type appropriate views are shown.

---

packages/bruno-electron/src/app/watcher.js

fixes: #1928 
This PR implements validation and normalization of the filepath based on its nature, such as a WSL network path or a standard valid path.

fix: enhance path normalization for WSL compatibility in watcher (fix #1928)

---

packages/bruno-app/src/utils/common/codemirror.js

fixes: #2842 
This PR is implemented to improve the app's performance when masking text in the SingleLineEditor. The logic in PR #2240 created a new node for every masked text range. While this logic performs well when the content length is less than 1000 characters, its performance degrades as the length exceeds 1000 characters. In this PR, I've addressed these performance issues.
Changes made:
1. Added an early return if there are no lines in the editor.
2. Limited the previous logic to cases where the number of masked characters is less than 500. This is more efficient for editing small content, such as secret environment variables.
3. For content greater than 500 characters, implemented a line-by-line masking approach to improve performance.
Before: …

fix: improve masking logic in MaskedEditor for large content handling (fixes #2842)

---

packages/bruno-app/src/providers/ReduxStore/slices/global-environments.js
packages/bruno-electron/src/store/global-environments.js

fixes: #3449 
This PR implements logic to check for the existence of duplicate names under global environments to prevent name conflicts.
Before:
https://github.com/user-attachments/assets/12d17ff2-9cdd-4e18-9fb0-57367ff2df31
After:
https://github.com/user-attachments/assets/f3ee88fe-eff9-4165-8fe6-fbfbd78d6f5f

feat: add validation to prevent duplicate global environment names (fixes: #3449)

---

packages/bruno-app/src/utils/importers/openapi-collection.js

Fix: [#3383 ](https://github.com/usebruno/bruno/issues/3383)  Request body not imported from OpenAPI YAML
- It was happening because of the shared Sets. hence used independent Sets for each recursive reference resolution to prevent skipping references.
Fix reference resolution by using independent Sets for recursion
Before:
After:

Fix: (#3383) openapi yaml req body not importing

---

packages/bruno-app/src/utils/collections/index.js

Issue #1615 describes "docs" not exporting to the flat file JSON Bruno format. It appears that element was not getting copied. This patch adds the element to the copy function.

Add "docs" to copy for export (1615)

---

packages/bruno-electron/src/ipc/collection.js
packages/bruno-electron/src/utils/filesystem.js

fixes: #2193  #3645 
This PR implements a fix for #2193. In this PR, I added the `isValidPath` call for only the basename, as expected by `is-valid-path`.
Demo:
https://github.com/user-attachments/assets/fbc989d3-6fa0-4c79-9efa-97f8ad8536ca

fix: update pathname validation to use basename for directory checks #2193

---

packages/bruno-electron/src/ipc/collection.js
packages/bruno-electron/src/utils/filesystem.js

fixes: #160 
This PR implements the logic for sanitizing the collection name and folder name during creation, cloning, or import by trimming leading and trailing spaces, improving navigation between files, and avoiding invalid folder names

refactor: add sanitization for collection and folder name fixes: #160

---

packages/bruno-cli/src/runner/prepare-request.js
packages/bruno-electron/src/ipc/network/prepare-request.js

fixes: #398 
This PR implements a fix for issue #398 by setting the `content-type` to `application/xml` instead of `text/xml` in both **Bruno** and **@usebruno/cli** as per [RFC 7303](https://www.rfc-editor.org/rfc/rfc7303)
Before:
After:

fix: update content-type header for XML requests to application/xml

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/DeleteCollectionItem/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/RenameCollectionItem/index.js

fixes: #3606 
This PR resolves the issue of stale folder settings tabs caused when a folder is renamed or deleted. Additionally, I have added a small feature that displays a notification indicating "Folder renamed" if a folder is renamed. Previously, the notification for both requests and folders showed "Request renamed."

fix: Stale Tabs for Folder Settings on Rename/Delete (fixes: #3606) 

---

packages/bruno-app/src/utils/curl/curl-to-json.js

fixed plain text curl body import

fix: plain text curl data

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/GenerateCodeItem/StyledWrapper.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/GenerateCodeItem/index.js

fixes: #3309 
This PR implements a feature that handles each language tab in the Generate Code modal as a focusable button. This allows users to switch between languages using both mouse clicks and keyboard navigation (Tab and Enter keys).
- Each language tab now has a `role` of button.
- Added `aria-pressed` to indicate the selected language, improving accessibility for users.
- Maintained a fixed width of 1000px.
Before:
https://github.com/user-attachments/assets/b462706f-c102-4d59-999f-679598e9a0ca
After:
https://github.com/user-attachments/assets/37a14f97-53e8-4061-a149-779c3466b9a1

Refactor/ Implement Focusable Buttons in the Generate Code Modal

---

packages/bruno-app/src/utils/importers/postman-collection.js

collection/folder level docs were not getting added when importing postman collection
https://github.com/user-attachments/assets/81c2695c-0b8f-4671-9d17-d699eec49161

fix: collection/folder docs when importing postman collection

---

package-lock.json
packages/bruno-electron/package.json
packages/bruno-electron/src/index.js

Added Redux DevTools and React Developer Tools in dev build

Added `Redux DevTools` and `React Developer Tools` in dev build

---

packages/bruno-app/src/components/CollectionSettings/ClientCertSettings/index.js
packages/bruno-app/src/components/Preferences/General/index.js
packages/bruno-electron/src/preload.js

fixes: #3754 
the nonstandard `path` property of the `Web File` object, added in early electron versions for convenience, has been removed starting with electron 32.0 due to security concerns and deviation from standards. It is now replaced by the [webUtils.getPathForFile](https://github.com/electron/electron/blob/main/docs/api/web-utils.md#webutilsgetpathforfilefile) method.
source: https://github.com/electron/electron/blob/main/docs/breaking-changes.md#removed-filepath

fix: file input element - replace the deprecated path prop

---

packages/bruno-cli/src/commands/run.js

fixes: #3748 for cli
~ fixes the issue where the execution count of the collection post-response script increases with each `setNextRequest` call.
~ the original request object was being modified, and `setNextRequest` was using the modified request with the merged collection post-response script, instead of an unmodified one.
solution:
clone the request item before every execution
before:
---
after:

fix: cli -- collection run -- clone request item at start

---

package-lock.json
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-electron/src/ipc/collection.js

This PR address issue #3541 
I've added a new option in dropdown menu to reveal files in Finder. Additionally, I've implemented support for similar functionality on Windows and Linux.

feature: Reveal in Finder

---

package.json
packages/bruno-electron/package.json

This allows for developers to attach Dev Tools, e.g. the Chrome "dedicated DevTools for node", to the main Electron process for debugging operations that occur on the main process when running the Electron app via `npm run dev:electron:debug`.
See https://www.electronjs.org/docs/latest/tutorial/debugging-main-process for reference.
Related to #3614

feat: Add an npm script to run the Electron app for debugging

---

packages/bruno-app/src/components/CodeEditor/index.js
packages/bruno-app/src/components/RequestPane/RequestBody/index.js

Addressing issue: #3811 
fixed the problem of request variables not being correctly marked, even when they are valid and the request is being processed correctly.

fix: Request vars displayed in red color in body even if they are valid

---

packages/bruno-app/src/providers/ReduxStore/slices/collections/index.js

Addressing issue: #3797 
Fixed: Path table is removed when we rearrange items in query table

Fix: Path table is removed when we rearrange items

---

packages/bruno-app/src/components/CollectionSettings/Docs/StyledWrapper.js
packages/bruno-app/src/components/CollectionSettings/Docs/index.js
packages/bruno-app/src/components/FolderSettings/Documentation/index.js

added save button for collection/folder docs

add: document save button for folder and collection settings

---

packages/bruno-app/src/components/Environments/EnvironmentSelector/index.js

This PR fixes an issue where clicking "Configure" from the environment dropdown opened a modal without hiding the dropdown. The fix ensures a smoother user experience by properly closing the dropdown when the modal appears.
https://github.com/user-attachments/assets/a4bc44a5-0fb9-463a-9d5b-c398e48e4eef

Fix: hide environment dropdown on configure

---

packages/bruno-app/src/components/MarkDown/StyledWrapper.js

Addressing issue: #3733 
Fixed styling for Horizontal Rules in markdown preview section

Fix: Horizontal Rules missing in markdown docs preview

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/index.js

Previously, if you wanted to expand a collection, you had to click on the name of the collection. In this pr, I expanded the area of click from the name to the entire tile of the collection.
https://github.com/user-attachments/assets/602e230a-19e0-4685-9d25-6298494f0a2d

Moved collection click area from name to div

---

packages/bruno-app/src/components/Modal/index.js
packages/bruno-app/src/components/Sidebar/ImportCollection/index.js

There are two modals in question, one is import modal and the modals that gets opened when we click on each of the type. our common modal component have event listeners for <b>ESC</b> , <b>ENTER</b> keys, outer modal has "onClose" which gets triggered when user press <b>ENTER</b> , this closes the outer modal, as the inner modals are within the outer modal, those also gets removed from the dom. 
currently i removed handleConfirm function for outer modal, so that Pressing on ENTER to not to trigger modal closing, ESC closes the modal as before. also made the handleConfirm prop optional
Additionaly, the  <b>handleConfirm</b> function we use within the callback for key-press event is not updated as it is not added as the dependency for useEffect, they continue to use the older handleConfirm, …

Fix: Import collection modal closes when click on ENTER

---

package-lock.json
packages/bruno-electron/package.json

Currently url that contains ipv6 throws an error as reported in [this issue](https://github.com/usebruno/bruno/issues/2338)
This PR bumps axios version to 1.7.7 that has the ipv6 fix ([axios PR](https://github.com/axios/axios/pull/5731))

fix: bump axios version to handle ivp6

---

packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-app/src/utils/common/platform.js

fixes: #3401 
This PR implements a feature to better handle path functions between Windows OS and other systems based on the nature of the path. It resolves the issue mentioned above, where a WSL request cannot be cloned if it is present in a folder.

fix: handle Windows paths in cloneItem and getDirectoryName functions (fixes: #3401)

---

packages/bruno-electron/src/utils/collection.js

#3723 
https://datatracker.ietf.org/doc/html/rfc7230#section-3.2
workaround for the above issue:
use `content-type` instead of `Content-Type`

use lowercase header keys while making requests

---

packages/bruno-app/src/components/CodeEditor/index.js

Initially Implemented in #2634 and regressed on #3462
Closes #1451
Enable back comment toggling for JSON in request body editor.
This maps both `Cmd+/` and `Ctrl+/` for toggling-comment.
https://github.com/user-attachments/assets/b9befc87-3d85-44ce-b070-347c67eaef60

Fix: Enable back comment toggling for JSON in request body editor

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-electron/src/ipc/collection.js

Duplicate of #3698
Closes #3541
On clicking the triple-dot menu(kebab menu?) on a Folder or a Request, a new menu-item named `Show in Folder` is added which opens it in the native file-browser(Finder, File-Explorer, Nautilus, Ranger, etc.)

Added a menu-item to show Folder and Requests in native file-browser

---

package.json
packages/bruno-electron/package.json

Duplicates #3616
Closes #3614
https://www.electronjs.org/docs/latest/tutorial/debugging-main-process

Add an npm-script to run the Electron app with debugging enabled (#3616)

---

packages/bruno-cli/src/commands/run.js
packages/bruno-cli/src/runner/run-single-request.js
packages/bruno-cli/src/utils/collection.js
packages/bruno-electron/src/ipc/network/index.js
packages/bruno-tests/collection/ping-another-one.bru
packages/bruno-tests/collection/scripting/api/bru/runRequest-1.bru
packages/bruno-tests/collection/scripting/api/bru/runRequest-2.bru
packages/bruno-tests/collection/scripting/api/bru/runRequest.bru
packages/bruno-tests/collection/scripting/api/bru/runner/1.bru
packages/bruno-tests/collection/scripting/api/bru/runner/2.bru
packages/bruno-tests/collection/scripting/api/bru/runner/3.bru

~ fixes the variables set/get inconsistency with `bru.runRequest` executions
~ adds support for `bru.runRequest` and bru runner util functions support to cli
before:
after:
https://github.com/user-attachments/assets/aa133dee-feb0-4fd7-a287-343f8c48113e

ensure variables set in scripts/tests of the request executed by `bru.runRequest` should reflect in the original request' scripts/tests

---

packages/bruno-app/src/utils/importers/openapi-collection.js

Addressing issue: https://github.com/usebruno/bruno/issues/3663, https://github.com/usebruno/bruno/issues/3631
Fixed OpenAPI collection import failure when handling circular references in the specification. Previously, the application would crash with a `RangeError: Maximum call stack size exceeded` error when trying to import OpenAPI collections containing circular references.
- Improved `resolveRefs` function to properly handle circular references
- Implemented caching mechanism using Map to store resolved references
- Added proper handling of intermediate states during reference resolution
- Prevented infinite recursion while maintaining the integrity of the imported collection

fix: resolve function recusion

---

packages/bruno-electron/src/ipc/collection.js

This PR implements a fix for the update variable, which might have gone unnoticed at the time of the merged PR #3834. A variable name was updated, and because of this change, collections are no longer clonable in the latest main branch.

Fix: Update variable for `clone-collection`

---

packages/bruno-cli/src/runner/run-single-request.js
packages/bruno-electron/src/ipc/network/index.js

Issues: #2102, #1944 
When a user sends the first request with a user-defined Cookie header, the request works as expected. However, the response from the server may include Set-Cookie headers. When the user sends a subsequent request, these cookies overwrite the user-defined cookies, leading to unexpected behavior.
Solution
This PR resolves the issue by merging the user-defined Cookie header with the cookies received from the server's Set-Cookie response. Both sets of cookies are now combined into a single Cookie header, ensuring that user-defined cookies are preserved while including any additional cookies set by the server.
https://github.com/user-attachments/assets/dcd19ef4-db2a-415b-9fa1-52f3e739c259

Fix: user defined cookies getting overwritten by stored cookies

---

packages/bruno-app/src/components/ResponsePane/QueryResult/index.js
packages/bruno-app/src/utils/common/codemirror.js
packages/bruno-app/src/utils/common/index.js

issue ticket : #3781 
i have added functionality to handle image/svg+xml contentType in getContentType function previously it is treating image/svg + xml as application/xml that is not allowing it to render on ui, now user can see image preview as well raw.
in getCodeMirrorModeBasedOnContentType i moved image condition to before the xml to handle both seamlessly . 

fix:handle render svg response

---

packages/bruno-electron/src/ipc/collection.js
packages/bruno-electron/src/utils/filesystem.js

fixes: #3880 
This PR implements logic to improve the `sanitizeCollectionName` utility function, to ensure that invalid characters in the collection name are properly replaced by `-`.

Fix: Import failing for collections with special characters in Windows

---

packages/bruno-app/src/utils/importers/translators/postman_translation.js

There was an error in one of the WIP feature which is breaking the translation, for now commenting it out.

Fix: Postman-import-translation not adding comments for unsupported APIs

---

.github/workflows/tests.yml

Update read permissions in CLI tests workflow

Fix: CLI-Tests Workflow lacks contents:read permission

---

packages/bruno-app/src/utils/importers/postman-collection.js

This PR updates the import functionality to ignore requests with unsupported custom HTTP methods instead of failing the entire import.

Fix: Handle Unsupported Custom HTTP Methods in Postman Collection Import

---

packages/bruno-app/src/components/CollectionSettings/ProxySettings/index.js
packages/bruno-app/src/components/CollectionSettings/Vars/VarsTable/index.js
packages/bruno-app/src/components/FolderSettings/Vars/VarsTable/index.js
packages/bruno-app/src/components/InfoTip/index.js
packages/bruno-app/src/components/RequestPane/QueryParams/index.js
packages/bruno-app/src/components/RequestPane/Vars/VarsTable/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CloneCollection/index.js
packages/bruno-app/src/components/Sidebar/CreateCollection/index.js
packages/bruno-app/src/components/ToolHint/index.js

- Refactor ToolHint to use `text` prop as text instead of HTML
- Currently there is no usage of ToolHint where we are passing HTML
content, so this should not break anything.
- Refactoring InfoTip to support just text and children instead of HTML

Tooltip Improvements

---

packages/bruno-app/src/components/CollectionSettings/Docs/StyledWrapper.js

Fixed extra space on top of collection docs editor

Fix: space on collection docs editor

---

packages/bruno-app/src/components/Notifications/index.js

This is to allow is to allow users to open web pages (like bruno downloads) from the app inside Notifications

fix: allow popus in notification iframes

---

packages/bruno-app/src/components/CodeEditor/index.js

fixes #4035 
https://github.com/user-attachments/assets/20625add-14be-4840-9ac9-e07825f7cf09
https://github.com/user-attachments/assets/73860267-ba7d-4010-8488-26d4402738b0
cmd + f, ctrl + f, triggers duplicate search fields

fix: remove duplicate search components

---

packages/bruno-app/src/components/RequestPane/HttpRequestPane/index.js

fixes: #3089 
auto select the body tab when opening requests if body is present but params aren't present or active.
https://github.com/user-attachments/assets/b9c20203-9726-4a51-9611-82e0db9b2109

feat: auto select body tab if it exists when params isnt active

---

packages/bruno-app/src/components/CollectionSettings/Overview/Info/index.js

Updated share collection color theme

chore: updated share collection color theme

---

packages/bruno-app/src/utils/importers/postman-collection.js

Issue: #4190 
Postman can have schema.postman.com as schema url, so it can break import in bruno because of our current implementation

Fix: New postman schema url fails import

---

packages/bruno-app/src/components/CodeEditor/index.js
packages/bruno-js/src/bruno-response.js
packages/bruno-js/src/sandbox/quickjs/shims/bruno-response.js
packages/bruno-tests/collection/scripting/api/res/getStatusText.bru

This PR implements the `res.getStatus()` API feature and adds support for `res.statusText` in safemode

Fix/ Support `res.statusText` in safe mode and add `getStatus()` API

---

packages/bruno-app/src/components/Sidebar/Collections/index.js

This PR amends the search bar placeholder to be more descriptive on what can be searched. Thank you!
| Before | After |
|--------|--------|
| ![Screenshot 2025-01-05 at 12 49 32](https://github.com/user-attachments/assets/bc6333f7-67fd-445c-8348-21e5802693c8) | ![Screenshot 2025-01-05 at 12 49 49](https://github.com/user-attachments/assets/bc00cfb8-8485-4ae8-bb03-739ad15e497e) | 
Fixes https://github.com/usebruno/bruno/issues/3730

chore: rephrase placeholder for clarity

---

packages/bruno-app/src/providers/ReduxStore/slices/collections/index.js

Adresses: https://github.com/usebruno/bruno/issues/1974
Sorts collections by name in alphabetical order
Collections with numbers in the names are sorted in numerical order.
Results in `['Test 10', 'Test 2', 'Test 1']`
being sorted to: `['Test 1', 'Test 2', 'Test 10']` instead of: `['Test 1', 'Test 10', 'Test 2']`
Accurately sorts numbers with decimals as well.

feat: Natural sort collection names with numbers

---

contributing.md
docs/contributing/contributing_bn.md
docs/contributing/contributing_cn.md
docs/contributing/contributing_de.md
docs/contributing/contributing_es.md
docs/contributing/contributing_fr.md
docs/contributing/contributing_hi.md
docs/contributing/contributing_it.md
docs/contributing/contributing_ja.md
docs/contributing/contributing_kr.md
docs/contributing/contributing_nl.md
docs/contributing/contributing_pl.md
docs/contributing/contributing_pt_br.md
docs/contributing/contributing_ro.md
docs/contributing/contributing_ru.md
docs/contributing/contributing_sk.md
docs/contributing/contributing_tr.md
docs/contributing/contributing_ua.md
docs/contributing/contributing_zhtw.md

As a developer who hasn't worked on many npm projects using workspaces, I wasn't aware how npm has the ability to [run a command over all the workspaces ](https://docs.npmjs.com/cli/v10/using-npm/workspaces#running-commands-in-the-context-of-workspaces). This means with this one-liner, a developer can easily run nearly all of the test suites in one go.
So off the back of this, this PR changes the contributing documentation _slightly_ to make it clearer it's possible to run the tests over the whole project rather than having to run them one by one.
Note, once I get a thumbs up emoji/an affirmative comment that is a welcomed change, then I'll make the change to all the different languages using auto-translation tools to amend the `# run tests over all workspaces` comments into respective …

[DX]: Document running test suite for all workspaces

---

packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js

Fix #2315
When I configure auth at a collection or folder level, I want the children of that folder to have the same auth by default.
- Changing default behavior here probably does count as a breaking change, since anyone depending on the old behavior could be surprised.  Maybe you want to delay it until v3?  But IMO it's the right change to make.

UI: Change the default request auth mode from "none" to "inherit"

---

packages/bruno-app/src/components/PathDisplay/StyledWrapper.js
packages/bruno-app/src/components/PathDisplay/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/CloneCollectionItem/StyledWrapper.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/CloneCollectionItem/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/CollectionItemInfo/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/RenameCollectionItem/StyledWrapper.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/RenameCollectionItem/index.js
packages/bruno-app/src/components/Sidebar/NewFolder/StyledWrapper.js
packages/bruno-app/src/components/Sidebar/NewFolder/index.js
packages/bruno-app/src/components/Sidebar/NewRequest/StyledWrapper.js
packages/bruno-app/src/components/Sidebar/NewRequest/index.js

Instead of showing the filesystem name by default (which might not be needed for the majority of the audience), we now have moved it to "Advanced Options" dropdown

feat: custom filename can be shown by clicking advanced options

---

packages/bruno-app/src/components/ResponsePane/Timeline/TimelineItem/Request/index.js
packages/bruno-app/src/components/ResponsePane/Timeline/TimelineItem/Response/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-app/src/utils/common/index.js
packages/bruno-electron/src/ipc/network/axios-instance.js
packages/bruno-electron/src/utils/oauth2.js

remove dataBuffer from debugInfo timeline objects since its directly derived from request/response data at all times and can be created directly in the ui comp.
[only for request not from the sendRequest flow]

handle oauth2 timeline response, remove dataBuffer from debugInfo obj

---

packages/bruno-electron/src/utils/proxy-util.js

Fix For: #3747, #4317
TLS agent setting was not properly getting passed form TimelineAgent to BaseAgent, this PR fixes the issue

Fix: TLS settings not applying to proxied connections

---

package-lock.json
package.json

There were few transitive `devDependencies` of `electron-store` -> `conf` which were sketchy.
Although those will never gets installed in any case, its better not to have them in the first place.
A better option is to upgrade `electron-store` itself to latest where its fixed, but they moved to ESM-only and we cannot upgrade easily.

Fix: Remove unwanted transitive `devDependencies` of `electron-store`

---

packages/bruno-app/src/utils/importers/postman-collection.js

fixes: #4277 
This PR introduces a logic where a Postman collection with an empty name, an empty folder name, or an empty request name will receive default names and be added to the import, ensuring a successful import. With this, users can import the collection and change the names afterward instead of creating the names first and then importing it into Bruno.

Feat/ Set default names for folders and requests in Postman collection importer (fixes: #4277)

---

packages/bruno-js/src/runtime/script-runtime.js

Same as https://github.com/usebruno/bruno/pull/795 but adding the functionality to the response scripts as well.

feat(scripting): allow multiple script context roots in response scripts

---

packages/bruno-app/src/utils/importers/postman-collection.js

fixes: #4379 
This PR updates the `importScriptsFromEvents` and `importPostmanV2CollectionItem` functions to properly handle cases where `event.script.exec` is an empty array. Now, if `exec` is empty, `requestObject.script.req` and `requestObject.tests` are set to empty strings instead of being thrown as an error.

fix: handle empty script.exec cases in postman collection importer

---

packages/bruno-cli/src/commands/run.js
packages/bruno-cli/src/utils/filesystem.js

This PR is related to this issue: https://github.com/usebruno/bruno/issues/4055

fix unsupport symbolic link folders

---

packages/bruno-electron/src/utils/oauth2.js

This PR resolves two related issues in the OAuth2 refresh token flow:
- **Avoids duplicate entries** in the network logs when making refresh token calls.
- **Clears stored token credentials** if the refresh token call fails

Oauth2 refresh token call fixes

---

packages/bruno-electron/src/ipc/network/prepare-request.js
packages/bruno-electron/src/utils/collection.js

This PR fixes issue #4052 where header key variables containing capital letters were not being properly interpolated in version 1.39. The issue occurred because header names were being converted to lowercase during the merging process, which prevented variable interpolation from working correctly for header keys with capital letters

fix: header key variables not interpolating with capital letters

---

packages/bruno-electron/src/ipc/network/index.js

Addressing issue https://github.com/usebruno/bruno/issues/4100
This PR fixes an issue where global environment variables set using `bru.setGlobalEnvVar()`  in test scripts were not being saved correctly during a collection run.
- When running multiple requests in a collection, if a test script updated a global environment variable, the next request didn't see the updated value.
- This issue only happened with test scripts. Pre-request and post-response scripts were already working fine.
https://github.com/user-attachments/assets/be35dfea-53b2-43c3-bb32-215f6af575f2

fix: update global env in collection runner

---

packages/bruno-cli/src/commands/run.js

Addressing issue: https://github.com/usebruno/bruno/issues/4155
This PR fixes an issue with the --bail option in the Bruno CLI where skipped requests were being treated as failures. When using` bru.runner.skipRequest()` in a pre-request script, the CLI would abort the entire run if the --bail flag was used, even though skipping a request is not a failure condition.

Fix: Prevent --bail option from treating skipped requests as failures

---

packages/bruno-electron/src/ipc/network/interpolate-vars.js

- Fix: Line-breaks in `$<mock>` built-ins are breaking JSON req body
- Fix: Falsy values from `$<mock>` built-ins are not getting interpolated

Fix: Mock/Random built-in variables related issues

---

package-lock.json
scripts/setup.js

Closes #4488
without this I couldn't get started with local dev `npm run setup`

Fix: Missing bruno-requests module in `setup.js` and `package-lock.json`

---

packages/bruno-js/src/runtime/script-runtime.js
packages/bruno-tests/collection/scripting/inbuilt modules/cheerio/cheerio.bru
packages/bruno-tests/collection/scripting/inbuilt modules/xml2js/xml2js.bru

Addresses #4515: #3976 introduced cheerio and xml2js modules to be used within scripts and tests. Unfortunately they forgot to add the modules to the post-response script runtime, so it is not available there. 
This PR adds these modules + expands the existing tests

Bugfix: Add cheerio and xml2js modules to post-response scripts

---

packages/bruno-app/src/components/FolderSettings/Headers/index.js
packages/bruno-app/src/components/RequestTabPanel/index.js

This PR enhances the handling of folder tabs during drag-and-drop operations to prevent crashes and improve user experience. 
1. Added automatic tab closure when a folder is moved to a new location in the collection hierarchy
2. Previously, when performing certain folder movements (like nesting folders), the folder settings tab would remain open but could no longer find the folder in its original location, causing errors
3. Now, when a folder is moved and its settings tab is open, the application automatically closes that tab to prevent accessing invalid folder references
- When dragging `Folder 1` into `Folder 2`, any open settings tab for `Folder 1` is automatically closed
https://github.com/user-attachments/assets/317e8d7a-c8f3-4dd7-9acd-b648678769dc …

Fix: Folder drag-and-drop crash

---

packages/bruno-js/src/runtime/vars-runtime.js

Fixes issue https://github.com/usebruno/bruno/issues/4491
In the runPostResponseVars
1. The `Bru` constructor wasn't receiving all variables
2. The result object from `runPostResponseVars` wasn't properly including global environment variables

Include globalEnvironmentVariables in runPostResponseVars result

---

packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/CollectionItemDragPreview/StyledWrapper.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/CollectionItemDragPreview/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/StyledWrapper.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/index.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/StyledWrapper.js
packages/bruno-app/src/components/Sidebar/Collections/Collection/index.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js
packages/bruno-app/src/providers/ReduxStore/slices/collections/index.js
packages/bruno-app/src/utils/collections/index.js
packages/bruno-electron/src/app/watcher.js
packages/bruno-electron/src/ipc/collection.js
packages/bruno-electron/src/utils/filesystem.js

~ persist the file/folder uids after file/folder re-sequencing
&nbsp;&nbsp;&nbsp;&nbsp; [ this keeps the opened request/folder tabs valid after re-sequencing ]
~ ui updates for file/folder sequencing ux

persist request/folder uids after request/folder resequencing and ui updates

---

packages/bruno-app/src/components/ResponsePane/ResponseSize/index.js
packages/bruno-app/src/components/ResponsePane/index.js

Fixes: #4573 
[Jira](https://usebruno.atlassian.net/browse/BRU-1091)
- Added handling for undefined and invalid values for `response.size` in the **ResponsePane** and **ResponseSize** components.
- This check ensures that only valid numeric sizes, including `0`, are allowed.
The following values are now excluded to prevent crashes or unexpected behavior:
- `undefined`  
- `null`  
- `NaN`  
- `Infinity`  
- `-Infinity`  
- Non-numeric types (e.g., strings, objects)

Fix: ResponseSize component logic to handle size when it's undefined

---

packages/bruno-app/src/utils/common/regex.js
packages/bruno-electron/src/utils/filesystem.js

Closes #4350
Fixes Regression #4350: Restore dot-prefixed folder support (e.g., .bruno) as valid collection locations, broken in v1.40.0.

Fix: Leading dot is not allowed for collections, folders and requests

---

packages/bruno-app/src/components/RequestTabPanel/FolderNotFound/index.js
packages/bruno-app/src/components/RequestTabPanel/index.js
packages/bruno-app/src/components/RequestTabs/RequestTab/index.js

Fixed app crash when trying to interact with renamed folders. Previously, the app would crash with a React error when a folder was renamed in the file system and the user tried to interact with its tab in Bruno.

fix: app crash when we rename folder in fs

---

packages/bruno-cli/src/runner/prepare-request.js
packages/bruno-cli/tests/runner/prepare-request.spec.js

Fixed authentication inheritance for AWS v4, NTLM, and WSSE authentication types, and added direct API key authentication support for requests.
Fixes: https://github.com/usebruno/bruno/issues/3688

feat: extend cli auth for inherit and request

---

packages/bruno-app/src/components/Sidebar/CreateCollection/index.js
packages/bruno-app/src/components/Sidebar/ImportCollectionLocation/index.js
packages/bruno-app/src/components/Sidebar/TitleBar/index.js
packages/bruno-app/src/providers/Toaster/index.js
packages/bruno-app/src/utils/common/error.js
packages/bruno-app/src/utils/common/index.js

- Improved error-toast for creating and importing collections
- Added a util for formatting the error form IPC
- Updated Toast global styles to prevent text overflow.
Whenever long file paths are shown, it overflows the Toast container.
- Fix: Import-collection select-location Modal closes on error
- Fix: Improve UX for selecting location when create/import collection
- Allow editing the input path where previously the `<input>` is marked
`readonly`.
Also this will allow automating test using Playwright.
|||
|-|-|
|![image](https://github.com/user-attachments/assets/3d40ebed-a54f-41d7-aa7f-234430b317c9)|![image](https://github.com/user-attachments/assets/0cd89ada-7cc4-4c97-b1d9-f5db19c30069)|
|![image](https://github.com/user-attachments/assets/23a4ba17-3917-4f84-a426-5b50b7d6c403)|

Create/Import collection UX improvements

---

contributing.md
packages/bruno-electron/src/index.js

If `ELECTRON_APP_NAME` env-variable is present and its dev env, then the `appName` and `userData` path is modified accordingly.
e.g.
```sh
ELECTRON_APP_NAME=bruno-dev npm run dev:electron
```
Note: This doesn't change the name of the window or the names in lot of other places, only the name used by Electron internally.

Added option to customize `userData` path on dev mode

---

package.json
packages/bruno-graphql-docs/package.json
packages/bruno-query/package.json
packages/bruno-requests/package.json
scripts/dev-hot-reload.js

This PR introduces a streamlined command that allows developers to set up and start the development servers with file watchers in a single step.
To install/re-install dependencies and then start the dev servers:
`npm run dev:watch -- --setup`
To start the dev servers assuming all packages are already installed and up to date:
`npm run dev:watch`

feat(dev): enhance hot reload development setup

---

packages/bruno-app/src/components/RunnerResults/index.jsx
packages/bruno-app/src/providers/ReduxStore/slices/collections/index.js
packages/bruno-electron/src/ipc/network/index.js

This PR adds support for pre-request and post-response test results in the collection runner, making test results from script:pre-request and script:post-response blocks visible in the runner results UI.
Changes

add: pre and post tests in runner

---

packages/bruno-cli/src/commands/run.js

Jira: [BRU-1210](https://usebruno.atlassian.net/browse/BRU-1210)
This PR adds support for `.bru` files by allowing both relative and absolute paths. This enables us to attach environments via the CLI from anywhere in the filesystem.
Demo:
Absolute path:
Relative Path:

feat(cli): add support for environment file input in run command

---

packages/bruno-app/src/components/RequestPane/QueryParams/index.js

- Rename `Path` to `Value` in the Query Params table.
- File changed: `packages/bruno-app/src/components/RequestPane/QueryParams/index.js`
Screenshot:

rename query table value from path to value

---

packages/bruno-electron/src/index.js

fixes: https://github.com/usebruno/bruno/issues/5450
Recently, we added Electron’s `globalShortcut` to register `CmdOrCtrl+M` and `CmdOrCtrl+H`. However, `globalShortcut` works system-wide, which caused Bruno to intercept these key combinations even when other applications were in focus. As a result, the shortcuts were hijacked and other apps lost their native behavior (e.g., `Cmd+M` to minimize the active app in macOS).

Refactor: Remove use of `globalShortcut` for minimize/hide to avoid hijacking system shortcuts

---

packages/bruno-app/src/components/Preferences/Beta/index.js

Update the gRPC tagline:
> Beta features are experimental previews that may change before full release. Try them and [share feedback](https://github.com/usebruno/bruno/discussions/5447).
File changed: `src/components/Preferences/Beta/index.js`

update the grpc tagline

---

packages/bruno-app/src/components/RequestPane/GrpcRequestPane/GrpcAuth/GrpcAuthMode/index.js
packages/bruno-app/src/components/RequestPane/GrpcRequestPane/GrpcAuth/index.js
packages/bruno-electron/src/ipc/network/grpc-event-handlers.js
packages/bruno-electron/src/ipc/network/prepare-request.js
packages/bruno-electron/tests/prepare-request.test.js

Fixes #5448 
[Jira ticket](https://usebruno.atlassian.net/browse/BRU-1832)
- Introduced WSSE authentication mode in GrpcAuth component.
- Updated supported authentication modes to include WSSE.
- Refactored gRPC event handlers to streamline authentication header setting.
- Added notes regarding limitations of complex auth modes in gRPC.
- Replaced `setGrpcAuthHeaders` with `setAuthHeaders` to fix problems with oauth in grpc requests
https://github.com/user-attachments/assets/e97293c2-cb5c-4ff4-9ed5-652686d504e5

feat: add WSSE authentication support to gRPC requests

---

scripts/count-locs.js

Adds a script to compute and print Lines of Code (LOC) across repo packages. This is needed for reporting to security vendors and will be useful to retain for future audits or usage.
[JIRA](https://usebruno.atlassian.net/browse/BRU-1087)

feat: script to calculate locs of repo

---

packages/bruno-app/src/components/GlobalSearchModal/index.js

This PR adds optional chaining operators (`?.`) to the GlobalSearchModal component to prevent app crash if request name is not there

fix: Add null safety checks in GlobalSearchModal

---

packages/bruno-app/src/components/RequestTabs/DraggableTab.js
packages/bruno-app/src/components/RequestTabs/index.js

Replaces the UI from #5413 to use `react-dnd` instead since the codebase already uses it for movement in other places. 
https://github.com/user-attachments/assets/973984e0-eded-41bc-b08b-55b146399878

feat: add draggable tabs component

---

packages/bruno-cli/src/runner/prepare-request.js
packages/bruno-cli/src/utils/filesystem.js
packages/bruno-cli/tests/runner/prepare-request.spec.js
packages/bruno-cli/tests/utils/filesystem.spec.js
packages/bruno-electron/src/ipc/network/prepare-request.js
packages/bruno-electron/src/utils/filesystem.js
packages/bruno-electron/src/utils/filesystem.test.js

[JIRA](https://usebruno.atlassian.net/browse/BRU-1773)
Fixes: https://github.com/usebruno/bruno/issues/5340
Bruno crashes with a "JavaScript heap out of memory" error when uploading large files (e.g., 367MB MP4 files) in file body mode. The issue occurs because the entire file is loaded into memory using `fs.readFile()`.
- **Small files (≤100MB)**: Use `fs.readFileSync()` for better performance
- **Large files (>100MB)**: Use `fs.createReadStream()` for streaming upload to prevent memory overflow

fix: improve file upload handling in prepare-request to use streaming

---

packages/bruno-app/src/components/GlobalEnvironments/EnvironmentSettings/EnvironmentList/EnvironmentDetails/EnvironmentVariables/index.js
packages/bruno-app/src/components/MultiLineEditor/StyledWrapper.js
packages/bruno-app/src/components/MultiLineEditor/index.js
packages/bruno-schema/src/collections/index.js
tests/collection/create/create-collection.spec.ts
tests/collection/moving-requests/cross-collection-drag-drop-folder.spec.ts
tests/collection/moving-requests/cross-collection-drag-drop-request.spec.ts
tests/collection/moving-requests/tag-persistence.spec.ts
tests/collection/open/open-multiple-collections.spec.ts
tests/global-environments/collection/bruno.json
tests/global-environments/collection/set-global-nonstring.bru
tests/global-environments/init-user-data/preferences.json
tests/global-environments/non-string-values.spec.ts
tests/utils/page/actions.ts

[JIRA](https://usebruno.atlassian.net/browse/BRU-716)
**Fix:**
- Allow mixed types in environment variable schema (`value: Yup.mixed().nullable()`)
- Non-string values are read-only in UI with warning tooltip
- String values remain fully editable
- Maintains backward compatibility with existing string-only environments
https://github.com/user-attachments/assets/6b429158-d931-46ad-9951-1ef0556cb94a

feat: Enhance EnvironmentVariables component with read-only support for non-string values

---

packages/bruno-app/src/utils/codemirror/autocomplete.js
packages/bruno-cli/src/runner/prepare-request.js
packages/bruno-electron/src/ipc/network/prepare-request.js
packages/bruno-js/src/bruno-request.js
packages/bruno-js/src/sandbox/quickjs/shims/bruno-request.js
packages/bruno-tests/collection/scripting/api/req/getTags.bru

Add support for `tags` ~~and `metadata`~~ with the `req` object while scripting.
Easily leverage this information to better create scripting logic for differing scenarios. 
Examples:
- Pre-request: if a specific tag is present -> skip the request when using the runner
- Post-request: if a specific tag is present -> set the next request to x
- Test scripts: does the request contain x tags -> pass
**Request Tags**
**Tests with Valid Tags and Metadata Passing**
**Tests with Invalid Tags Failing**
**req.getTag() in Script**
~~**req.getMetadata() in Script**~~
- https://github.com/usebruno/bruno/issues/5689  …

adding req getTags methods

---

packages/bruno-cli/src/utils/collection.js

fixes: https://github.com/usebruno/bruno/issues/5710
related to: https://github.com/usebruno/bruno/issues/5685
This PR implements the logic for ignoring, skipping, and reporting invalid `.bru` files in the collection. This solves the issue where invalid files prevent the collection from running properly.
Before:
After:

feat(cli): ignore and skip invalid `.bru` file

---

packages/bruno-lang/v2/src/envToJson.js
packages/bruno-lang/v2/src/utils.js
packages/bruno-lang/v2/tests/utils.spec.js

Jira: BRU-1937
fixes: #5670
This PR implements the logic for removing the forced `normalizeNewLines` since it is interfering with the existing CRLF.

Refactor: Remove `normalizeNewlines` function and update tests to preserve newline types

---

packages/bruno-app/src/components/ResponsePane/ResponseSize/ResponseSize.spec.js

fixes #5732 
This PR fixes 4 tests that were failing if the user testing was on a different locale than `EN`.
File `packages/bruno-app/src/components/ResponsePane/ResponseSize.spec.js`, the following tests :
- "should handle exactly 1024 bytes as size"
- "should render kilobytes when size is greater than 1024"
- "should handle large size numbers"
- "should handle decimal size numbers"
Because these tests directly use locale dependent **magic strings** :
This string is computed in the `ResponseSize` component using the method `number.toLocaleString()`
This method documentation says :
Because these tests seem to "just" check if the title is set, computing the "locale string" in the test before the assertion is acceptable **(won't break the nature of the test)** and will works for everybody. …

fix: fixing tests using locale on numbers
